ami-iit/bipedal-locomotion-framework

- .clang-format
- CHANGELOG.md
- CMakeLists.txt
- README.md
- cmake/AddInstallRPATHSupport.cmake
- cmake/AddUninstallTarget.cmake
- cmake/BipedalLocomotionControllersFindDependencies.cmake
- cmake/FindEigen3.cmake
- cmake/InstallBasicPackageFiles.cmake
- src/CMakeLists.txt
Before merging I would like to:
> Add cmake skeleton

- CHANGELOG.md
- CMakeLists.txt
- README.md
- cmake/BipedalLocomotionControllersFindDependencies.cmake
- src/CMakeLists.txt
- src/YarpUtilities/CMakeLists.txt
- src/YarpUtilities/include/BipedalLocomotionControllers/YarpUtilities/Helper.h
- src/YarpUtilities/include/BipedalLocomotionControllers/YarpUtilities/Helper.tpp
- src/YarpUtilities/src/Helper.cpp
- src/YarpUtilities/tests/CMakeLists.txt
- src/YarpUtilities/tests/YarpUtilitiesTest.cpp
- src/YarpUtilities/tests/YarpUtilitiesTestMain.cpp
This PR:
1.  implements the first version of the `YarpUtilities` library
2. Implement the tests for the aforementioned library 
3. Update the `CHANGELOG.md` file
> Implement Yarp Utilities library

- .github/workflows/ci.yml
> Add CI pipeline with Github Actions

- .github/workflows/ci.yml
- CMakeLists.txt
- cmake/AddBipedalLocomotionControllersUnitTest.cmake
- cmake/BipedalLocomotionControllersFindDependencies.cmake
- cmake/Catch2Main.cpp.in
- cmake/FindVALGRIND.cmake
- src/ParametersHandler/tests/CMakeLists.txt
- src/ParametersHandler/tests/ParametersHandlerYarpTestMain.cpp
- src/YarpUtilities/tests/CMakeLists.txt
They are set to ``OFF`` by default.
> Added valgrind tests.

- .github/workflows/gh-pages.yml
The code has been taken from [here](https://github.com/robotology/how-to-document-modules#octocat-automatic-documentation-aka-let-github-do-the-job-for-us)
> Enable automatic Doxygen documentation generation

- CMakeLists.txt
- cmake/AddBipedalLocomotionControllersComponent.cmake
- src/ParametersHandler/CMakeLists.txt
- src/ParametersHandler/YarpImplementation/CMakeLists.txt
- src/YarpUtilities/CMakeLists.txt
This PR implements the `add_bipedal_component` cmake function. 
This should closes #24
> Add a custom cmake function for enhancing the components compilation

- src/GenericContainer/CMakeLists.txt
> Fix typo in GenericContainer CMakeLists.txt file

- .github/workflows/ci.yml
Thi PR should fix the failing of the CI caused by the remaining of the repository.
> Update the CI workflow

- cmake/AddBipedalLocomotionLibrary.cmake
> Update the AddBipedalLocomotionLibrary.cmake 

- src/System/include/BipedalLocomotion/System/Advanceable.h
> Fix missing vitual keyword in Advanceable class

- src/ParametersHandler/CMakeLists.txt
- src/ParametersHandler/include/BipedalLocomotion/ParametersHandler/IParametersHandler.h
- src/ParametersHandler/include/BipedalLocomotion/ParametersHandler/StdImplementation.h
- src/ParametersHandler/include/BipedalLocomotion/ParametersHandler/StdImplementation.tpp
- src/ParametersHandler/src/StdImplementation.cpp
- src/ParametersHandler/tests/ParametersHandlerTest.cpp
> Move the ParameterHanlder::BasicImplementation from tests to the library

- src/Planners/src/ContactPhaseList.cpp
> Bugfix in ContactPhaseList::cbegin() function

- CMakeLists.txt
- cmake/BipedalLocomotionFrameworkFindDependencies.cmake
- cmake/InstallIniFiles.cmake
This is required to #62 in order to install the ini files and write a README.
> Set possibility to force enabling a dependency and added macro to install ini files

- src/Planners/CMakeLists.txt
- src/Planners/include/BipedalLocomotion/Planners/ConvexHullHelper.h
- src/Planners/src/ConvexHullHelper.cpp
- src/Planners/tests/CMakeLists.txt
- src/Planners/tests/ConvexHullHelperTest.cpp
> Use Eigen in ConvexHullHelper class

- CMakeLists.txt
- cmake/AddBipedalLocomotionLibrary.cmake
- cmake/AddBipedalLocomotionUnitTest.cmake
- cmake/BipedalLocomotionFrameworkFindDependencies.cmake
- src/ContactModels/CMakeLists.txt
- src/ContactModels/tests/CMakeLists.txt
- src/Estimators/CMakeLists.txt
- src/Estimators/tests/CMakeLists.txt
- src/GenericContainer/CMakeLists.txt
- src/GenericContainer/include/BipedalLocomotion/GenericContainer/TemplateHelpers.h
- src/GenericContainer/include/BipedalLocomotion/GenericContainer/Vector.h
- src/GenericContainer/tests/GenericContainerTest.cpp
- src/Planners/CMakeLists.txt
- src/Planners/tests/CMakeLists.txt
- src/System/CMakeLists.txt
- src/System/tests/CMakeLists.txt
Doing my part toward #63 I also removed the options ``DEPENDS_ON_EIGEN_PRIVATE`` and ``DEPENDS_ON_EIGEN_PUBLIC`` in favor of the using the corresponding target in the correct link lists.
> Add toEigen in generic vector

- .github/workflows/ci.yml
CI workflow is failing because of YCM https://github.com/dic-iit/bipedal-locomotion-framework/actions
See https://github.com/robotology/whole-body-estimators/pull/83
> [workflows] Update YCM tag in ci.yml

- cmake/AddBipedalLocomotionLibrary.cmake
- cmake/AddBipedalLocomotionUnitTest.cmake
See https://github.com/dic-iit/bipedal-locomotion-framework/pull/85#issuecomment-686605967
> Add USE_MATH_DEFINES for tests and library compile definitions

- .github/workflows/ci.yml
> Add the Debug compilation in GitHub Action

- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
This fixes the point 2 of #121 
I tested with the `YarpDevice` implemented by @prashanthr05
> Make the `joints_list` parameter as optional in the YarpSensorBridge

- src/Planners/src/TimeVaryingDCMPlanner.cpp
`Casadi::Map` is a feature implemented in casadi that allows improving the performances of the code while computing the system dynamics. 
Probably we can also increase the performances by calling the map as 
```cpp
auto trajectory = this->optiFunctions.dcmDynamics.map(horizonSampling, "thread", 8);
```
instead of
https://github.com/dic-iit/bipedal-locomotion-framework/blob/3b99825b4fdb4c9d352b1d2d27e35ccee2a59465/src/Planners/src/TimeVaryingDCMPlanner.cpp#L231
> Use Casadi::Map function to compute the system dynamics in the Time varying DCM planner

- .github/workflows/ci.yml
- src/Planners/CMakeLists.txt
- src/Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
- src/Planners/src/SwingFootPlanner.cpp
- src/Planners/tests/CMakeLists.txt
- src/Planners/tests/SwingFootPlannerTest.cpp
~~**Disclaimer: this PR includes also the modification implemented in #83 and #84. The commits introduced by this PR are:https://github.com/dic-iit/bipedal-locomotion-framework/commit/bea075317d89216dba02e050afcddd279aa2a6ca https://github.com/dic-iit/bipedal-locomotion-framework/commit/0f52a74e6f7f9c107fe460a327738e376027fb76 https://github.com/dic-iit/bipedal-locomotion-framework/commit/17db65be1c8109a892a18f1cb8756e37b96b2e8a**~~
This PR introduces the `SwingFootPlanner` class, the class uses the QuinticSpline class implemented in #83 to plan the foot position and the SO(3) planner #84 to generate the orientation of the foot.
The velocity and acceleration generated by the planner are written in mixed representation. 
This PR is ready to be reviewed ~~however I will keep in in draft …
> Implement the swing foot trajectory planner

- src/Planners/include/BipedalLocomotion/Planners/SO3Planner.h
- src/Planners/include/BipedalLocomotion/Planners/TimeVaryingDCMPlanner.h
This PR fixes the Doxygen documentation in the Planners library
> Fix doxygen documentation in the Planners library

- .github/workflows/ci.yml
Please check https://github.com/dic-iit/bipedal-locomotion-framework/pull/134#issuecomment-729258898
> Fix the Debug compilation in GitHub CI

- devices/FloatingBaseEstimatorDevice/CMakeLists.txt
> Fix Floating base estimation device CMakeLists.txt

- cmake/AddBipedalLocomotionYARPDevice.cmake
- devices/FloatingBaseEstimatorDevice/CMakeLists.txt
Replace manually written ini files with YARP dynamic plugin ini installation feature.
> devices: Allow dynamic installation of plugin ini files

- .github/workflows/ci.yml
Adds workaround for macOS issues listed here actions/virtual-environments#2322 and here https://github.com/actions/virtual-environments/issues/2391
> Fix automated builds macOS

- cmake/BipedalLocomotionFrameworkFindDependencies.cmake
- utilities/joint-trajectory-player/CMakeLists.txt
> Add FRAMEWORK_COMPILE_JointTrajectoryPlayer cmake option

- utilities/joint-trajectory-player/src/Module.cpp
> Remove Useless double initialization of the robotControl interface in joint-trajectory-player

- .github/workflows/ci.yml
Obviously if there is a failure we will not be 100% sure of what caused it, but we are like the [Steve McQueen](https://en.wikipedia.org/wiki/Steve_McQueen) of CI and so we like to live like this.
> CI: Refresh dependencies versions 

- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
Fixes https://github.com/dic-iit/bipedal-locomotion-framework/issues/188
> [YarpSensorBridge] fix check for NaN

- utilities/joint-trajectory-player/include/BipedalLocomotion/JointTrajectoryPlayer/Module.h
- utilities/joint-trajectory-player/src/Module.cpp
The PR implements https://github.com/dic-iit/element_torque-control-via-current/issues/171.
> Add joint velocities and motor currents logging in `joint-trajectory-player`

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
> Fix missing implementation of `YarpSensorBridge::getFailedSensorReads()`.

- CHANGELOG.md
- src/System/CMakeLists.txt
- src/System/include/BipedalLocomotion/System/FloatingBaseSystemDynamics.h
- src/System/src/FloatingBaseSystemDynamics.cpp
- utilities/mas-imu-test/CMakeLists.txt
- utilities/mas-imu-test/scripts/plotResults.m
- utilities/mas-imu-test/src/MasImuTest.cpp
> Substitute 9.81 with BipedalLocomotion::Math::StandardAccelerationOfGravitation

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
- src/IK/src/SE3Task.cpp
- src/IK/tests/SE3TaskTest.cpp
- src/TSID/src/SE3Task.cpp
- src/TSID/tests/SE3TaskTest.cpp
This fixes #235.
@traversaro while merging this PR we should update the version of installed manif in superbuild and in conda.
We may probably ask to add a tag in manif
> Update IK and TSID to the latest manif version

- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/System/CMakeLists.txt
- bindings/python/System/include/BipedalLocomotion/bindings/System/Module.h
- bindings/python/System/include/BipedalLocomotion/bindings/System/VariablesHandler.h
- bindings/python/System/src/Module.cpp
- bindings/python/System/src/VariablesHandler.cpp
- bindings/python/System/tests/test_variables_handler.py
- bindings/python/bipedal_locomotion_framework.cpp.in
- src/System/include/BipedalLocomotion/System/VariablesHandler.h
- src/System/src/VariablesHandler.cpp
This is required to port the IK in python 
cc @paolo-viceconte
> Implement python bindings for VariablesHandler class

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
- CMakeLists.txt
- bindings/python/CMakeLists.txt
- cmake/BipedalLocomotionDependencyClassifier.cmake
- cmake/BipedalLocomotionFrameworkDependencies.cmake
This should avoid problems like #246
> Ask for a specific version for the dependencies 

- .github/workflows/ci.yml
- bindings/python/all.py
- cmake/AddBipedalLocomotionYARPDevice.cmake
- devices/FloatingBaseEstimatorDevice/scope/sim/base_pose_scope.xml
- devices/FloatingBaseEstimatorDevice/scope/sim/base_velocity_scope.xml
- devices/FloatingBaseEstimatorDevice/scope/sim/contact_normal_scope.xml
- devices/FloatingBaseEstimatorDevice/scope/sim/waist_imu.xml
- devices/examples/ROSPublisherTestDevice/README.md
- devices/examples/ROSPublisherTestDevice/app/robots/iCubGazeboV2_5/publisher/ros-publisher.xml
- devices/examples/ROSPublisherTestDevice/include/BipedalLocomotion/ROSPublisherTestDevice.h
- devices/examples/ROSPublisherTestDevice/src/ROSPublisherTestDevice.cpp
- src/Contacts/CMakeLists.txt
- src/Contacts/include/BipedalLocomotion/ContactDetectors/ContactDetector.h
- src/Contacts/include/BipedalLocomotion/ContactDetectors/SchmittTriggerDetector.h
- src/Contacts/src/ContactDetector.cpp
- src/Contacts/src/SchmittTriggerDetector.cpp
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimatorIO.h
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/LeggedOdometry.h
- src/Estimators/src/FloatingBaseEstimator.cpp
- src/Estimators/src/LeggedOdometry.cpp
- src/Perception/include/BipedalLocomotion/Perception/Capture/RealSense.h
- src/Perception/include/BipedalLocomotion/Perception/Features/ArucoDetector.h
- src/Perception/src/RealSense.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ICameraBridge.h
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/IPointCloudBridge.h
- src/YarpUtilities/include/BipedalLocomotion/YarpUtilities/RosPublisher.h
- src/YarpUtilities/src/RosPublisher.cpp
- utilities/mas-imu-test/README.md
- utilities/realsense-test/include/BipedalLocomotion/RealSenseTest/Module.h
Trailing Whitespaces are really annoying this PR add a GitHub action that can be used to find them 
Here: https://github.com/dic-iit/bipedal-locomotion-framework/runs/2241283783#step:3:224 an example of failing action 
~~https://github.com/marketplace/actions/find-trailing-whitespace~~ Not used because of https://github.com/harupy/find-trailing-whitespace/issues/13
> Add Find Trailing Whitespace GitHub action

- src/System/tests/AdvanceableRunnerTest.cpp
This fixes https://github.com/dic-iit/bipedal-locomotion-framework/pull/274/checks?check_run_id=2317717051
> Bugfix in AdvanceableRunnerTest.cpp

- CHANGELOG.md
- src/System/CMakeLists.txt
- src/System/include/BipedalLocomotion/System/QuitHandler.h
- src/System/src/QuitHandler.cpp
The original implementation can be found here:   https://github.com/robotology/idyntree-yarp-tools/blob/main/src/lib/Utilities/Utilities.h
> Implement handleQuitSignals() function in System component

- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/LeggedOdometry.h
- src/Estimators/src/LeggedOdometry.cpp
- Added a getter method
- Improved changeFixedFrame and resetEstimator calls
> Improve LeggedOdometry implementation

- CHANGELOG.md
- src/ParametersHandler/YarpImplementation/CMakeLists.txt
- src/ParametersHandler/YarpImplementation/include/BipedalLocomotion/ParametersHandler/YarpImplementation.h
- src/ParametersHandler/YarpImplementation/src/YarpImplementation.cpp
- src/ParametersHandler/include/BipedalLocomotion/ParametersHandler/IParametersHandler.h
- src/ParametersHandler/include/BipedalLocomotion/ParametersHandler/StdImplementation.h
- src/ParametersHandler/src/StdImplementation.cpp
- src/ParametersHandler/tests/ParametersHandlerTest.cpp
- src/ParametersHandler/tests/ParametersHandlerYarpTest.cpp
- src/YarpUtilities/CMakeLists.txt
- src/YarpUtilities/include/BipedalLocomotion/YarpUtilities/Helper.tpp
- src/YarpUtilities/src/Helper.cpp
Follow up of https://github.com/dic-iit/bipedal-locomotion-framework/issues/285#issuecomment-826923766
> Implement clone method in ParametersHandler classes

- CHANGELOG.md
- src/TSID/CMakeLists.txt
- src/TSID/include/BipedalLocomotion/TSID/CoMTask.h
- src/TSID/src/CoMTask.cpp
- src/TSID/tests/CMakeLists.txt
- src/TSID/tests/CoMTaskTest.cpp
As written in the title the PR introduces the CoMTask in tsid.
The PR implements also a test.
> Implement `CoMTask` in TSID

- .github/workflows/ci.yml
> Remove workaround in macOS CI

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/ParametersHandler/CMakeLists.txt
- src/ParametersHandler/TomlImplementation/CMakeLists.txt
- src/ParametersHandler/TomlImplementation/include/BipedalLocomotion/ParametersHandler/TomlImplementation.h
- src/ParametersHandler/TomlImplementation/include/BipedalLocomotion/ParametersHandler/TomlImplementation.tpp
- src/ParametersHandler/TomlImplementation/src/TomlImplementation.cpp
- src/ParametersHandler/tests/CMakeLists.txt
- src/ParametersHandler/tests/ParametersHandlerTomlTest.cpp
The PR introduces the `toml` implementation of `IParametersHandler`.  The code uses https://github.com/marzer/tomlplusplus
TODO
> Add the support to toml in the parameters handler

- CHANGELOG.md
- cmake/AddBipedalLocomotionYARPDevice.cmake
- devices/FloatingBaseEstimatorDevice/include/BipedalLocomotion/FloatingBaseEstimatorDevice.h
- devices/examples/FTIMULoggerDevice/include/BipedalLocomotion/FTIMULoggerDevice.h
- devices/examples/ROSPublisherTestDevice/include/BipedalLocomotion/ROSPublisherTestDevice.h
This fixes #335 
I followed this tutorial: http://www.yarp.it/git-master/add_a_plugin.html
> Various fixes for the yarp devices

- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/ft-imu-logger.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/interface/all_joints_mc.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/interface/root_imu.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/launch-ft-imu-logger.xml
- devices/examples/FTIMULoggerDevice/include/BipedalLocomotion/FTIMULoggerDevice.h
- devices/examples/FTIMULoggerDevice/src/FTIMULoggerDevice.cpp
> Add the possibility to log the joint state and the base imu in FTIMULoggerDevice

- .github/workflows/ci.yml
> Invalidate the cache in GitHub CI

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
As suggested by @S-Dafarra in https://github.com/dic-iit/bipedal-locomotion-framework/pull/364#issuecomment-878394900
> Rename macOS-latest in macos-latest in GitHub CI

- CHANGELOG.md
- src/IK/include/BipedalLocomotion/IK/CoMTask.h
- src/IK/src/CoMTask.cpp
- src/IK/tests/CoMTaskTest.cpp
The same as #356 but for the CoM.
Blocked by #356 
cc @paolo-viceconte
> Add the possibility to control a subset of coordinates in `IK::CoMTask`

- CHANGELOG.md
- src/TSID/CMakeLists.txt
- src/TSID/include/BipedalLocomotion/TSID/QPFixedBaseTSID.h
- src/TSID/include/BipedalLocomotion/TSID/QPTSID.h
- src/TSID/include/BipedalLocomotion/TSID/TaskSpaceInverseDynamics.h
- src/TSID/src/QPFixedBaseTSID.cpp
- src/TSID/src/QPTSID.cpp
This PR concludes the refactoring of TSID. I designed the `QPTSID` class that implements a  Task base inverse dynamics algorithm for a floating base system.
The `QPFixedBaseTSID` now inherits from `QPTSID` since a fixed base robot can be seen as a floating base robot with a hard constraint on the robot base pose.
No actions are required by the users of `QPFixedBaseTSID` for the migration (@isorrentino)
> Implement Floating base TSID

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
> YarpSensorBridge: add checks in control board getter methods

- .github/workflows/ci.yml
Hopefully, this will fix https://github.com/dic-iit/bipedal-locomotion-framework/runs/3124956581?check_suite_focus=true
> Update vcpkg_robotology_TAG in CI.yml

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
And remove them from homebrew.
> Add PCL and OpenCV to conda dependencies in conda-based CI

- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/TextLogging/CMakeLists.txt
- bindings/python/TextLogging/include/BipedalLocomotion/bindings/TextLogging/Module.h
- bindings/python/TextLogging/include/BipedalLocomotion/bindings/TextLogging/TextLogging.h
- bindings/python/TextLogging/src/Module.cpp
- bindings/python/TextLogging/src/TextLogging.cpp
- bindings/python/bipedal_locomotion_framework.cpp.in
- src/TextLogging/include/BipedalLocomotion/TextLogging/Logger.h
- src/TextLogging/src/Logger.cpp
I exposed all the spdlogs levels to a new blf enum at the C++ level. Then, the blf enum is exposed to Python.
> Allow changing the log verbosity

- .github/workflows/ci.yml
This should fix https://github.com/dic-iit/bipedal-locomotion-framework/issues/389
This is the solution: https://github.com/IntelRealSense/librealsense/issues/9607#issuecomment-896789179
> Fix realsense installation in Ubuntu CI

- CHANGELOG.md
- src/System/include/BipedalLocomotion/System/AdvanceableRunner.h
Thanks to `AdvanceableRunner::isRunning()`, it is possible to check if the thread created by the class is still running
> Implement AdvanceableRunner::isRunning() method

- .github/workflows/ci.yml
> Bump iDynTree version to 3.1.0 in Github CI

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
This will clarify the minimum required version of spdlog
> Set the required spdlog version in the cmake file

- .ci/generate-labeler-file.py
- .github/labeler.yml
- .github/workflows/labeler.yml
- .github/workflows/update-labeler-file.yml
`labeler` is an action that automatically label new pull requests based on the paths of files being changed.
This PR introduces:
- `.github/workflows/labeler.yml` and `.github/labeler.yml` are two files required by the action
- `.ci/generate-labeler-file.py` a python script that automatically generates `.github/labeler.yml` file
- `.github/workflows/update-labeler-file.yml` is an action that automatically checks if a new component has been added and it opens a PR to update the `.github/labeler.yml` file` file
> Add labeler workflow

- CHANGELOG.md
- bindings/python/TSID/CMakeLists.txt
- bindings/python/TSID/include/BipedalLocomotion/bindings/TSID/AngularMomentumTask.h
- bindings/python/TSID/src/AngularMomentumTask.cpp
- bindings/python/TSID/src/Module.cpp
- src/TSID/CMakeLists.txt
- src/TSID/include/BipedalLocomotion/TSID/AngularMomentumTask.h
- src/TSID/src/AngularMomentumTask.cpp
- src/TSID/tests/AngularMomentumTaskTest.cpp
- src/TSID/tests/CMakeLists.txt
> Implement the AngularMomentumTask in TSID component

- CHANGELOG.md
- bindings/python/utils.py
Implement an utility python function that can be used to create an IK. 
Relative PR: https://github.com/ami-iit/bipedal-locomotion-framework/pull/433
> Implement `create_ik` python function

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
> Add the possibility to enable/disable the joints and motors state logging in the YarpRobotLoggerDevice

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
This fixes https://github.com/ami-iit/bipedal-locomotion-framework/issues/455.
> Fix - Add a new method to properly read the analog FT sensors

- CHANGELOG.md
- CMakeLists.txt
Tested with https://github.com/nlohmann/cmake_min_version
> Fix minimum cmake required version

- CHANGELOG.md
- src/TSID/src/QPTSID.cpp
> Fix the population of the jointAccelerations and baseAcceleration variables in QPTSID

- CHANGELOG.md
- src/TSID/src/QPTSID.cpp
> Fix the retrieved joint torques in QPTSID class

- CHANGELOG.md
- bindings/python/IK/src/IntegrationBasedIK.cpp
- bindings/python/System/CMakeLists.txt
- bindings/python/System/include/BipedalLocomotion/bindings/System/ILinearTaskSolver.h
- bindings/python/System/src/LinearTask.cpp
- bindings/python/TSID/src/TaskSpaceInverseDynamics.cpp
- src/IK/include/BipedalLocomotion/IK/QPInverseKinematics.h
- src/IK/src/QPInverseKinematics.cpp
- src/System/include/BipedalLocomotion/System/ILinearTaskSolver.h
- src/System/include/BipedalLocomotion/System/LinearTask.h
- src/System/src/LinearTask.cpp
- src/TSID/include/BipedalLocomotion/TSID/QPTSID.h
- src/TSID/src/QPTSID.cpp
> Implement the possibility to get the residual in LinearTask

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
> Return the motorPositions and motorVelecities in rad and not in deg

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
From here: https://blog.fleetdm.com/4-tips-for-github-actions-usability-2-debugging-4c0c920adfde
> Avoid duplicate runs with push and pull_request in the github action

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- devices/YarpRobotLoggerDevice/CMakeLists.txt
- devices/YarpRobotLoggerDevice/app/robots/iCubGazeboV3/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova02/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova04/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
You can try to use it. It depends on https://github.com/robotology/yarp-telemetry/pull/146
This closes #189 
cc @isorrentino @S-Dafarra @traversaro
> Use telemetry in YarpLoggerDevice

- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
This PR depends on  https://github.com/ami-iit/bipedal-locomotion-framework/pull/492
> Add logging of joint and motor accelerations in YarpRobotLoggerDevice

- .github/workflows/gh-pages.yml
Thanks to https://github.com/mosra/m.css/pull/189
> Use official m.css to build the documentation

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- devices/CMakeLists.txt
- devices/VectorsCollectionWrapper/CMakeLists.txt
- devices/VectorsCollectionWrapper/README.md
- devices/VectorsCollectionWrapper/app/CMakeLists.txt
- devices/VectorsCollectionWrapper/app/robots/iCubGazeboV3/launch-vectors-collection-wrapper.xml
- devices/VectorsCollectionWrapper/app/robots/iCubGazeboV3/vectors-collection-wrapper.xml
- devices/VectorsCollectionWrapper/include/BipedalLocomotion/VectorsCollectionWrapper.h
- devices/VectorsCollectionWrapper/src/VectorsCollectionWrapper.cpp
> Add VectorsCollectionWrapper device

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/interface/right_upper_leg_ft_client.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/interface/right_upper_leg_wrench_client.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/launch-yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
This PR gives the possibility to log info about the new FT mounted on the right upper leg of iCub3.
> Add reading of right upper leg ft and associated cartesian wrench

- CHANGELOG.md
- src/Planners/include/BipedalLocomotion/Planners/CubicSpline.h
- src/Planners/src/CubicSpline.cpp
- src/Planners/tests/SplineTest.cpp
In https://github.com/ami-iit/bipedal-locomotion-framework/pull/344 I didn't add a test for the CubicSpline.
> Add the test for the Cubic spline 

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/interface/ft_clients.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/interface/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ISensorBridge.h
cc @isorrentino @GiulioRomualdi
> Add temperature sensors to YarpSensorBridge and YarpRobotLogger, migrate to MAS interfaces for FT Sensors

- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/ContinuousDynamicalSystem/CMakeLists.txt
- bindings/python/ContinuousDynamicalSystem/include/BipedalLocomotion/bindings/ContinuousDynamicalSystem/DynamicalSystem.h
- bindings/python/ContinuousDynamicalSystem/include/BipedalLocomotion/bindings/ContinuousDynamicalSystem/FloatingBaseSystemKinematics.h
- bindings/python/ContinuousDynamicalSystem/include/BipedalLocomotion/bindings/ContinuousDynamicalSystem/Integrator.h
- bindings/python/ContinuousDynamicalSystem/include/BipedalLocomotion/bindings/ContinuousDynamicalSystem/LinearTimeInvariantSystem.h
- bindings/python/ContinuousDynamicalSystem/include/BipedalLocomotion/bindings/ContinuousDynamicalSystem/Module.h
- bindings/python/ContinuousDynamicalSystem/src/FloatingBaseSystemKinematics.cpp
- bindings/python/ContinuousDynamicalSystem/src/LinearTimeInvariantSystem.cpp
- bindings/python/ContinuousDynamicalSystem/src/Module.cpp
- bindings/python/ContinuousDynamicalSystem/tests/test_floating_base_system_kinematics.py
- bindings/python/ContinuousDynamicalSystem/tests/test_linear_system.py
- bindings/python/bipedal_locomotion_framework.cpp.in
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/FixedStepIntegrator.h
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/ForwardEuler.h
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/Integrator.h
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/impl/traits.h
Thanks to this PR it will be possible to use the integratos in the `ContinuousDynamicalSystem` along with the DynamicalSystem. 
For the time being I wrote the bindings only for the `LinearTimeVariantSystem` and the `FloatingBaseKinematics`. Here same examples
```python
import bipedal_locomotion_framework.bindings as blf                                                      
import numpy as np
A = np.array([[0,1],[-2,-2]])
B = np.array([0,2])
u = np.array([1])
x0 = np.array([0, 0])
dt = 0.0001
system = blf.continuous_dynamical_system.LinearTimeInvariantSystem()
assert system.set_system_matrices(A,B)
assert system.set_state((x0,)) ## if you want to be more pythonic you can use system.state = x0,
assert system.set_control_input((u,))
integrator = …
```
> Implement the bindings for the ContinuousDynamicalSystem component

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
> Fix compatibility of YarpRobotLoggerDevice with new version of matiocpp

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionDependencyClassifier.cmake
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- devices/YarpRobotLoggerDevice/CMakeLists.txt
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/interface/webcams.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpTextLoggingUtilities.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- devices/YarpRobotLoggerDevice/src/YarpTextLoggingUtilities.cpp
- src/RobotInterface/YarpImplementation/src/YarpCameraBridge.cpp
> Add the possibility to log the YarpTextLogging in the YarpRobotLogger

- CHANGELOG.md
- bindings/python/ParametersHandler/tests/test_parameters_handler_yarp.py
- src/YarpUtilities/include/BipedalLocomotion/YarpUtilities/Helper.tpp
- src/YarpUtilities/tests/YarpUtilitiesTest.cpp
Moreover the PR removes also the macros
> Accept boolean as integer while getting an element from searchable in YarpUtilities

- CHANGELOG.md
- bindings/python/IK/src/SE3Task.cpp
- src/IK/include/BipedalLocomotion/IK/SE3Task.h
- src/IK/src/SE3Task.cpp
- src/IK/tests/SE3TaskTest.cpp
This closes https://github.com/ami-iit/bipedal-locomotion-framework/issues/360
---
Required to use IMU in the IK
> Add the possibility to set the exogenous feedback for the IK::SE3Task

- .github/CODEOWNERS
- README.md
> Add the maintainers 

- .github/workflows/ci.yml
Temporary workaround for actions/setup-python#577
> Workaround for python brew installation

- .github/workflows/ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
This will simplify https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/issues/14
> Ask for toml++ v3.0.1

- .github/workflows/gh-pages.yml
Similar to:
* https://github.com/ami-iit/bipedal-locomotion-framework/pull/593
* https://github.com/robotology/robotology-superbuild/pull/840
* https://github.com/robotology/robometry/pull/141
* https://github.com/robotology-playground/yarp-devices-ros2/pull/44
* https://github.com/gazebosim/gazebo-classic/pull/3287
>  Fix gh-pages CI

- .github/workflows/ci.yml
> Attempt to fix macOS CI

- src/IK/include/BipedalLocomotion/IK/QPFixedBaseInverseKinematics.h
- src/IK/include/BipedalLocomotion/IK/QPInverseKinematics.h
> Fix the documentation in the IK component

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/SubModel.h
- src/Estimators/src/SubModel.cpp
- src/Estimators/tests/RobotDynamicsEstimator/CMakeLists.txt
- src/Estimators/tests/RobotDynamicsEstimator/ConfigFolderPath.h.in
- src/Estimators/tests/RobotDynamicsEstimator/SubModelCreatorTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/model.ini
> Add functions to split a robot model into submodel objects

- CHANGELOG.md
- examples/InverseKinematics/config/ik.toml
- examples/InverseKinematics/inverse_kinematics.ipynb
As per title.
@LoreMoretti @traversaro
> Update the IK tutorial to use QPInverseKinematics::build

- examples/InverseKinematics/README.md
Thank https://github.com/conda-forge/staged-recipes/pull/22244,  `robot_description` is available also in `conda-forge`.
> Update InverseKinematics example README

- CHANGELOG.md
- src/TSID/include/BipedalLocomotion/TSID/QPTSID.h
> fix documentation for QPTSID.h

- CHANGELOG.md
- src/TSID/src/QPTSID.cpp
> Fix error message for contact wrench variable

- examples/InverseKinematics/inverse_kinematics.ipynb
> Update the inverse_kinematics example to be compliant the new version of ContinousDynamicalSystem

- .github/workflows/ci.yml
> Speed up the GitHub CI compilation by using all the cores of the GitHub runner

- .github/workflows/ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/TSID/src/AngularMomentumTask.cpp
- src/TSID/src/CoMTask.cpp
- src/TSID/src/SE3Task.cpp
- src/TSID/src/SO3Task.cpp
- src/TSID/tests/CoMTaskTest.cpp
- src/TSID/tests/SE3TaskTest.cpp
- src/TSID/tests/SO3TaskTest.cpp
As per the title, this PR makes the framework compatible with the latest version of lie-groups-controller
Fix https://github.com/robotology/robotology-superbuild/issues/1388
> Update the code to be compatible with LieGroupControllers v0.2.0

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
> Fix RobotDynamicsEstimator compilation dependencies

- .github/workflows/conda-forge-ci.yml
Workaround for https://github.com/ami-iit/bipedal-locomotion-framework/issues/674 .
> Add workaround for conda-forge manifpy and GCC 12 problem

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/UkfState.h
- src/Estimators/src/AccelerometerMeasurementDynamics.cpp
- src/Estimators/src/ConstantMeasurementModel.cpp
- src/Estimators/src/FrictionTorqueStateDynamics.cpp
- src/Estimators/src/GyroscopeMeasurementDynamics.cpp
- src/Estimators/src/JointVelocityStateDynamics.cpp
- src/Estimators/src/UkfState.cpp
- src/Estimators/tests/RobotDynamicsEstimator/CMakeLists.txt
- src/Estimators/tests/RobotDynamicsEstimator/ConfigFolderPath.h.in
- src/Estimators/tests/RobotDynamicsEstimator/UkfStateTest.cpp
Add UkfState class representing the process model of the estimator.
> Add UkfState class

- src/ML/include/BipedalLocomotion/ML/MANNTrajectoryGenerator.h
- src/ML/src/MANNTrajectoryGenerator.cpp
- src/ML/tests/MANNTrajectoryGeneratorTest.cpp
As per title. This makes the connection with MPC easier.
> Expose the CoM trajectory and the angular momentum trajectory as std::vector in MANNTrajectoryGenerator

- src/ReducedModelControllers/include/BipedalLocomotion/ReducedModelControllers/CentroidalMPC.h
With this fix the documentation will be correctly generated
> Fix CentroidalMPC documentation

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
This PR fixes https://github.com/ami-iit/bipedal-locomotion-framework/issues/638
⚠️ Before merging the PR I would like to test it on the robot.
> Make the YarpSensorBridge compatible with MAS that use the same name between gyro ac magn and orientation

- CHANGELOG.md
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/CentroidalDynamics.h
- src/ContinuousDynamicalSystem/src/CentroidalDynamics.cpp
- src/ReducedModelControllers/tests/CentroidalMPCTest.cpp
As per the title, this PR allows to set an external wrench instead of a pure force in the CentroidalDynamics
> Give the possibility to set an external wrench in the CentroidalDynamics

- CHANGELOG.md
- src/TSID/src/JointTrackingTask.cpp
- src/TSID/tests/JointTrackingTaskTest.cpp
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/718 .
> Fix handling of feedforward acceleration in `BipedalLocomotion::TSID::JointTrackingTask::setSetPoint`

- CHANGELOG.md
- src/IK/src/CoMTask.cpp
- src/TSID/include/BipedalLocomotion/TSID/CoMTask.h
- src/TSID/src/CoMTask.cpp
- src/TSID/tests/CoMTaskTest.cpp
I ported the change https://github.com/ami-iit/bipedal-locomotion-framework/pull/357 from IK to TSID.
fyi @xela-95 @Gio-DS @diegoferigo @LoreMoretti
> Add the possibility to control a subset of coordinates in TSID::CoMTask

- bindings/python/Contacts/src/Contacts.cpp
Bug introduced in https://github.com/ami-iit/bipedal-locomotion-framework/pull/750
> Fix inequality operator in PlannedContact bindings

- CHANGELOG.md
- src/TSID/include/BipedalLocomotion/TSID/JointDynamicsTask.h
- src/TSID/src/JointDynamicsTask.cpp
> added mass matrix regularziation in TSID joint dynamic task

- CHANGELOG.md
- src/TextLogging/include/BipedalLocomotion/TextLogging/Logger.h
Inspired from https://stackoverflow.com/a/73755864
> Fixed compilation on Windows of fmt formatter for Eigen types.

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/all_joints_mc.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/imu_clients.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/webcams.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
This has been tested on the robot
> [ergoCubSN000] Update the YarpRobotLogger configuration file to be compliant with robots-configuration v2.5.2

- CHANGELOG.md
- bindings/python/Contacts/src/Contacts.cpp
- src/Contacts/include/BipedalLocomotion/Contacts/ContactList.h
- src/Contacts/src/ContactList.cpp
- src/Contacts/tests/Contacts/ContactListTest.cpp
This PR adds `ContactList::getNextContact` and `ContactList::getActiveContact` functions that are useful to get the current active contact and the next active contact in a contact list
> Implement ContactList::getNextContact and ContactList::getActiveContact in Contact component

- .github/workflows/conda-forge-ci.yml
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/780 .
> Install all common mamba dependencies in a single command

- CHANGELOG.md
- utilities/joint-position-tracking/script/blf_joint_position_tracking_plot_dataset.py
This PR adds these changes:
- Plots the error and saves the figure.
- Removes the lines related to the latex in the Python script. 
cc @GiulioRomualdi
> Add plot of the joint position error

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/blf-yarp-robot-logger-interfaces/imu_clients.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/blf-yarp-robot-logger-interfaces/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/yarp-robot-logger.xml
~⚠️ Blocked by https://github.com/ami-iit/bipedal-locomotion-framework/pull/790~
> 🤖 [ergoCubSN001] Update YarpRobotLoggerDevice configuration file to exclude the head-imu and include the arms FTs

- CHANGELOG.md
- src/ContinuousDynamicalSystem/src/MultiStateWeightProvider.cpp
- src/IK/src/JointLimitsTask.cpp
- src/IK/src/JointTrackingTask.cpp
- src/TSID/src/JointTrackingTask.cpp
This should fix the issue we experienced on the robot two days ago.
> Check that the size the gains and weights vectors are correct

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/blf-yarp-robot-logger-interfaces/imu_clients.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/blf-yarp-robot-logger-interfaces/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/launch-yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/yarp-robot-logger.xml
This PR adds the logging of the feet IMU for `ergoCubGazeboV1_1`
The feet IMU has been added in https://github.com/icub-tech-iit/ergocub-software/pull/217
> 🤖 [ergoCubGazeboV1_1] Enable the logging of the feet FT IMU 

- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/blf-yarp-robot-logger-interfaces/all_joints_mc.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/yarp-robot-logger.xml
This also adds the torso pitch
> 🤖 [ergoCubGazeboV1_1] Fix logging configuration file

- .gitignore
- cmake/AddBipedalLocomotionYARPDevice.cmake
I also updated the ``gitignore`` to ignore Visual Studio files
> Fixed setting of target include directories for the yarp devices

- CHANGELOG.md
- bindings/python/TSID/CMakeLists.txt
- bindings/python/TSID/include/BipedalLocomotion/bindings/TSID/R3Task.h
- bindings/python/TSID/src/Module.cpp
- bindings/python/TSID/src/QPTSID.cpp
- bindings/python/TSID/src/R3Task.cpp
- bindings/python/TSID/src/TaskSpaceInverseDynamics.cpp
- bindings/python/utils.py
- src/TSID/CMakeLists.txt
- src/TSID/include/BipedalLocomotion/TSID/AngularMomentumTask.h
- src/TSID/include/BipedalLocomotion/TSID/BaseDynamicsTask.h
- src/TSID/include/BipedalLocomotion/TSID/CoMTask.h
- src/TSID/include/BipedalLocomotion/TSID/FeasibleContactWrenchTask.h
- src/TSID/include/BipedalLocomotion/TSID/JointDynamicsTask.h
- src/TSID/include/BipedalLocomotion/TSID/JointTrackingTask.h
- src/TSID/include/BipedalLocomotion/TSID/QPTSID.h
- src/TSID/include/BipedalLocomotion/TSID/R3Task.h
- src/TSID/include/BipedalLocomotion/TSID/SE3Task.h
- src/TSID/include/BipedalLocomotion/TSID/SO3Task.h
- src/TSID/include/BipedalLocomotion/TSID/TSIDLinearTask.h
- src/TSID/include/BipedalLocomotion/TSID/TaskSpaceInverseDynamics.h
- src/TSID/src/QPTSID.cpp
- src/TSID/src/R3Task.cpp
- src/TSID/src/TSIDLinearTask.cpp
- src/TSID/src/TaskSpaceInverseDynamics.cpp
- src/TSID/tests/CMakeLists.txt
- src/TSID/tests/R3TaskTest.cpp
As per the title, moreover, the PR adds also the R3Task for TSID
> Add the possibility to programmatically build a TSID problem from config file

- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/blf-yarp-robot-logger-interfaces/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/blf-yarp-robot-logger-interfaces/webcams.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/yarp-robot-logger.xml
This PR fixes the config files of the ergoCubSN001 after the robot update
> Fix the ergoCubSN001 logging 

- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
This fix the regression https://github.com/ami-iit/bipedal-locomotion-framework/issues/846 introduced in  ami-iit/bipedal-locomotion-framework@4e9a2bac07d99d6c648a1206d7b6a33c300557a4
> Fix signal logging in YarpRobotLoggerDevice

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN002/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
cc @GiulioRomualdi @carloscp3009 @giotherobot
> Added missing logData for vectorSignals and TextLogging

- CHANGELOG.md
- bindings/python/IK/CMakeLists.txt
- bindings/python/IK/include/BipedalLocomotion/bindings/IK/JointVelocityLimitsTask.h
- bindings/python/IK/src/JointVelocityLimitsTask.cpp
- bindings/python/IK/src/Module.cpp
- bindings/python/IK/tests/test_QP_inverse_kinematics.py
- src/IK/CMakeLists.txt
- src/IK/include/BipedalLocomotion/IK/JointVelocityLimitsTask.h
- src/IK/src/JointVelocityLimitsTask.cpp
- src/IK/tests/CMakeLists.txt
- src/IK/tests/JointVelocityLimitsTaskTest.cpp
With this PR I add a task in the IK to set the joint velocity limits.
CC @Gianlucamilani @claudia-lat
> Add joint velocity limits task

- CHANGELOG.md
- src/ReducedModelControllers/src/CentroidalMPC.cpp
> Fix the normal force limit constraint in the CentroidalMPC

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ISensorBridge.h
This fixes https://github.com/ami-iit/bipedal-locomotion-framework/issues/943
cc @FabioBergonti
> Add joint type handling to YarpSensorBridge in case of prismatic and revolute joints

- CHANGELOG.md
- devices/JointTorqueControlDevice/src/JointTorqueControlDevice.cpp
As per title. 
Related comment: https://github.com/ami-iit/element_sensorless-torque-control/issues/232#issuecomment-2838572109
cc @isorrentino @GiulioRomualdi
> Fix logic for friction torque saturation

- bindings/python/JointLevelControllers/src/EMAWithLimits.cpp
- src/JointLevelControllers/include/BipedalLocomotion/JointLevelControllers/EMAWithLimits.h
- src/JointLevelControllers/src/EMAWithLimits.cpp
- src/JointLevelControllers/tests/EMAWithLimitsTest.cpp
This pull request updates the `EMAWithLimits` reset by setting the initial value
> Reset EMAWithLimits with the current position
