ami-iit/bipedal-locomotion-framework

- README.md
- cmake/BipedalLocomotionControllersFindDependencies.cmake
Since the `iDynTree 1.0.0` has been [released](https://github.com/robotology/idyntree/releases/tag/v1.0.0) 
The required minimum version of iDynTree has been updated. This is required by `COMPATIBILITY SameMajorVersion` 
```cmake 
install_basic_package_files(iDynTree VARS_PREFIX ${VARS_PREFIX}
VERSION ${${VARS_PREFIX}_VERSION}
COMPATIBILITY SameMajorVersion
TARGETS_PROPERTY ${VARS_PREFIX}_TARGETS
NO_CHECK_REQUIRED_COMPONENTS_MACRO
ENABLE_COMPATIBILITY_VARS
DEPENDENCIES ${_IDYNTREE_EXPORTED_DEPENDENCIES})
```
In the main iDynTree [`CMakeLists.txt`](https://github.com/robotology/idyntree/blob/516713a5ec71427ee04746243dbc504ead66862f/CMakeLists.txt#L72-L78) file
> Update the iDynTree required version

- README.md
- cmake/BipedalLocomotionControllersFindDependencies.cmake
Since https://github.com/robotology/idyntree/pull/629 fixed the problem, we can revert dic-iit/bipedal-locomotion-controllers#8
> Revert "Update the iDynTree required version"

- src/YarpUtilities/include/BipedalLocomotionControllers/YarpUtilities/Helper.h
- src/YarpUtilities/include/BipedalLocomotionControllers/YarpUtilities/Helper.tpp
This PR allows calling `getVectorFromSearchable()` with fix sized vectors (i.e. `iDynTree::VectorFixSize`) 
In details, I:
- introduced `is_resizable` struct: usefull gor checking if a class of type `T` has the method `T::resize()`
- used `if constexpr ()` for checking at compile time if the resize can be performed. If the size is not compatible the method returns an error. 
Fixes #11
> Add the possibility to use YarpUtilities::getVectorFromSearchable() with fix sized vectors

- CMakeLists.txt
- src/YarpUtilities/CMakeLists.txt
- src/YarpUtilities/include/BipedalLocomotionControllers/YarpUtilities/Helper.tpp
- src/YarpUtilities/src/Helper.cpp
Fix the problem presented in  #14. Furthermore, in the main `CMakeLists.txt` I added 
```cmake
option(BUILD_SHARED_LIBS "Build libraries as shared as opposed to static" ON)
```
See [here](https://github.com/robotology/how-to-export-cpp-library/blob/master/CMakeLists.txt#L98) and [here](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html) for further details
> Add the possibility to compile the library as static and shared

- src/ParametersHandler/YarpImplementation/include/BipedalLocomotionControllers/ParametersHandler/YarpImplementation.h
- src/ParametersHandler/YarpImplementation/src/YarpImplementation.cpp
- src/ParametersHandler/include/BipedalLocomotionControllers/ParametersHandler/IParametersHandler.h
- src/ParametersHandler/include/BipedalLocomotionControllers/ParametersHandler/IParametersHandler.tpp
- src/ParametersHandler/tests/ParametersHandlerTest.cpp
- src/ParametersHandler/tests/ParametersHandlerYarpTest.cpp
The `isEmpty()` method could be really useful to check if the handler contains any parameters.
> Implement isEmpty() method in ParameterHandler library

- src/ParametersHandler/YarpImplementation/include/BipedalLocomotionControllers/ParametersHandler/YarpImplementation.h
- src/ParametersHandler/YarpImplementation/include/BipedalLocomotionControllers/ParametersHandler/YarpImplementation.tpp
- src/ParametersHandler/YarpImplementation/src/YarpImplementation.cpp
- src/ParametersHandler/include/BipedalLocomotionControllers/ParametersHandler/IParametersHandler.h
- src/ParametersHandler/include/BipedalLocomotionControllers/ParametersHandler/IParametersHandler.tpp
- src/ParametersHandler/tests/CMakeLists.txt
- src/ParametersHandler/tests/ConfigFolderPath.h.in
- src/ParametersHandler/tests/ParametersHandlerTest.cpp
- src/ParametersHandler/tests/ParametersHandlerYarpTest.cpp
- src/ParametersHandler/tests/config.ini
Initially, the refactoring started adding utility functions like ``make_unique``, or the possibility to set the handler from another generic object. Then, @GiulioRomualdi realized (https://github.com/dic-iit/bipedal-locomotion-controllers/issues/20) there were issues with the usage of ``unique_ptr`` which caused other issues about ownership and how the groups were handled.
One possibility to fix these issues was to return a ``weak_ptr`` to the group. In this way, it is clear who owns the group and ideally, any parameter modified in the group would have appeared also in the original handler. But then the issue was that the original handler should have held a shared pointer to group. Then, I decided that the handler should also contain a map where I associate the group name to a shared …
> Small refactoring of ParametersHandler

- src/ParametersHandler/YarpImplementation/src/YarpImplementation.cpp
- src/ParametersHandler/tests/ParametersHandlerYarpTest.cpp
- src/ParametersHandler/tests/config.ini
Added test cases.
#18 was broken. Whoops :sweat_smile:
> Fix missing fields when parsing config files

- .github/workflows/ci.yml
This PR adds support for use GitHub Actions cache (see https://github.com/actions/cache) for storing the dependency build from source (YCM, YARP and ICUB).
Furthermore:
- Switch to use predefined commits for vcpkg, YCM, YARP iDynTree and Catch2 used for testing
- Switch to use pre-compiled vcpkg archive (fix dic-iit/bipedal-locomotion-controllers#30)
Check also: https://github.com/actions/virtual-environments/issues/605
> Add cache GitHub Action to cache dependency compiled from source

- cmake/AddBipedalLocomotionControllersComponent.cmake
- src/ParametersHandler/YarpImplementation/CMakeLists.txt
This PR closes #34. In details:
-  `AddBipedalLocomotionControllersComponent` cmake function accepts also the name of a custom installation folder. If the folder is not specified the default one will be used. The name of the default folder is equal to name of the component.
- The header of `ParameterHandlerYarpImplementation` are now installed in `BipedalLocomotionControllers/ParameterHandler`
> Add the possibility to specify the installation folder AddBipedalLocomotionControllersComponent function

- .github/workflows/ci.yml
This PR is required to fix the windows compilation on CI. Please check [here](https://github.com/dic-iit/bipedal-locomotion-framework/runs/752263574)
Associated PR: https://github.com/robotology/idyntree/pull/672
> Require iDynTree v1.1.0 in ci.yml

- .github/workflows/ci.yml
- README.md
- cmake/BipedalLocomotionFrameworkFindDependencies.cmake
- src/Planners/CMakeLists.txt
- src/Planners/include/BipedalLocomotion/Planners/ConvexHullHelper.h
- src/Planners/src/ConvexHullHelper.cpp
- src/Planners/tests/CMakeLists.txt
- src/Planners/tests/ConvexHullHelperTest.cpp
This PR introduces the first version of the `ConvexHullHelper` class inside the Planner Component. 
In order to use the helper, and in general to compile the component, the [Qhull](https://github.com/qhull/qhull) library is now required.
> Implement the ConvexHullHelper class

- src/ContactModels/tests/CMakeLists.txt
- src/ContactModels/tests/ContinousContactModelTest.cpp
This fixes #64. Furthermore, it removes the dependency on YARP for compiling the test
> Improve continuous contact model test

- src/System/include/BipedalLocomotion/System/DynamicalSystem.h
- src/System/include/BipedalLocomotion/System/DynamicalSystem.tpp
- src/System/include/BipedalLocomotion/System/FixedStepIntegrator.h
- src/System/include/BipedalLocomotion/System/FixedStepIntegrator.tpp
- src/System/include/BipedalLocomotion/System/FloatingBaseSystemDynamics.h
- src/System/include/BipedalLocomotion/System/FloatingBaseSystemKinematics.h
- src/System/include/BipedalLocomotion/System/ForwardEuler.h
- src/System/include/BipedalLocomotion/System/ForwardEuler.tpp
- src/System/include/BipedalLocomotion/System/Integrator.h
- src/System/include/BipedalLocomotion/System/Integrator.tpp
- src/System/include/BipedalLocomotion/System/LinearTimeInvariantSystem.h
- src/System/src/FloatingBaseSystemDynamics.cpp
- src/System/src/FloatingBaseSystemKinematics.cpp
- src/System/src/LinearTimeInvariantSystem.cpp
- src/System/tests/IntegratorTest.cpp
This goes in the direction of #56 
Unfortunately in `FloatingBaseSystemDynamics` the conversion of the Eigen vectors/matrix in iDynTree objects is done manually. I think that it can be solved with https://github.com/robotology/idyntree/issues/716
A test for the `FloatingBaseSystemDynamics` class is still missing.
> Use Eigen in DynamicalSystems

- README.md
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/Estimators/FloatingBaseEstimator.h
- src/Estimators/include/BipedalLocomotion/Estimators/FloatingBaseEstimatorIO.h
- src/Estimators/include/BipedalLocomotion/Estimators/FloatingBaseEstimatorParams.h
- src/Estimators/src/FloatingBaseEstimator.cpp
- src/Estimators/tests/CMakeLists.txt
- src/Estimators/tests/FloatingBaseEstimatorTest.cpp
- src/Estimators/tests/ResourceFolderPath.h.in
- src/Estimators/tests/base-estimator/model.urdf
This PR,
- Adds a `FloatingBaseEstimators` library currently implementing the base class `FloatingBaseEstimator` which needs to be derived for proper implementations. It must be noted that this implementation assumes that an IMU is rigidly attached to the floating base link of the bipedal robot.
- Adds a `FloatingBaseEstimatorTest` which describes the generic usage of the `FloatingBaseEstimator` class.
> Add FloatingBaseEstimator skeleton class 

- src/Planners/tests/CMakeLists.txt
https://github.com/dic-iit/bipedal-locomotion-framework/pull/71 removed `checkandset_dependency(Eigen3)` from ` cmake/BipedalLocomotionFrameworkFindDependencies.cmake` as a consequence `FRAMEWORK_HAS_Eigen3` is not defined anymore. Consequentally the test `ContactList` was not compiled anymore.
This PR reenables the compilation of the test
> Avoid checking FRAMEWORK_HAS_Eigen3 in Planner/test/CMakeLists.txt

- src/ParametersHandler/CMakeLists.txt
Since StdImplementation.tpp is included in StdImplementation.h, this is required.
> Add StdImplementation.tpp to Public headers in ParameterHandler CMakeList

- .github/workflows/ci.yml
- CMakeLists.txt
- cmake/BipedalLocomotionFrameworkFindDependencies.cmake
- src/Planners/CMakeLists.txt
- src/Planners/include/BipedalLocomotion/Planners/Contact.h
- src/Planners/include/BipedalLocomotion/Planners/ContactList.h
- src/Planners/src/ContactList.cpp
- src/Planners/src/TimeVaryingDCMPlanner.cpp
- src/Planners/tests/ContactListTest.cpp
- src/Planners/tests/ContactPhaseListTest.cpp
- src/Planners/tests/TimeVaryingDCMPlannerTest.cpp
In this PR I removed the `iDyntree` dependency in favor of `manif`.
I also updated the CI adding `manif` dependency. Here I'm cloning manif from   https://github.com/GiulioRomualdi/manif.git because of https://github.com/artivis/manif/issues/156. I already opened a PR upstream https://github.com/artivis/manif/pull/157 as soon as it has been merged I will update this code.
I would like to wait for the review of @S-Dafarra since he is the first developer of this part of the code
> Use manif in the contacts component

- src/Planners/CMakeLists.txt
- src/Planners/include/BipedalLocomotion/Planners/QuinticSpline.h
- src/Planners/src/QuinticSpline.cpp
- src/Planners/tests/CMakeLists.txt
- src/Planners/tests/QuinticSplineTest.cpp
This PR introduces the `QuinticSpline` class. This class can be seen as an extension of the `iDynTree::CubicSpline` class. The main difference between this class and the `iDynTree` one is the order of the polynomials used in the spline. Using a 5th order spline guarantees to generate a trajectory that minimizes the jerk. (I will add further details for the latest statement later)
> Implement the QuinticSpline class

- .github/workflows/ci.yml
- cmake/Findcppad.cmake
- src/AutoDiff/tests/CppADTest.cpp
Thanks to https://github.com/microsoft/vcpkg/pull/12560 installing `cppad` on windows becomes simple. This PR introduces the support to cppad on Windows.
Related issues #75
> Enable cppad on Windows 

- README.md
- cmake/BipedalLocomotionFrameworkFindDependencies.cmake
- src/CMakeLists.txt
- src/RobotInterface/CMakeLists.txt
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ISensorBridge.h
- src/RobotInterface/tests/CMakeLists.txt
- src/RobotInterface/tests/DummyImplementation/CMakeLists.txt
- src/RobotInterface/tests/DummyImplementation/DummySensorBridge.h
- src/RobotInterface/tests/DummyImplementation/DummySensorBridgeTest.cpp
This PR,
- Adds `RobotInterface` library to the Framework
- Adds `ISensorBridge` interface class to `RobotInterface` library
~~- Adds OpenCV as a dependency for handling `cv::Mat` within the `ISensorBridge` class~~
- Adds a trivial `DummySensorBridge` test implementation to depict the use of the `ISensorBridge` interface
> Add RobotInterface library and a SensorBridge interface class

- CMakeLists.txt
`LAST_EXT` option in `get_file_component` is available only from CMake v3.14, See https://cmake.org/cmake/help/v3.14/command/get_filename_component.html
and https://cmake.org/cmake/help/v3.13/command/get_filename_component.html for comparison.
This is used in https://github.com/dic-iit/bipedal-locomotion-framework/blob/26f45d714097ad3fe299025122cae1864cbef497/cmake/AddBipedalLocomotionLibrary.cmake#L102
> Bump CMake minimum version for LAST_EXT option in get_file_component

- src/GenericContainer/include/BipedalLocomotion/GenericContainer/TemplateHelpers.h
- src/GenericContainer/include/BipedalLocomotion/GenericContainer/Vector.h
- src/GenericContainer/tests/GenericContainerTest.cpp
The class ``Ref`` is used as a substitution to a classical reference to a Vector. The advantage of using this, is that custom vectors (all those supported by ``GenericContainer::Vector``) can be implicitly casted to ``Ref``.
``Ref`` does not allocate any memory in construction, hence can be used as a parameter to be passed by copy. The operator ``=`` clones the content.                                                                      
``Ref`` inherits ``Vector<T>``, hence it can be used as it was a ``Vector<T>``.      
This goes in the direction of fixing #95, at least to simplify the use of ``GenericContainer::Vector<double>`` in public interfaces.
> Add Ref class to GeneriContainer::Vector

- src/Planners/CMakeLists.txt
- src/Planners/include/BipedalLocomotion/Planners/SO3Planner.h
- src/Planners/include/BipedalLocomotion/Planners/SO3Planner.tpp
- src/Planners/tests/CMakeLists.txt
- src/Planners/tests/SO3PlannerTest.cpp
~~**Disclaimer: this PR includes also the modification implemented in #82. This main introduction of this PR is:  https://github.com/dic-iit/bipedal-locomotion-framework/commit/9c3c9a0ad4e602381fdcfa588d4220fa9fb8fb5d https://github.com/dic-iit/bipedal-locomotion-framework/commit/9271e4354c571eb319464b394f87e5aba4980d41 https://github.com/dic-iit/bipedal-locomotion-framework/commit/dae089d5b2060eaab13cb56e7844dd179de8014a**~~
The PR implements a  2-point minimum jerk trajectory planner for SO(3) elements. The Planner extended the theory explained in [**Modern Robotics: Mechanics, Planning, and Control (Chapter 9.2)**](http://hades.mech.northwestern.edu/index.php/Modern_Robotics), and it introduces the possibility to generate the velocity/acceleration expressed not only in body frame but …
> Implement a 2-point minimum jerk trajectory generator in SO(3)

- src/RobotInterface/YarpImplementation/CMakeLists.txt
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ISensorBridge.h
- src/RobotInterface/tests/DummyImplementation/DummySensorBridge.h
This PR adds the YarpSensorBridge implementation that refactors out our traditional way of getting sensor measurements into a library. The current implementation supports measurements read from
- a remote control board remapper implementing encoders interface
- a multiple analog sensor remapper implementing accelerometers, gyroscopes, magnetometers, orientation sensors, and force-torque sensors interface
- generic IMU sensors through a server inertial
- analog FT sensors
- cartesian wrenches opened as generic sensors considered to have dimension size 6
It needs to be configured with a PolyDriverList of the relevant devices that are available in the network, and a configuration setup that informs the SensorBridge about the devices and the underlying sensor interfaces.
Implementation …
> YarpSensorBridge Implementation

- src/Planners/include/BipedalLocomotion/Planners/DCMPlanner.h
- src/Planners/src/TimeVaryingDCMPlanner.cpp
This PR attempts to reduce the memory allocation (and in general improve the performances) in the `TimeVaryingDCMPlanner`, in details:
- https://github.com/dic-iit/bipedal-locomotion-framework/commit/a333d3fb631b91510d0e22ba1b21819320f6e28e Introduces the `QuinticSpline` instead of the `iDynTree::CubicSpline`, here thanks to the usage of the `Eigen::Ref<>` + `Eigen::Map<>` it was possible to directly use `casadi::DM` objects as input of the `QuinticSpline::evaluatePoint()` method. 
- https://github.com/dic-iit/bipedal-locomotion-framework/commit/0681b2d52dcc3698407ba0127be967cdc7def7be add `omega dot` as a state of the Planner.
- I noticed that building the constraints in a `for loop`  is time-consuming (for casadi), in https://github.com/dic-iit/bipedal-locomotion-framework/commit/5a4218a …
> Improve performances TimeVaryingDCMPlanner

- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpRobotControl.h
- src/RobotInterface/YarpImplementation/src/YarpRobotControl.cpp
This PR fixes two bugs in the `yarp` implementation of the `iRobotControl` class.
- https://github.com/dic-iit/bipedal-locomotion-framework/pull/118/commits/8fc2bef8a813d078c64852ec13ca00d3a6e099c3 fixes #115 I followed what @diegoferigo implemented in [wb-toolbox](https://github.com/robotology/wb-toolbox/blob/4278d56dc16e4a76e0b4ef6b872bc3e26c43e451/toolbox/base/src/RobotInterface.cpp#L83).
- https://github.com/dic-iit/bipedal-locomotion-framework/pull/118/commits/8c17556b6a2b8bbe8a5372c0d6060860c3c7e540 resets the vectors containing the desired joint values and the associated control modes when the interface is initialized.
> Bugfix in Yarp iRobotControl implementation

- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
Associated issue  #121 (point 1)
> Use booleans instead of int as configuration parameters in YarpSensorBridge class

- .github/workflows/ci.yml
- src/Planners/include/BipedalLocomotion/Planners/TimeVaryingDCMPlanner.h
- src/Planners/src/TimeVaryingDCMPlanner.cpp
This PR introduces some general improvements for the TimeVarying DCM planner. 
- https://github.com/dic-iit/bipedal-locomotion-framework/commit/5da3568d21c6f91dcf098ba8e899e5728b3ec0a9 convert the `Casadi::MX` element in `Casadi::SX` object. Thanks to this modification the desired DCM trajectory is computed faster.
For instance, the test gives the following results:
- Without the PR:
```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
Ipopt is released as open source code under the Eclipse Public License (EPL).
For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************
solver  :   t_proc      (avg) …
```
> General improvements of the TimeVarying DCM planner

- README.md
The correct spelling is macOS, see:
* https://www.apple.com/macos/catalina/
* https://en.wikipedia.org/wiki/MacOS
> Fix macOs/macOS spelling

- CHANGELOG.md
- README.md
- cmake/BipedalLocomotionFrameworkFindDependencies.cmake
- src/CMakeLists.txt
- src/Conversions/CMakeLists.txt
- src/Conversions/include/BipedalLocomotion/Conversions/CommonConversions.h
- src/Conversions/include/BipedalLocomotion/Conversions/ManifConversions.h
- src/Conversions/tests/CMakeLists.txt
- src/Conversions/tests/ManifConversionsTest.cpp
~This PR includes basic aliases and conversions between Eigen/manif/iDynTree.~
This PR includes conversions between Eigen/manif/iDynTree objects.
Currently, only conversions of transform objects are included.
> Add CommonConversions and ManifConversions library

- .github/workflows/gh-pages.yml
This new release addresses https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> GitHub Action: Bump the webfactory/ssh-agent to v0.4.1

- src/GenericContainer/include/BipedalLocomotion/GenericContainer/Vector.h
It was assuming value_type to be defined, even if not necessary.
> Fix default resizer.

- CHANGELOG.md
- CMakeLists.txt
- cmake/AddBipedalLocomotionYARPDevice.cmake
- devices/CMakeLists.txt
- devices/FloatingBaseEstimatorDevice/CMakeLists.txt
- devices/FloatingBaseEstimatorDevice/FloatingBaseEstimatorDevice.ini
- devices/FloatingBaseEstimatorDevice/app/CMakeLists.txt
- devices/FloatingBaseEstimatorDevice/app/robots/iCubGazeboV2_5/estimators/invekf-base-estimator.xml
- devices/FloatingBaseEstimatorDevice/app/robots/iCubGazeboV2_5/interface/all_joints_mc.xml
- devices/FloatingBaseEstimatorDevice/app/robots/iCubGazeboV2_5/interface/root_imu.xml
- devices/FloatingBaseEstimatorDevice/app/robots/iCubGazeboV2_5/interface/wbd_left_foot.xml
- devices/FloatingBaseEstimatorDevice/app/robots/iCubGazeboV2_5/interface/wbd_right_foot.xml
- devices/FloatingBaseEstimatorDevice/app/robots/iCubGazeboV2_5/launch-base-estimator.xml
- devices/FloatingBaseEstimatorDevice/include/BipedalLocomotion/FloatingBaseEstimatorDevice.h
- devices/FloatingBaseEstimatorDevice/scope/sim/base_pose_scope.xml
- devices/FloatingBaseEstimatorDevice/scope/sim/base_velocity_scope.xml
- devices/FloatingBaseEstimatorDevice/scope/sim/contact_normal_scope.xml
- devices/FloatingBaseEstimatorDevice/scope/sim/waist_imu.xml
- devices/FloatingBaseEstimatorDevice/src/FloatingBaseEstimatorDevice.cpp
This PR adds a YARP device wrapper for the FloatingBaseEstimator library, in its current version implementing an InvariantEKF.
**Remark for reviewers:**
Mostly contains small files for configuration and scopes.
Only two files for the source code are significantly big.
> Add FloatingBaseEstimatorDevice YARP wrapper to the algorithms in FloatingBaseEstimator library

- src/RobotInterface/YarpImplementation/CMakeLists.txt
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpHelper.h
- src/RobotInterface/YarpImplementation/src/YarpHelper.cpp
- utilities/joint-position-tracking/src/Module.cpp
`constructYarpRobotDevice` function has been implement. Thanks to this function it will be easy to create a remote control board polydriver. 
The function is then used in the `joint-position-tracking` application.
cc @isorrentino
> Implement constructYarpRobotDevice

- devices/FloatingBaseEstimatorDevice/FloatingBaseEstimatorDevice.ini
Sorry, this is a leftover that I missed in https://github.com/dic-iit/bipedal-locomotion-framework/pull/155.
> FloatingBaseEstimatorDevice: remove leftover ini file

- CHANGELOG.md
- src/YarpUtilities/CMakeLists.txt
- src/YarpUtilities/include/BipedalLocomotion/YarpUtilities/RosPublisher.h
- src/YarpUtilities/src/RosPublisher.cpp
This PR adds a class for publishing wrenches, joint states and transforms over ROS topics using YARP only software.
Inspiration was taken from [human-dynamics-estimation/publishers](https://github.com/robotology/human-dynamics-estimation/tree/master/publishers).
The class internally contains a YARP based ROS node and a set of publishers which can be configured for publishing over certain topics and configuring connections to a YARP transform server in order to publish transforms. 
Although the class might be ROS independent, in order to run the code, ROS is required and usual YARP-ROS connections need to be made.
A test device has also been implemented, I can include it in this PR if required.
This PR depends on  https://github.com/dic-iit/bipedal-locomotion-framework/pull/155 if the test …
> Implement a YARP based ROS publisher class in YarpUtilities library.

- CHANGELOG.md
- CMakeLists.txt
- cmake/AddBipedalLocomotionYARPDevice.cmake
- devices/examples/CMakeLists.txt
- devices/examples/ROSPublisherTestDevice/CMakeLists.txt
- devices/examples/ROSPublisherTestDevice/README.md
- devices/examples/ROSPublisherTestDevice/app/CMakeLists.txt
- devices/examples/ROSPublisherTestDevice/app/robots/iCubGazeboV2_5/launch-ros-publisher-test.xml
- devices/examples/ROSPublisherTestDevice/app/robots/iCubGazeboV2_5/publisher/ros-publisher.xml
- devices/examples/ROSPublisherTestDevice/include/BipedalLocomotion/ROSPublisherTestDevice.h
- devices/examples/ROSPublisherTestDevice/ros-publisher-test-runner.xml
- devices/examples/ROSPublisherTestDevice/src/ROSPublisherTestDevice.cpp
This PR adds a test device for YARP based ROS Publisher added in https://github.com/dic-iit/bipedal-locomotion-framework/pull/156.
Current implementation cannot fit in to a CI testing framework, since the process requires `roscore` to run (which is not our dependency), further it requires an additional subscribing mechanism to check if the data is published properly or not. 
So we will stick to manually running the test device, at the moment. We could fix it when we have more time dedicated for software-engineering tasks.
> Add a test device for YARP based ROS Publisher 

- src/TSID/tests/JointsTrackingTaskTest.cpp
- src/TSID/tests/SE3TaskTest.cpp
When blf is built in debug, running TSID tests lasts 30 minutes. This should speed up the tests
> Speed up TSID tests

- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpHelper.h
- src/RobotInterface/YarpImplementation/src/YarpHelper.cpp
- utilities/joint-position-tracking/include/BipedalLocomotion/JointPositionTracking/Module.h
- utilities/joint-position-tracking/src/Module.cpp
- utilities/joint-trajectory-player/include/BipedalLocomotion/JointTrajectoryPlayer/Module.h
- utilities/joint-trajectory-player/src/Module.cpp
This is required because in a next PR I'm going to implement a function to build a [`GenericSensorClient`](https://github.com/robotology/whole-body-estimators/blob/master/devices/genericSensorClient/GenericSensorClient.h) required to retrieve the estimation of the contact wrenches  
- Rename BipedalLocomotion::RobotInterface::constructYarpRobotDevice() into BipedalLocomotion::RobotInterface::constructRemoteControlBoardRemapper()
- Introduce PolyDriverDescriptor in RobotInterface/YarpHelper
> General refactoring of polydriver construction in RobotInterface

- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ISensorBridge.h
- src/RobotInterface/tests/DummyImplementation/DummySensorBridge.h
This PR includes,
- bug fixes in using the MAS interface through the YarpSensorBridge
- removal of camera related methods from the SensorBridge implementations since a separate ICameraBridge is being added in https://github.com/dic-iit/bipedal-locomotion-framework/pull/165
> [RobotInterface] Fix MAS sensors in YarpSensorBridge and remove cameras from SensorBridge

- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/RobotInterface.cpp
- bindings/python/bipedal_locomotion_framework.cpp
- bindings/python/bipedal_locomotion_framework.h
- cmake/BipedalLocomotionFrameworkDependencies.cmake
The PR introduces the python bindings for the `IRobotControl` and the `YARP` implementation.
This is a usage example
```python
import bipedal_locomotion_framework.bindings as blf
import time
if __name__ == "__main__":
handler = blf.StdParametersHandler()
handler.set_parameter_vector_string("joints_list", ["r_hip_pitch", "r_hip_roll", "r_hip_yaw", "r_knee", "r_ankle_pitch", "r_ankle_roll"])
handler.set_parameter_vector_string("remote_control_boards", ["right_leg"])
handler.set_parameter_string("robot_name", "icubSim")
handler.set_parameter_string("local_prefix", "test_local")
handler.set_parameter_float("positioning_duration", 3.0)
handler.set_parameter_float("positioning_tolerance", 0.05)
handler.set_parameter_float("position_direct_max_admissible_error", 0.1)
control_board = …
```
> Implement IRobotControl python bindings

- CHANGELOG.md
- bindings/python/RobotInterface.cpp
- bindings/python/bipedal_locomotion_framework.cpp
- bindings/python/bipedal_locomotion_framework.h
Similar to #200 
The following example explains how to use bindings
```python
import bipedal_locomotion_framework.bindings as blf
import time
if __name__ == "__main__":
handler = blf.StdParametersHandler()
handler.set_parameter_vector_string("joints_list", ["r_hip_pitch", "r_hip_roll", "r_hip_yaw", "r_knee", "r_ankle_pitch", "r_ankle_roll"])
handler.set_parameter_vector_string("remote_control_boards", ["right_leg"])
handler.set_parameter_string("robot_name", "icubSim")
handler.set_parameter_string("local_prefix", "test_local")
handler.set_parameter_float("positioning_duration", 3.0)
handler.set_parameter_float("positioning_tolerance", 0.05)
handler.set_parameter_float("position_direct_max_admissible_error", 0.1)
handler.set_parameter_float("position_direct_max_admissible_error", 0.1) …
```
> Implement ISensorBridge python bindings

- CHANGELOG.md
- devices/FloatingBaseEstimatorDevice/include/BipedalLocomotion/FloatingBaseEstimatorDevice.h
- devices/FloatingBaseEstimatorDevice/src/FloatingBaseEstimatorDevice.cpp
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimatorIO.h
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/InvariantEKFBaseEstimator.h
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/LeggedOdometry.h
- src/Estimators/src/FloatingBaseEstimator.cpp
- src/Estimators/src/InvariantEKFBaseEstimator.cpp
- src/Estimators/src/LeggedOdometry.cpp
- src/Estimators/tests/FloatingBaseEstimators/FloatingBaseEstimatorTest.cpp
- src/Estimators/tests/FloatingBaseEstimators/InvariantEKFBaseEstimatorTest.cpp
This PR tries to improve the existing feature of floating base estimator by allowing the handling of multiple contacts. 
It also implements the Legged odometry algorithm.
This PR also makes an API change to the `initialize()` method of the `FloatingBaseEstimator` class, since KinDynComputations is changed from being an object of the class to a shared_pointer of an external object.
This PR depends on 
- #141 (Merged)
- #142 (Merged)
> Allow FloatingBaseEstimator to handle multiple contacts, Implement Legged Odometry and favor iDynTree KinDynComputations instead of Model

- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/Constants.cpp
- bindings/python/Contacts.cpp
- bindings/python/TimeVaryingDCMPlanner.cpp
- bindings/python/bipedal_locomotion_framework.cpp
- bindings/python/bipedal_locomotion_framework.h
- bindings/python/tests/test_time_verying_dcm_planner.py
- src/Math/CMakeLists.txt
- src/Math/include/BipedalLocomotion/Math/Constants.h
- src/Planners/CMakeLists.txt
- src/Planners/include/BipedalLocomotion/Planners/DCMPlanner.h
- src/Planners/include/BipedalLocomotion/Planners/TimeVaryingDCMPlanner.h
- src/Planners/src/DCMPlanner.cpp
- src/Planners/src/TimeVaryingDCMPlanner.cpp
- src/Planners/tests/CMakeLists.txt
- src/Planners/tests/TimeVaryingDCMPlannerTest.cpp
With this PR it will be possible to pass a desired reference DCM trajectory to the DCMPlanner. The trajectory will be used as a regularization term. 
In details it introduces the optional parameter `use_external_dcm_reference`. If set to true the user should call  `setDCMReference()` to set the desired DCM reference.
The python bindings have been updated and they already implement this new feature. 
I checked the output of the planner with the already existing code and this is the planned trajectory
cc @paolo-viceconte @diegoferigo
> Add the possibility to pass a reference DCM trajectory to the DCMPlanner

- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/ContactDetectors.cpp
- bindings/python/bipedal_locomotion_framework.cpp
- bindings/python/bipedal_locomotion_framework.h
- bindings/python/tests/pytest.ini
- bindings/python/tests/test_schmitt_trigger_detector.py
- Added bindings for SchmittTriggerDetector class
- Added a pytest script reflecting [SchmittTriggerDetectorUnitTest](https://github.com/dic-iit/bipedal-locomotion-framework/blob/master/src/Contacts/tests/ContactDetectors/SchmittTriggerDetectorUnitTest.cpp)
> Add python bindings for SchmittTriggerDetector class

- CHANGELOG.md
- devices/FloatingBaseEstimatorDevice/include/BipedalLocomotion/FloatingBaseEstimatorDevice.h
- devices/FloatingBaseEstimatorDevice/src/FloatingBaseEstimatorDevice.cpp
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimatorIO.h
- src/Estimators/src/FloatingBaseEstimator.cpp
- src/Estimators/src/InvariantEKFBaseEstimator.cpp
- src/Estimators/src/LeggedOdometry.cpp
- src/Estimators/tests/FloatingBaseEstimators/CMakeLists.txt
- src/Estimators/tests/FloatingBaseEstimators/FloatingBaseEstimatorTest.cpp
- src/Estimators/tests/FloatingBaseEstimators/InvariantEKFBaseEstimatorTest.cpp
Many thanks to @GiulioRomualdi , @S-Dafarra  and @traversaro for the iDynTree MatrixView/KinDynComputations span PRs, this was made considerably easy.
Fixes #107
> FloatingBaseEstimators: Replace iDynTree types with Eigen/manif

- CHANGELOG.md
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/ModelComputationsHelper.h
- src/Estimators/src/ModelComputationsHelper.cpp
- src/Estimators/tests/FloatingBaseEstimators/CMakeLists.txt
- src/Estimators/tests/FloatingBaseEstimators/InvariantEKFBaseEstimatorTest.cpp
This PR,
- adds `KinDynComputationsDescriptor` class which is a simple wrapper for a shared pointer for an iDyntree KinDynComputations object
- helper method to load a model and construct a valid KinDynComputations using a parameter handler
Related issue https://github.com/dic-iit/bipedal-locomotion-framework/issues/214#issuecomment-786666189
> Add ModelComputationsHelper to constuct KinDynComputations object

- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/FloatingBaseEstimators.cpp
- bindings/python/LeggedOdometry.cpp
- bindings/python/ParametersHandler.cpp
- bindings/python/bipedal_locomotion_framework.cpp
- bindings/python/bipedal_locomotion_framework.h
- bindings/python/tests/CMakeLists.txt
- bindings/python/tests/model.urdf
- bindings/python/tests/pytest.ini
- bindings/python/tests/test_legged_odometry.py
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/LeggedOdometry.h
- src/Estimators/src/LeggedOdometry.cpp
> Add python bindings for FloatingBaseEstimator and LeggedOdometry 

- bindings/python/TimeVaryingDCMPlanner.cpp
- src/Planners/include/BipedalLocomotion/Planners/DCMPlanner.h
- src/Planners/include/BipedalLocomotion/Planners/TimeVaryingDCMPlanner.h
- src/Planners/src/TimeVaryingDCMPlanner.cpp
#208 implements   `setDCMReference()` however the user had to call the function after `setContactPhaseList()`.  Thanks to this PR, `setDCMReference()` does not depends on `setContactPhaseList()` and the user can call it whenever their want. 
cc @paolo-viceconte
> [TimeVaryingDCMPlanner] restructure of setDCMReference() and setContactPhaseList()

- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/ModelComputationsHelper.h
- src/Estimators/src/ModelComputationsHelper.cpp
This option is useful while loading human URDF models.
> ModelComputationsHelper: Option to load KinDynComputationsDescriptor without specifying joints list

- CHANGELOG.md
- bindings/python/RobotInterface.cpp
- devices/FloatingBaseEstimatorDevice/src/FloatingBaseEstimatorDevice.cpp
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ISensorBridge.h
- src/RobotInterface/tests/DummyImplementation/DummySensorBridge.h
- src/RobotInterface/tests/DummyImplementation/DummySensorBridgeTest.cpp
**THIS PR BREAKS THE API**
This PR attempts to remove the usage of raw pointers in ISensorBridge. This can be done using `std::optional<std::reference_wrapper<double>>`. 
You can find further information in https://stackoverflow.com/questions/62454934/optionalreference-wrappert-vs-optionalt-practical-examples
cc @isorrentino @traversaro @S-Dafarra
> Use std::optional instead of raw pointer in ISensorBridge

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/CMakeLists.txt
- src/ParametersHandler/CMakeLists.txt
- src/ParametersHandler/include/BipedalLocomotion/ParametersHandler/StdImplementation.tpp
- src/ParametersHandler/src/StdImplementation.cpp
- src/Planners/CMakeLists.txt
- src/Planners/src/TimeVaryingDCMPlanner.cpp
- src/TextLogging/CMakeLists.txt
- src/TextLogging/include/BipedalLocomotion/TextLogging/Logger.h
- src/TextLogging/src/Logger.cpp
This pr should be seen as a point where we can discuss. Then if we found a common agreement we may think to merge it.
In this PR I added [`spdlog`](ttps://github.com/gabime/spdlog). It is a nice log that can be used to print stuff in the terminal.
The dependency can be installed with `apt` `vcpkg` and `brew`. 
This is the output of the `TimeVaryingDCMTest` with the code implemented in this PR.
We can further customize the output: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting.
It's also possible to automatically print the name of the function, name of the file and line. However, we should define some macros.
The nice thing is that it can be used in a multithread application https://cran.r-project.org/web/packages/RcppSpdlog/vignettes/introduction.html
cc @traversaro …
> Start using spdlog in the repo

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
This PR fixes bugs in `YarpSensorBridge::attachAllSixAxisForceTorqueSensors()`,
- fix the wrong usage of ` set_intersection` with `set_difference`
- call `checkAttachedMASSensors` on the MAS FT interface to update internal name/index buffers
> bug fix: YarpSensorBridge attach FT sensors 

- src/Planners/tests/SO3PlannerTest.cpp
Right now, valgrind is needing 5mins to run it, after this it is reduced to 30sec
> Reduce the time needed by the SO3PlannerTest

- .github/workflows/conda-forge-ci-build-and-tests.yml
- .github/workflows/conda-forge-ci.yml
Add GitHub Action job that compile the project using conda-forge-provided dependencies on Linux/macOS/Windows. The main advantage over apt-based workflow is that we always get the latest version of dependencies, easily detecting eventual regressions. Furthermore, no dependency needs to be compiled from source, making the GitHub Action simpler and more mantainable. 
Similar PRs:
* https://github.com/dic-iit/matio-cpp/pull/29
* https://github.com/robotology/idyntree/pull/786
> Add conda-force-ci GitHub Action job

- CHANGELOG.md
- src/Math/CMakeLists.txt
- src/Math/include/BipedalLocomotion/Math/LinearizedFrictionCone.h
- src/Math/src/LinearizedFrictionCone.cpp
- src/Math/tests/CMakeLists.txt
- src/Math/tests/LinearizedFrictionConeTest.cpp
This PR implements the computation of the LinearizedFrictionCone (only for the tangential component)
The implementation follows the [matlab code developed](https://github.com/robotology/whole-body-controllers/blob/0567206c5c0fae359a9abf5c384759e058f9a7e9/library/matlab-wbc/%2Bwbc/computeRigidContactConstraints.m) by  @gabrielenava
> Implement LinearizedFrictionCone class

- .github/workflows/ci.yml
- bindings/python/bipedal_locomotion_framework.cpp.in
- cmake/BipedalLocomotionFrameworkDependencies.cmake
This follows https://github.com/dic-iit/bipedal-locomotion-framework/issues/246#issuecomment-808711753
Now we can use pybind11 installed from apt in ubuntu 20.04
> Fix pybind11 version

- src/TextLogging/src/Logger.cpp
Without this PR a multithread application may crash  at 
https://github.com/dic-iit/bipedal-locomotion-framework/blob/4e82be2f098aa836a6dce9feb9a6c6ad5ee0f876/src/TextLogging/src/Logger.cpp#L23
> Make BipedaLocomotion::log() function thread safe.

- cmake/InstallBasicPackageFiles.cmake
The CMAKE_MODULE_PATH_BK variable was used also in matio-cpp.
Related issue #259
> Fixed InstallBasicPackageFiles

- .github/workflows/conda-forge-ci.yml
As https://github.com/robotology/robotology-superbuild/pull/652 has been merged, we now have officially generated packages coming from the robotology-superbuild in the [robotology anaconda channel](https://anaconda.org/robotology), so we can switch to use that instead of the experimental and test-only `robotology-staging`.
> conda-forge-ci: Switch to use official robotology channel

- CHANGELOG.md
- src/System/CMakeLists.txt
- src/System/YarpImplementation/CMakeLists.txt
- src/System/YarpImplementation/include/BipedalLocomotion/System/YarpClock.h
- src/System/YarpImplementation/src/YarpClock.cpp
- src/System/include/BipedalLocomotion/System/Clock.h
- src/System/include/BipedalLocomotion/System/IClock.h
- src/System/include/BipedalLocomotion/System/StdClock.h
- src/System/src/Clock.cpp
- src/System/src/StdClock.cpp
Another piece required for the block runner is a clock. Here I introduced the interface IClock and two concrete implementations `StdClock` and `YarpClock`. The former is useful for standalone applications while the latter becomes pivotal when you want to simulate your system with gazebo and using a shared clock. 
The clocks, both yarp, and std are implemented using singleton and they are instantiated using the factory paradigm. The `std` lof is the default clock. If you want to use the `yarp` one you should set the associated factory in the `ClockBuilder`.
Long story short. 
1. Do you want to use a normal std clock?
```cpp
// this will return the time since the epoch
auto now = BipedalLocomotion::clock().now();
```
2. Do you want to use yarp clock?
```cpp
// Change the clock. Call it only …
```
> Implement Clock class

- CHANGELOG.md
- src/RobotInterface/CMakeLists.txt
- src/RobotInterface/YarpImplementation/src/YarpRobotControl.cpp
This fixes https://github.com/dic-iit/bipedal-locomotion-framework/issues/270
> Bugfix in YarpRobotControl::Impl::setReferences

- CHANGELOG.md
- src/Perception/CMakeLists.txt
- src/Perception/include/BipedalLocomotion/Perception/Features/PointCloudProcessor.h
- utilities/realsense-test/config/robots/iCubGazeboV2_5/blf-realsense-pointcloud-test-options.ini
- utilities/realsense-test/include/BipedalLocomotion/RealSenseTest/Module.h
- utilities/realsense-test/src/Module.cpp
This PR adds 
- a `PointCloudProcessor` class in the `PerceptionFeatures` library
- a modification to the `realsense-test` utility to visualize the processed point clouds.
All of the code snippets are taken from the tutorials in https://pcl.readthedocs.io/projects/tutorials/en/latest/. However, this PR creates a templatized class for carrying out the necessary processing. 
Inspired from [ANYbotics/PointcloudProcessor](https://github.com/ANYbotics/grid_map/blob/master/grid_map_pcl/include/grid_map_pcl/PointcloudProcessor.hpp)
> Add a PointCloudProcessor class to the PerceptionFeatures library

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/CMakeLists.txt
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpCameraBridge.h
- src/RobotInterface/YarpImplementation/src/YarpCameraBridge.cpp
YarpCameraBridge allows to access YARP based camera devices.
Currently available interfaces
- Depth Cameras through RGBD sensor interface
- Camera images through OpenCV Grabber interface
Related results in https://github.com/dic-iit/bipedal-locomotion-framework/issues/94#issuecomment-739954442
> Add YarpCameraBridge to PerceptionInterfaceYarpImplementation library

- CHANGELOG.md
- src/GenericContainer/include/BipedalLocomotion/GenericContainer/TemplateHelpers.h
- src/System/CMakeLists.txt
- src/System/YarpImplementation/include/BipedalLocomotion/System/YarpClock.h
- src/System/YarpImplementation/src/YarpClock.cpp
- src/System/include/BipedalLocomotion/System/Advanceable.h
- src/System/include/BipedalLocomotion/System/AdvanceableRunner.h
- src/System/include/BipedalLocomotion/System/IClock.h
- src/System/include/BipedalLocomotion/System/SharedResource.h
- src/System/include/BipedalLocomotion/System/StdClock.h
- src/System/src/StdClock.cpp
- src/System/tests/AdvanceableRunnerTest.cpp
- src/System/tests/CMakeLists.txt
This is the latest block missing for #260.
Related PR: #256
> Introduce Advanceable Runner and SharedResource

- CHANGELOG.md
- src/Contacts/include/BipedalLocomotion/Contacts/Contact.h
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimatorIO.h
- src/Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimatorParams.h
- src/Estimators/src/FloatingBaseEstimator.cpp
- src/Estimators/src/InvariantEKFBaseEstimator.cpp
- Adds support for landmarks in estimators
- In-code disabling of some functionality related to InvariantEKF using a simple flag
- Add logic to use estimator without specifying a model (useful for estimation that does not involve kinematics)
> General improvements for FloatingBaseEstimators library

- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/FixedBaseDynamics.h
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/FloatingBaseDynamicsWithCompliantContacts.h
- src/ContinuousDynamicalSystem/src/FixedBaseDynamics.cpp
- src/ContinuousDynamicalSystem/src/FloatingBaseDynamicsWithCompliantContacts.cpp
This PR attempts to fix part of #273. In details the `FixedBaseDynamics::setKinDyn()` and `FloatingBaseDynamicsWithCompliantContacts::setKinDyn()` has been remove and 
`FixedBaseDynamics::setRobotModel()` and `FloatingBaseDynamicsWithCompliantContacts::setRobotModel()` has been implemented.
> Avoid to set a shared_ptr of kinDyn object in ContinuousDynamicalSystem classes 

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
This pr changes a bit the implementation of sensor bridge. In details:
1. In https://github.com/dic-iit/bipedal-locomotion-framework/commit/ca31b8968dd422c3e6d2a70c5c8cc3012939a478 I avoid creating temporary yarp::sig::vector every time the joint state is read from the yarpinterface. Furthermore, the motors current was not ordered using `remappedJointIndices`
2. In cf44af6 I run `clang_format` and I start using spdlog instead of court to prints info and errors
> Some improvements in sensorbridge

- CHANGELOG.md
- src/TSID/CMakeLists.txt
- src/TSID/include/BipedalLocomotion/TSID/SO3Task.h
- src/TSID/src/SO3Task.cpp
- src/TSID/tests/CMakeLists.txt
- src/TSID/tests/SO3TaskTest.cpp
As written in the title the PR implements the SO3Task  in tsid. I also wrote a simple test to spot possible bugs.
> Implement SO3 task in TSID

- CHANGELOG.md
- src/Estimators/src/LeggedOdometry.cpp
The frame index for world reference frame was not initialized to a proper value when it is not specified in the parameter configuration.
This PR fixes #287.
> [FloatingBaseEstimator] Bug fix in  initialization LeggedOdometry

- CHANGELOG.md
- src/Estimators/src/LeggedOdometry.cpp
LeggedOdometry::Impl::updateInternalContactStates() is now called even if the legged odometry is not initialize. This was required to have a meaningful base estimation the first time `LeggedOdometry::changeFixedFrame()` is called.
> Bugfix in LeggedOdometry::updateKinematics()

- CHANGELOG.md
- src/System/include/BipedalLocomotion/System/VariablesHandler.h
- src/System/src/VariablesHandler.cpp
- src/System/tests/VariablesHandlerTest.cpp
- Implement VariablesHandler::clear()
- Implement VariablesHandler::initialize()
- Use TextLogging in VariblesHandler class
- Update the VariablesHandlerTest
This closes #286 
cc @isorrentino
> Add the possibility to initialize the VariablesHandler with the ParametersHandler

- CHANGELOG.md
- src/Contacts/include/BipedalLocomotion/Contacts/ContactPhaseList.h
- src/Contacts/src/ContactPhaseList.cpp
- src/Contacts/tests/Contacts/ContactPhaseListTest.cpp
This Implements the copy-constructor and copy-assignment operator for the `ContactPhaseList` class. 
`ContactPhaseList` has an attribute called `m_phases`
https://github.com/dic-iit/bipedal-locomotion-framework/blob/d916b56f71eca03a7d1e519e4f13d785665b79ed/src/Contacts/include/BipedalLocomotion/Contacts/ContactPhaseList.h#L37
where `ContactPhase` has a `std::unordered_map` of active contacts during a given phase.
https://github.com/dic-iit/bipedal-locomotion-framework/blob/d916b56f71eca03a7d1e519e4f13d785665b79ed/src/Contacts/include/BipedalLocomotion/Contacts/ContactPhase.h#L37-L40
Accordingly to the `ContactPhaseList` documentation
https://github.com/dic-iit/bipedal-locomotion-framework/blob/d916b56f71eca03a7d1e519e4f13d785665b79ed/src/Contacts/include/BipedalLocomotion/Contacts/ContactP …
> Fix copy-constructor and copy-assignment operator in  `ContactPhaseList` class

- CHANGELOG.md
- src/Contacts/CMakeLists.txt
- src/Contacts/include/BipedalLocomotion/Contacts/ContactList.h
- src/Contacts/src/ContactList.cpp
This PR introduces the possibility to set the default contact in the `ContactList` class. Furthermore it introduces the `TextLogging` in  `ContactList`
> Add the possibility to set the dafault contact in `ContactList` class

- CHANGELOG.md
- src/TSID/CMakeLists.txt
- src/TSID/include/BipedalLocomotion/TSID/QPFixedBaseTSID.h
- src/TSID/src/QPFixedBaseTSID.cpp
- src/TSID/tests/CMakeLists.txt
- src/TSID/tests/QPFixedBaseTSIDTest.cpp
This PR implements the `TaskSpaceInverseDynamics` interface described in https://github.com/dic-iit/bipedal-locomotion-framework/issues/230 and the QPFixedBaseTSID class which is a concrete implementation of the TSID.
The PR is blocked by dic-iit/bipedal-locomotion-framework#242.
[UPDATE]
The PR is ready to be reviewed @GiulioRomualdi @S-Dafarra @prashanthr05 @traversaro
> Implementation of Fixed Base Task Space Inverse Dynamics

- CHANGELOG.md
- src/ParametersHandler/YarpImplementation/include/BipedalLocomotion/ParametersHandler/YarpImplementation.h
- src/ParametersHandler/YarpImplementation/src/YarpImplementation.cpp
- src/ParametersHandler/tests/ParametersHandlerYarpTest.cpp
This PR implements `YarpImplementation::setFromFile()`. This method can be used to easily load a configuration file from the path. 
It will simplify the implementation of the python bindings for `IParameterHandler::YarpImplementation`
cc @paolo-viceconte
> Implement IParameterHandler::YarpImplementation::setFromFile()

- .github/workflows/ci.yml
This follows from https://github.com/IntelRealSense/librealsense/issues/9102#issuecomment-848822964
> Fix librealsense installation in CI

- CHANGELOG.md
- bindings/python/ParametersHandler/CMakeLists.txt
- bindings/python/ParametersHandler/include/BipedalLocomotion/bindings/ParametersHandler/YarpModule.h
- bindings/python/ParametersHandler/include/BipedalLocomotion/bindings/ParametersHandler/YarpParametersHandler.h
- bindings/python/ParametersHandler/src/Module.cpp
- bindings/python/ParametersHandler/src/ParametersHandler.cpp
- bindings/python/ParametersHandler/src/YarpModule.cpp
- bindings/python/ParametersHandler/src/YarpParametersHandler.cpp
- bindings/python/ParametersHandler/tests/config.ini
- bindings/python/ParametersHandler/tests/test_parameters_handler_yarp.py
- bindings/python/bipedal_locomotion_framework.cpp.in
This PR implements the python bindings for the `YarpParametersHandler` class. 
It is possible to load the parameters directly from the configuration file thanks to `set_from_file` method. While writing the tests I noticed a bug in the `setParameter` method for the `YarpParametersHandler` #308. I think this is te reason why the test is failing:
```
40: =================================== FAILURES ===================================
40: __________________________________ test_bool ___________________________________
40: 
40:     def test_bool():
40:     
40:         handler = blf.YarpParametersHandler()
40:     
40:         handler.set_parameter_bool(name="my_bool", value=True)
40:     
40: >       assert handler.get_parameter_bool(name="my_bool") is True
40: E       ValueError: Failed to …
```
> Implement YarpParametersHandler bindings

- src/ParametersHandler/YarpImplementation/include/BipedalLocomotion/ParametersHandler/YarpImplementation.h
- src/ParametersHandler/YarpImplementation/src/YarpImplementation.cpp
This fixes https://github.com/dic-iit/bipedal-locomotion-framework/issues/317
> Implement template specialization for YarpImplementation::setParameterPrivate in case of std::vector<bool>

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- README.md
- bindings/python/Contacts/include/BipedalLocomotion/bindings/Contacts/Contacts.h
- bindings/python/Contacts/src/Contacts.cpp
- bindings/python/Contacts/src/Module.cpp
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/Contacts/CMakeLists.txt
- src/Contacts/include/BipedalLocomotion/Contacts/ContactList.h
- src/Contacts/include/BipedalLocomotion/Contacts/ContactListJsonParser.h
- src/Contacts/include/BipedalLocomotion/Contacts/ContactPhaseList.h
- src/Contacts/src/ContactListJsonParser.cpp
- src/Contacts/tests/Contacts/ContactListTest.cpp
This PR closes #315 in detail I used [nlohmann json](https://github.com/nlohmann/json/) to parse the JSON file.
The two functions can be used to store and read from a JSON file the contact lists.
TODO
> Implement contactListMapFromJson() and contactListMapToJson() methods

- CHANGELOG.md
- bindings/python/Planners/tests/test_swing_foot_planner.py
- src/Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
- src/Planners/src/SwingFootPlanner.cpp
- src/Planners/tests/SwingFootPlannerTest.cpp
This PR introduces `foot_take_off_acceleration` and `foot_take_off_velocity` parameters in the `SwingFootPlanner` class.
I also remove `std::cerr` in favour if `log()->error(...)`
> Add `foot_take_off_acceleration` and `foot_take_off_velocity` parameters in the `SwingFootPlanner` class

- CHANGELOG.md
- devices/examples/CMakeLists.txt
- devices/examples/FTIMULoggerDevice/CMakeLists.txt
- devices/examples/FTIMULoggerDevice/README.md
- devices/examples/FTIMULoggerDevice/app/CMakeLists.txt
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/ft-imu-logger.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/interface/ft-imu-mas-remapper.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/interface/mas-left-foot-ft-client.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/interface/mas-left-leg-ft-client.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/interface/mas-left-leg-inertial-client.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/interface/mas-right-foot-ft-client.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/interface/mas-right-leg-ft-client.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/interface/mas-right-leg-inertial-client.xml
- devices/examples/FTIMULoggerDevice/app/robots/iCubGenova04/launch-ft-imu-logger.xml
- devices/examples/FTIMULoggerDevice/include/BipedalLocomotion/FTIMULoggerDevice.h
- devices/examples/FTIMULoggerDevice/src/FTIMULoggerDevice.cpp
This PR adds,
- an example device that access the strain2 sensor based FT-IMU pairs available on `iCubGenova04` through the `YarpSensorBridge` and logs the foot IMU and  FT sensor measurements using a naive Eigen+matioCpp based implementation.
P.S. for a scalable implementation, it is recommended to use the `yarp-telemetry` based logging.
> Add matioCpp-based FTIMULogger example device

- CHANGELOG.md
- src/ParametersHandler/YarpImplementation/src/YarpImplementation.cpp
- src/ParametersHandler/include/BipedalLocomotion/ParametersHandler/StdImplementation.tpp
- src/ParametersHandler/src/StdImplementation.cpp
- src/YarpUtilities/include/BipedalLocomotion/YarpUtilities/Helper.tpp
- src/YarpUtilities/src/Helper.cpp
This PR implements what discussed in https://github.com/dic-iit/bipedal-locomotion-framework/issues/120#issuecomment-858048366
It closes https://github.com/dic-iit/bipedal-locomotion-framework/issues/120
cc @diegoferigo and @S-Dafarra
> Change the parameters handler verbosity

- CHANGELOG.md
- src/Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
- src/Planners/src/SwingFootPlanner.cpp
Refer to https://github.com/dic-iit/bipedal-locomotion-framework/pull/323#issuecomment-859498629. #323 introduced new mandatory parameters. Since they can be easily defaulted to `0.0`, this PR makes them optional so that the existing code that does not include the new parameters in its handler keeps working as before.
> Restore backward compatibility of SwingFootPlanner parameters

- .github/workflows/conda-forge-ci.yml
Local fix for https://github.com/dic-iit/bipedal-locomotion-framework/issues/353 . I will do the proper fix at the casadi-feedstock level, but for the time being this should work fine.
> conda CI: Use CasADi>=3.5.5 to avoid that an old CasADi without ipopt is picked by the conda solver

- .github/workflows/conda-forge-ci.yml
With this PR we start using manif provided by conda-forge instead of the one installed from sources.
The next step is to remove also toml-plus-plus but this is currently blocked by https://github.com/conda-forge/staged-recipes/pull/14921
> Use manif provided by conda-forge in CondaForge CI

- CHANGELOG.md
- src/Math/CMakeLists.txt
- src/Math/include/BipedalLocomotion/Math/ContactWrenchCone.h
- src/Math/src/ContactWrenchCone.cpp
- src/Math/tests/CMakeLists.txt
- src/Math/tests/FrictionConesTest.cpp
The math is taken from [Stability of surface contacts for humanoid robots: Closed-form formulae of the Contact Wrench Cone for rectangular support areas](https://ieeexplore.ieee.org/document/7139910)
The PR is required to implement the Feasibility wrench constraint in TSID
cc @Giulero
> Implement Contact wrench Cone in math component 

- CHANGELOG.md
- bindings/python/RobotInterface/src/SensorBridge.cpp
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ISensorBridge.h
- utilities/joint-trajectory-player/config/robots/iCubGazeboV3/blf-joint-trajectory-player-options.ini
This PR is meant to add the possibility to log motor encoders, current sensors, WBD torque estimates, motor PWMs, PID references.
> Stream motor state, joint torques and PID state in SensorBridge

- src/RobotInterface/YarpImplementation/src/YarpRobotControl.cpp
> Fix YarpRobotControl when PWM or Torque control is used

- CHANGELOG.md
- src/Math/include/BipedalLocomotion/Math/ContactWrenchCone.h
- src/Math/include/BipedalLocomotion/Math/LinearizedFrictionCone.h
- src/Math/src/ContactWrenchCone.cpp
- src/Math/src/LinearizedFrictionCone.cpp
- src/TSID/CMakeLists.txt
- src/TSID/include/BipedalLocomotion/TSID/FeasibleContactWrenchTask.h
- src/TSID/src/FeasibleContactWrenchTask.cpp
- src/TSID/tests/CMakeLists.txt
- src/TSID/tests/FeasibleContactWrenchTaskTest.cpp
This PR implements a task for the TSID component ensuring a feasible contract  wrench
> Implement FeasibleContactWrenchTask for TSID component

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/src/YarpRobotControl.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/IRobotControl.h
This enables the possibility to set the motor current in RobotInterface class. The current is expressed in `ampere`
> Enable the Current control in RobotInterface class

- .github/workflows/ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/IK/include/BipedalLocomotion/IK/SE3Task.h
- src/IK/src/SE3Task.cpp
- src/System/CMakeLists.txt
- src/System/include/BipedalLocomotion/System/ITaskControllerManager.h
This PR adds the possibility to disable/enable the LieGroup controller in the `IK::SE3Task`. 
This feature is useful when the task is used to control the foot. Indeed when the foot is in contact with the ground the desired cartesian velocity should be fixed to zero.
As far as I know, @paolo-viceconte needed this feature to obtain successful results in his test. This PR give a better structure to the feature. 
This PR depends on https://github.com/dic-iit/lie-group-controllers/pull/9
> Add the possibility to disable the proportional controller in the IK::SE3Task

- CHANGELOG.md
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/FloatingBaseSystemKinematics.h
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/ForwardEuler.h
- src/ContinuousDynamicalSystem/src/FloatingBaseSystemKinematics.cpp
- src/ContinuousDynamicalSystem/tests/IntegratorFloatingBaseSystemKinematics.cpp
- src/IK/tests/QPInverseKinematicsTest.cpp
This PR introduces the possibility to use ForwardEuler integrator with manif objects. Thanks to this I removed the  Baumgarte stabilization in FloatingBaseSystemKinematics class
> Add the possibility to use manif objects in the ForwardEuler integrator

- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/FloatingBaseEstimators/src/LeggedOdometry.cpp
* Fixed compilation of Python bindings on Windows on MSVC. The problem was that the pybind11 bindings for LeggedOdometry references some `LeggedOdometry::resetEstimator` overloads that actually belonged to the parent class  `FloatingBaseEstimator`.
* Fixed loading of tests on MSVC by copying the BLF dll to the directory in which the Python binding dll is found, to avoid problem in loading blf dll as on Windows there is no RPATH
* Switch GitHub Actions conda CI to use Ninja as a generator on Windows, to workaround  https://github.com/dic-iit/bipedal-locomotion-framework/issues/382 . As the ninja MSVC generator only works on Command Prompt, we also switched the relevant steps to run on Command Prompt as well.
> Enable Python bindings in conda-forge CI and fix Python bindings compilation and tests on MSVC

- .github/workflows/ci.yml
- CHANGELOG.md
- src/ParametersHandler/TomlImplementation/include/BipedalLocomotion/ParametersHandler/TomlImplementation.h
- src/ParametersHandler/TomlImplementation/src/TomlImplementation.cpp
- src/ParametersHandler/YarpImplementation/src/YarpImplementation.cpp
- src/ParametersHandler/tests/ParametersHandlerTomlTest.cpp
This fixes the problem spotted by @traversaro in #381. 
It implements what is explained in https://github.com/dic-iit/bipedal-locomotion-framework/pull/381#issuecomment-896756059
> Fix the `TOML` and `YARP` implementation of the parameters handler when a `std::vector<bool>` is passed to the `setParameter()` 

- .github/workflows/conda-forge-ci.yml
See https://github.com/conda-forge/staged-recipes/pull/14921 for the PR that added the tomlplusplus package to conda-forge.
> conda-forge-ci: Use tomlplusplus conda package

- CHANGELOG.md
- src/Contacts/include/BipedalLocomotion/Contacts/ContactPhase.h
- src/Contacts/include/BipedalLocomotion/Contacts/ContactPhaseList.h
- src/Contacts/src/ContactPhaseList.cpp
- src/Contacts/tests/Contacts/ContactPhaseListTest.cpp
This PR implements the `ContactPhaseList::getPresentPhase()` method. The implementation is higly inspired by `ContactList::getPresentContact()`
https://github.com/dic-iit/bipedal-locomotion-framework/blob/d847912014baa5e4348d7b74965601afdaa63c2a/src/Contacts/src/ContactList.cpp#L211-L223
I also updated the test adding the new feature.
> Implement `ContactPhaseList::getPresentPhase()` method

- CHANGELOG.md
- src/System/CMakeLists.txt
- src/System/include/BipedalLocomotion/System/AdvanceableRunner.h
- src/System/include/BipedalLocomotion/System/Barrier.h
- src/System/src/Barrier.cpp
- src/System/tests/AdvanceableRunnerTest.cpp
This PR introduces a synchronization mechanism for the `AdvanceableRunner` class.  The `Barrier` class has been developed,  the code was taken from [here](https://stackoverflow.com/questions/24465533/implementing-boostbarrier-in-c11).
c++20 introduces the barrier class however since this repo is based on c++17, the implementation of this new class was required. `Barrier` is then used in the `run` method of the advanceable runner to synchronize the startup of all the threads.
> Add a synchronization mechanism for the AdvanceableRunner

- CHANGELOG.md
- src/System/include/BipedalLocomotion/System/AdvanceableRunner.h
- src/System/tests/AdvanceableRunnerTest.cpp
Now the name of the AdvanceableRunner must be specified in the initialization
> Add `name` parameter to the `AdvanceableRunner` class

- CHANGELOG.md
- src/TextLogging/CMakeLists.txt
- src/TextLogging/YarpImplementation/CMakeLists.txt
- src/TextLogging/YarpImplementation/include/BipedalLocomotion/TextLogging/YarpLogger.h
- src/TextLogging/YarpImplementation/src/YarpLogger.cpp
- src/TextLogging/include/BipedalLocomotion/TextLogging/DefaultLogger.h
- src/TextLogging/include/BipedalLocomotion/TextLogging/Logger.h
- src/TextLogging/include/BipedalLocomotion/TextLogging/LoggerBuilder.h
- src/TextLogging/src/DefaultLogger.cpp
- src/TextLogging/src/Logger.cpp
- src/TextLogging/src/LoggerBuilder.cpp
This PR closes https://github.com/ami-iit/bipedal-locomotion-framework/issues/407. In detail, I implemented a custom sink to handle the logging through yarp. 
The switching between the normal logging to the `yarp` one is pretty simple and has been implemented using the factory pattern.
```cpp
#include <BipedalLocomotion/TextLogging/Logger.h>
#include <BipedalLocomotion/TextLogging/YarpLogger.h>
#include <BipedalLocomotion/TextLogging/LoggerBuilder.h>
// Change the logger
BipedalLocomotion::TextLogging::LoggerBuilder::setFactory(std::make_shared<BipedalLocomotion::TextLogging::YarpLoggerFactory>()));
BipedalLocomotion::log()->info("My info");
```
will print
```
[INFO] [2021-09-02 23:20:43.501] [thread: 108475] [blf] My info
```
using `yInfo()`
Thanks to this feature all the applications …
> Add the possibility to use spdlog with YARP

- .github/workflows/ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
This should fix what @S-Dafarra and @isorrentino spotted in https://github.com/ami-iit/bipedal-locomotion-framework/issues/413
> Fix dependencies issues in the cmake machinery

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
- .gitignore
- CHANGELOG.md
- bindings/python/Contacts/src/Contacts.cpp
- bindings/python/Planners/CMakeLists.txt
- bindings/python/Planners/include/BipedalLocomotion/bindings/Planners/UnicyclePlanner.h
- bindings/python/Planners/src/Module.cpp
- bindings/python/Planners/src/UnicyclePlanner.cpp
- bindings/python/Planners/tests/test_unicycle_planner.py
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/Planners/CMakeLists.txt
- src/Planners/include/BipedalLocomotion/Planners/UnicyclePlanner.h
- src/Planners/src/UnicyclePlanner.cpp
- src/System/include/BipedalLocomotion/System/Advanceable.h
This PR is the first step towards including in BLF the unicycle planner currently stored in [robotology/unicycle-footstep-planner](https://github.com/robotology/unicycle-footstep-planner).
In order to simplify the review process, I split the porting in two steps:
1. This PR calls the existing `UnicyclePlanner` from the external repository and defines a new Advanceable with its own parameter handler, input, state, and Python bindings (and tests).
2. Once the first step (this PR) is finalized, I can start vendoring the external `UnicyclePlanner` files and perform a small refactoring. I try to minimize the changes to parameters, inputs, and outputs wrt to this PR.
Open questions:
- The [`::FootPrint`](https://github.com/robotology/unicycle-footstep-planner/blob/master/include/FootPrint.h) …
> Add new Advanceable exposing `UnicyclePlanner`

- CHANGELOG.md
- bindings/python/Contacts/src/Contacts.cpp
- src/Math/include/BipedalLocomotion/Math/Wrench.h
This PR introduces the python bindings for the `ContactWrench`. To correctly convert the `Wrenchd` class into a `numpy` object I had to inherits all the `Eigen::Matrix` constructors in the `Wrenchd` class 7ba03bbfac7d115e271c884d0dc2ca32f9a10ab5 .
Without this `pybind11` was complaining with the following error.
```
[ 75%] Building CXX object bindings/python/CMakeFiles/pybind11_blf.dir/Contacts/src/Contacts.cpp.o
In file included from /home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/bindings/python/Contacts/src/Contacts.cpp:8:
/usr/include/pybind11/eigen.h: In instantiation of ‘bool pybind11::detail::type_caster<Type, typename std::enable_if<std::integral_constant<bool, (pybind11::detail::negation<std::integral_constant<bool, (decltype …
```
> Implement ContactWrench python bindings

- CHANGELOG.md
- bindings/python/IK/CMakeLists.txt
- bindings/python/IK/include/BipedalLocomotion/bindings/IK/AngularMomentumTask.h
- bindings/python/IK/src/AngularMomentumTask.cpp
- bindings/python/IK/src/Module.cpp
- bindings/python/IK/tests/test_QP_inverse_kinematics.py
- src/IK/CMakeLists.txt
- src/IK/include/BipedalLocomotion/IK/AngularMomentumTask.h
- src/IK/src/AngularMomentumTask.cpp
- src/IK/tests/AngularMomentumTaskTest.cpp
- src/IK/tests/CMakeLists.txt
This task can be used to control a desired angular momentum in the IK.
This can be useful to generate a swing motion of the arms when the robot is position control
> Implement AngularMomentum task in the IK component

- CHANGELOG.md
- bindings/python/IK/src/SE3Task.cpp
- bindings/python/System/CMakeLists.txt
- bindings/python/System/include/BipedalLocomotion/bindings/System/ITaskControllerManager.h
- bindings/python/System/src/ITaskControllerManager.cpp
- bindings/python/System/src/Module.cpp
- bindings/python/TSID/src/SE3Task.cpp
- src/IK/include/BipedalLocomotion/IK/SE3Task.h
- src/TSID/include/BipedalLocomotion/TSID/SE3Task.h
- src/TSID/src/SE3Task.cpp
This PR introduces the possibility to set the task controller mode for the SE3Task in the tsid component. This feature was already implemented for the IK
I also add the possibility to set the mode in python
> Add the possibility to set the task controller mode for the SE3Task in the TSID component and update the python bindings

- bindings/python/utils.py
- docs/pages/python-additional-info.md
- src/IK/src/QPInverseKinematics.cpp
In the original implementation of the `create_ik` function, I forgot to add 
```python
assert solver.initialize(param_handler.get_group("IK"))
```
this PR fixes the bug and I updated the associated documentation.
Furthermore the `QPInverseKinematics::finalize()` checks if the IK is initialized.
Associated issue: https://github.com/ami-iit/bipedal-locomotion-framework/issues/464
> Fix `create_ik` python function

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/interface/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
This modification follows from the possibility to log also the orientation from the IMU on the head of iCub3 (https://github.com/ami-iit/robots-configuration/commit/4f3ce7f8197cadf849319d18aa860600a2b36afa).
> Add logging of IMU orientation for iCub3

- CHANGELOG.md
- bindings/python/IK/src/IntegrationBasedIK.cpp
- bindings/python/TSID/src/TaskSpaceInverseDynamics.cpp
- src/IK/include/BipedalLocomotion/IK/QPInverseKinematics.h
- src/IK/src/QPInverseKinematics.cpp
- src/IK/tests/QPInverseKinematicsTest.cpp
- src/System/include/BipedalLocomotion/System/ILinearTaskSolver.h
- src/TSID/include/BipedalLocomotion/TSID/QPTSID.h
- src/TSID/src/QPTSID.cpp
- src/TSID/tests/QPFixedBaseTSIDTest.cpp
> Add the possibility to change the weight in TSID/IK

- CHANGELOG.md
- src/ContinuousDynamicalSystem/CMakeLists.txt
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/FirstOrderSmoother.h
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/FixedStepIntegrator.h
- src/ContinuousDynamicalSystem/src/FirstOrderSmoother.cpp
- src/ContinuousDynamicalSystem/tests/CMakeLists.txt
- src/ContinuousDynamicalSystem/tests/FirstOrderSmoother.cpp
- src/System/include/BipedalLocomotion/System/Advanceable.h
This can be used to perform gain-scheduling as explained in https://github.com/ami-iit/bipedal-locomotion-framework/issues/474
This is the last block missing to use the blf IK in the walking module
> Implement a first order smoother

- CHANGELOG.md
- bindings/python/IK/src/IKLinearTask.cpp
- bindings/python/IK/tests/test_QP_inverse_kinematics.py
- bindings/python/System/include/BipedalLocomotion/bindings/System/LinearTask.h
- bindings/python/System/src/LinearTask.cpp
- bindings/python/TSID/src/TSIDLinearTask.cpp
- bindings/python/TSID/tests/test_TSID.py
- docs/pages/python-additional-info.md
- src/IK/include/BipedalLocomotion/IK/IKLinearTask.h
- src/System/include/BipedalLocomotion/System/ITaskControllerManager.h
- src/System/include/BipedalLocomotion/System/LinearTask.h
- src/System/include/BipedalLocomotion/System/Sink.h
- src/System/include/BipedalLocomotion/System/Source.h
- src/TSID/include/BipedalLocomotion/TSID/TSIDLinearTask.h
If you are a `python` user and you want to create inverse kinematics (IK) or a task-based inverse
dynamics (TSID) task, you do need to write a `C++` code. Indeed it is possible to write a class that inherits from `TSIDLinearTask` or `IKLinearTask`  and passes it to `tsid` or `ik` solvers. The following snippet can be used as starting point to build a custom TSID task, a similar approach can be used to define a custom IK task
```py
import bipedal_locomotion_framework.bindings as blf
class CustomTSIDTask(blf.tsid.TSIDLinearTask):
""" CustomTSIDTask represents a custom task for the tsid solver.
The class must define the following functions:
__init__(self): the constructor
size(self) -> Get the size of the task. (I.e the number of rows of the vector b)
is_valid(self) -> Determines the …
```
> Add the possibility to create custom LinearTasks in python

- CHANGELOG.md
- bindings/python/Contacts/src/ContactDetectors.cpp
- bindings/python/FloatingBaseEstimators/src/FloatingBaseEstimators.cpp
- bindings/python/IK/src/IntegrationBasedIK.cpp
- bindings/python/Planners/src/DCMPlanner.cpp
- bindings/python/Planners/src/SwingFootPlanner.cpp
- bindings/python/Planners/src/TimeVaryingDCMPlanner.cpp
- bindings/python/Planners/src/UnicyclePlanner.cpp
- bindings/python/System/include/BipedalLocomotion/bindings/System/Advanceable.h
- bindings/python/TSID/src/QPTSID.cpp
- bindings/python/TSID/src/TaskSpaceInverseDynamics.cpp
This PR restructure the implementation of the bindings. In the long run, it should reduce the line of code required to add a new advanceable. 
Nothing change in the usage of the bindings
> Reduce code duplication in python bindings

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
With this PR I removed all the `yarp` command to stream text logging info. And I replaced it with `spdlog`. All the messages are however visible on the `yarplogger` thanks to the custom sink I developed in #407
> Use TextLogger in YarpRobotLoggerDevice

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/README.md
The documentation for the `YarpRobotLoggerDevice` was not up-to-date, I have replaced it with a more general one with all the new features.
I have also noticed currently, as far as I see, the devices are not mentioned in the main `README.md`. Not sure if that's because they are still not stable, or it is simply missing.
cc @isorrentino
> Update YarpRobotLoggerDevice documentation

- .github/workflows/ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/IK/src/QPInverseKinematics.cpp
- src/TSID/src/QPTSID.cpp
With this PR, `osqp-eigen 0.6.4.100` is required to compile the IK and TSID components. Thanks to this modification it is now possible to get the optimal solution from the solver even if it is not accurate.
> Ask for osqp-eigen 0.6.4.100

- CHANGELOG.md
- src/TextLogging/include/BipedalLocomotion/TextLogging/Logger.h
- src/TextLogging/src/Logger.cpp
This should fix https://github.com/ami-iit/bipedal-locomotion-framework/pull/492#issuecomment-1008736884
> Use enum underlying type to convert TextLogging verbosity level to spdlog verbosity level

- .github/workflows/ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- cmake/valgrind-linux.supp
- src/YarpUtilities/include/BipedalLocomotion/YarpUtilities/Helper.tpp
- src/YarpUtilities/src/Helper.cpp
- src/YarpUtilities/tests/YarpUtilitiesTest.cpp
[`Yarp 3.5.0`](https://github.com/robotology/yarp/releases/tag/v3.5.0) has been released a while ago. This PR modifies the code `YarpUtilities` component to substitute the deprecated methods in favour of new methods
- `isInt()` is deprecated in favour of `isInt32()`
- `isDouble()` is deprecated in favour of `isFloat64()`
- `asInt()` is deprecated in favour of `asInt32()`
- `asDouble()` is deprecated in favour of `asFloat64()`
> Fix deprecated `YARP` functions in `YarpUtilities` component

- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/System/CMakeLists.txt
- bindings/python/System/include/BipedalLocomotion/bindings/System/Clock.h
- bindings/python/System/include/BipedalLocomotion/bindings/System/IClock.h
- bindings/python/System/include/BipedalLocomotion/bindings/System/Module.h
- bindings/python/System/include/BipedalLocomotion/bindings/System/YarpClock.h
- bindings/python/System/include/BipedalLocomotion/bindings/System/YarpModule.h
- bindings/python/System/src/Clock.cpp
- bindings/python/System/src/IClock.cpp
- bindings/python/System/src/Module.cpp
- bindings/python/System/src/YarpClock.cpp
- bindings/python/System/src/YarpModule.cpp
- bindings/python/bipedal_locomotion_framework.cpp.in
- src/System/include/BipedalLocomotion/System/Clock.h
- src/System/src/Clock.cpp
This PR implements:
1. The python bindings for the Clock machinery and for the yarp clock
Furthermore, since the clock is implemented as a singleton, an error it will be returned if the user tries to change the clock type once the `clock()` has been already called once. Notice that `BipedalLocomotion::clock()` instantiate the singleton the first time is called (See Meyers' singleton implementation).
For instance, in python, we will have 
```
In [1]: import bipedal_locomotion_framework.bindings as blf
In [2]: blf.clock().now()
Out[2]: datetime.timedelta(days=19010, seconds=63353, microseconds=503687)
In [3]: blf.system.ClockBuilder.set_factory(blf.system.YarpClockFactory())
[2022-01-18 18:35:55.945] [thread: 66773] [blf] [error] [ClockBuilder::setFactory] The clock has been already called. …
```
> Implement python bindings for the classes that handle the clock

- CHANGELOG.md
- bindings/python/System/CMakeLists.txt
- bindings/python/System/include/BipedalLocomotion/bindings/System/ILinearTaskSolver.h
- bindings/python/System/include/BipedalLocomotion/bindings/System/WeightProvider.h
- bindings/python/System/src/Module.cpp
- bindings/python/System/src/WeightProvider.cpp
- src/IK/include/BipedalLocomotion/IK/QPInverseKinematics.h
- src/IK/src/QPInverseKinematics.cpp
- src/IK/tests/QPInverseKinematicsTest.cpp
- src/System/CMakeLists.txt
- src/System/include/BipedalLocomotion/System/ConstantWeightProvider.h
- src/System/include/BipedalLocomotion/System/ILinearTaskSolver.h
- src/System/include/BipedalLocomotion/System/IWeightProvider.h
- src/System/src/ConstantWeightProvider.cpp
- src/TSID/include/BipedalLocomotion/TSID/QPTSID.h
- src/TSID/src/QPTSID.cpp
- src/TSID/tests/QPFixedBaseTSIDTest.cpp
Thanks to this PR it will be possible to define different providers for the weight in the Ik and TSID. As a consequence, it will be possible to implement a provider that allows performing weight scheduling.
The associated python bindings have been updated accordingly.
> Introduce the IWeightProvider and the ConstantWeightProvider

- CHANGELOG.md
- bindings/CMakeLists.txt
See https://github.com/robotology/robotology-superbuild/issues/1012 for a discussion of the problem. This is not particularly problematic for blf as blf is not on PyPI, but anyhow seeing the output of `pip list --verbose` with `cmake` as a tool (see https://github.com/robotology/robotology-superbuild/issues/1012#issuecomment-1032880753) is always cool. :D
> Add installation of pip metadata files for when blf python bindings are installed only via CMake

- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/YarpUtilities/CMakeLists.txt
- bindings/python/YarpUtilities/include/BipedalLocomotion/bindings/YarpUtilities/BufferedPort.h
- bindings/python/YarpUtilities/include/BipedalLocomotion/bindings/YarpUtilities/Module.h
- bindings/python/YarpUtilities/include/BipedalLocomotion/bindings/YarpUtilities/VectorsCollection.h
- bindings/python/YarpUtilities/src/Module.cpp
- bindings/python/YarpUtilities/src/VectorsCollection.cpp
- bindings/python/bipedal_locomotion_framework.cpp.in
- cmake/BipedalLocomotionFrameworkDependencies.cmake
Thanks to this PR it is possible to use the `VectorsCollection` message also in python. As a consequence, a python process can log data in the [`YarpRobotLoggerDevice`](https://github.com/ami-iit/bipedal-locomotion-framework/tree/master/devices/YarpRobotLoggerDevice).
This is a minimum python example (you should run `yarpserver`)
```python
import bipedal_locomotion_framework.bindings as blf
import yarp
network = yarp.Network()
network.init()
port = blf.yarp_utilities.BufferedPortVectorsCollection()
port.open("/foo")
data = port.prepare()
data.vectors = {"v1": [1, 2, 3.4], "v2": [12, 3, 2, 4, 3]}
port.write()
port.close()
```
⚠️ : It is not possible to modify directly the content of `data.vectors`. Indeed trying to add an entity to the dictionary does not work
```python
>>> …
```
> Implement the python bindings for the VectorsCollection message and the associated buffered port

- bindings/CMakeLists.txt
As reported in https://github.com/conda-forge/opencv-feedstock/issues/302, `\n\r` do not represent a single newline in Windows (even as in that case it would be `\r\n`). Anyhow, `\n` seems to be working fine, so let's just use that one.
> Always use \n as new line when generating files with CMake

- CHANGELOG.md
- src/Perception/src/ArucoDetector.cpp
This should permit to compile without problems on OpenCV 4.6.0 .
> ArucoDetector: Avoid to use deprecated function aruco::drawAxis

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- devices/YarpRobotLoggerDevice/CMakeLists.txt
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
`robometry` is the new name of `YARP_telemetry`, see https://github.com/robotology/robometry/pull/173
please review code
> YarpLoggerDevice: ported to robometry

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
> Fix the dependency required to compile the YarpRobotLogger device

- .github/workflows/ci.yml
- CHANGELOG.md
- src/TextLogging/CMakeLists.txt
- src/TextLogging/include/BipedalLocomotion/TextLogging/Logger.h
If `spdlog` uses a system-wide installation of `fmt` and the `fmt` version is at least 9.0.0, the current implementation of the logger does not work with eigen object. 
This caused the homebrew CI failure https://github.com/robotology/robotology-superbuild/issues/1234
This PR implements what is suggested in https://fmt.dev/latest/api.html#std-ostream-support for `Dense` and `Transpose` eigen matrices. Additional `formatter` could be defined in the future if required. 
Once this PR is merged it will be possible to reactivate the compilation of blf in the macOS CI of the superbuild.
> Fix the compatibility with fmt v9.0.0

- CHANGELOG.md
- bindings/python/IK/CMakeLists.txt
- bindings/python/IK/include/BipedalLocomotion/bindings/IK/R3Task.h
- bindings/python/IK/src/R3Task.cpp
- src/IK/CMakeLists.txt
- src/IK/include/BipedalLocomotion/IK/R3Task.h
- src/IK/src/R3Task.cpp
- src/IK/tests/CMakeLists.txt
- src/IK/tests/R3TaskTest.cpp
This task can be used to stabilize the desired frame position. As the `CoMTask` and the `SE3Task` the user can pass a mask to deactivate some directions.
For instance `mask = [false, false, true]` will enable the controller only on the z-coordinate. 
The PR implements also the associated bindings @paolo-viceconte @RiccardoZuppetti
> Implement the IK::R3Task

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
Back in time, we (@S-Dafarra and I) noticed that storing the text with the logger is time-consuming. This PR gives the user the possibility to log only a subset of text logging ports by specifying substrings that need to be contained in the port name. 
If one of those substrings is found then the port is logged.
In order to do so, I introduced `text_logging_subnames` parameter. This parameter is optional. If not passed all the logs are saved
This is an example of configuration
```ini
text_logging_subnames    ("icub-head/yarprobotinterface", "walking-module")
```
> Add the possibility to log only a subset of text logging ports

- CHANGELOG.md
- bindings/python/RobotInterface/src/Polydriver.cpp
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpHelper.h
- src/RobotInterface/YarpImplementation/src/YarpHelper.cpp
This PR implements `RobotInterface::constructMultipleAnalogSensorsClient()` and `RobotInterface::constructMultipleAnalogsensorsRemapper()` function (and the associated bindings). These two methods allows the user to easily construct a multipleanalogsensorclient and `multipleanalogsensorremapper` from a set of configuration
The following example can be used as starting point to build the two polydrivers. 
```cpp
#include <BipedalLocomotion/RobotInterface/YarpHelper.h>
#include <BipedalLocomotion/ParametersHandler/YarpImplementation.h>
#include <yarp/os/ResourceFinder.h>
#include <memory>
int main(int argc, char *argv[])
{
yarp::os::ResourceFinder &rf = yarp::os::ResourceFinder::getResourceFinderSingleton();
rf.setDefaultConfigFile("config.ini");
rf.configure(argc - 1, argv);
auto handler = …
```
> Implement constructMultipleAnalogSensorsClient and constructMultipleAnalogSensorsRemapper functions

- CHANGELOG.md
- CMakeLists.txt
- cmake/AddBipedalLocomotionYARPDevice.cmake
- devices/YarpRobotLoggerDevice/CMakeLists.txt
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
Thanks to this PR every time a matfile is saved by the `YarpRobotLoggerDevice`, the device will also save a `md` file containing the status of the system. For the time being the output of 
```console
bash ${ROBOTOLOGY_SUPERBUILD_SOURCE_DIR}/scripts/robotologyGitStatus.sh
```
and
```console
apt list --installed
```
I also added a parameter called `code_status_cmd_prefixes` that can be sued to add a prefix to the previous two commands, for instance 
```xml
<param name="code_status_cmd_prefixes">("ssh icub@10.0.0.2")</param>
```
will call the commands on `icub-head`
Thanks to this it will be possible to reconstruct the experiment from a given dataset
> Log the status of the system with tiny-process-library

- CHANGELOG.md
- cmake/AddBipedalLocomotionYARPDevice.cmake
It is quite counterintuitive that beside enabling the YARP-specific option, some more options need to be enabled to actually compile YARP devices.
See also https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/issues/5 .
> AddBipedalLocomotionYARPDevice: Enable YARP devices by deafult

- CHANGELOG.md
- devices/FloatingBaseEstimatorDevice/include/BipedalLocomotion/FloatingBaseEstimatorDevice.h
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
The header was deprecated since YARP 3.3.0 (see https://github.com/robotology/yarp/blob/v3.3.0/doc/release/v3_3_0.md?plain=1#L80) and wille be removed in YARP 3.8 .
Fix part of https://github.com/robotology/robotology-superbuild/issues/1307 .
> Remove use of deprecated include yarp/dev/Wrapper.h

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/System/CMakeLists.txt
- bindings/python/System/include/BipedalLocomotion/bindings/System/RosClock.h
- bindings/python/System/include/BipedalLocomotion/bindings/System/RosModule.h
- bindings/python/System/src/RosClock.cpp
- bindings/python/System/src/RosModule.cpp
- bindings/python/bipedal_locomotion_framework.cpp.in
- cmake/AddUninstallTarget.cmake
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/System/CMakeLists.txt
- src/System/RosImplementation/CMakeLists.txt
- src/System/RosImplementation/include/BipedalLocomotion/System/RosClock.h
- src/System/RosImplementation/src/RosClock.cpp
This PR develops the ROS2 implementation for the Clock class in the system component. This PR uses plain `CMake` instead of `ament_cmake` (provided by ROS2). The required ROS version is [humble](https://docs.ros.org/en/humble/index.html).
The clock can be used as follows:
1. In c++
```cpp
#include <BipedalLocomotion/System/RosClock.h>
#include <BipedalLocomotion/System/Clock.h>
#include <chrono>
#include <memory>
using namespace std::chrono_literals;
int main(int argc, char *argv[])
{
BipedalLocomotion::System::ClockBuilder::setFactory(std::make_shared<BipedalLocomotion::System::RosClockFactory>(argc, argv));
BipedalLocomotion::clock().sleepFor(2000ms);
return 0;
}
```
2. In python
```python
import bipedal_locomotion_framework as blf
import sys
import datetime …
```
> Design the ROS2 implementation for Clock class

- CHANGELOG.md
- src/IK/src/SE3Task.cpp
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpHelper.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpHelper.cpp
This PR:
- fixes a bug `MultipleAnalogSensorsRemapper` 97f204ed9080ba80fc9aaa749ecfd0cb76fb1e2f
- Add the possibility to attach all the multiple analog sensor clients
- Add informative prints `YarpSensorBridge::Impl`
> Improvements on the `MultipleAnalogSensorsRemapper` handling in the framework

- src/TextLogging/YarpImplementation/include/BipedalLocomotion/TextLogging/YarpLogger.h
- src/TextLogging/YarpImplementation/src/YarpLogger.cpp
- src/TextLogging/include/BipedalLocomotion/TextLogging/DefaultLogger.h
- src/TextLogging/src/DefaultLogger.cpp
When using the implemented Logger Factories, the logger's name (currently `blf`) is displayed in the formatted message -  see [here](https://github.com/ami-iit/bipedal-locomotion-framework/blob/6747c2dfb0f3fc3f1feeb94ad911095ccb356780/src/TextLogging/YarpImplementation/src/YarpLogger.cpp#L42) for a reference (where `%n` is the name of the logger).
Users may not want to use `blf`, so this PR to allow the usage of a custom name for the implemented loggers of the TextLogging component.
The changes do not break the current API since the default name `blf` is provided as default value.
> [TextLogging] Allow custom logger name

- CHANGELOG.md
- src/Estimators/CMakeLists.txt
- src/Estimators/tests/FloatingBaseEstimators/CMakeLists.txt
There were this warnings:
~~~
CMake Warning (dev) at cmake/AddBipedalLocomotionLibrary.cmake:73 (target_link_libraries):
The library that is being linked to, iDynTree::idyntree-modelio-urdf, is
marked as being deprecated by the owner.  The message provided by the
developer is:
Do not use deprecated target iDynTree::idyntree-modelio-urdf, use
iDynTree::idyntree-modelio instead.
Call Stack (most recent call first):
src/Estimators/CMakeLists.txt:17 (add_bipedal_locomotion_library)
This warning is for project developers.  Use -Wno-dev to suppress it.
~~~
These were introduced in iDynTree 4.3.0, I think it is safe to use the new target.
> Fix iDynTree 4.3.0 deprecations

- .github/workflows/conda-forge-ci.yml
Currently the CI is failing on Linux and Windows with a weird conflict error. This is due to the fact that we are install mamba (from the conda-forge channel) on the top of miniconda3 (that by default install all the packages from the defaults channel). To make an analogy in apt world, this is like installing Debian, and then trying to install packages from the Ubuntu repo: something can go wrong.
To solve this problem, we install [mambaforge](https://github.com/conda-forge/miniforge) (a installer like miniconda3 but already using conda-forge packages) directly, so we always and only use packages from the conda-forge channel. 
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/592 .
Similar to:
* https://github.com/robotology/robotology-superbuild/pull/840
* …
> Fix conda-ci GitHub Action CI by using mambaforge directly

- CHANGELOG.md
- src/Perception/src/ArucoDetector.cpp
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/586 .
> Fix compatibility with OpenCV 4.7.0

- src/System/src/QuitHandler.cpp
As per title, this PR is to check if the OS is Windows using the preprocessing flag `_WIN32`.
Currently, the only file checking for windows is the one addressed by this PR, and it checks the OS using `WIN32`.
According to many discussions (e.g. [here](https://stackoverflow.com/questions/142508/how-do-i-check-os-with-a-preprocessor-directive) or [here](https://stackoverflow.com/questions/2989810/which-cross-platform-preprocessor-defines-win32-or-win32-or-win32)) or even on [Microsoft's documentation](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170), `_WIN32` is the flag that should be used.
> Use _WIN32 to check windows OS

- CHANGELOG.md
- bindings/python/TextLogging/CMakeLists.txt
- bindings/python/TextLogging/include/BipedalLocomotion/bindings/TextLogging/RosLogger.h
- bindings/python/TextLogging/include/BipedalLocomotion/bindings/TextLogging/RosModule.h
- bindings/python/TextLogging/include/BipedalLocomotion/bindings/TextLogging/TextLogging.h
- bindings/python/TextLogging/src/RosLogger.cpp
- bindings/python/TextLogging/src/RosModule.cpp
- bindings/python/TextLogging/src/TextLogging.cpp
- bindings/python/bipedal_locomotion_framework.cpp.in
- src/TextLogging/CMakeLists.txt
- src/TextLogging/RosImplementation/CMakeLists.txt
- src/TextLogging/RosImplementation/include/BipedalLocomotion/TextLogging/RosLogger.h
- src/TextLogging/RosImplementation/src/RosLogger.cpp
- src/TextLogging/YarpImplementation/include/BipedalLocomotion/TextLogging/YarpLogger.h
- src/TextLogging/YarpImplementation/src/YarpLogger.cpp
- src/TextLogging/include/BipedalLocomotion/TextLogging/DefaultLogger.h
- src/TextLogging/include/BipedalLocomotion/TextLogging/Logger.h
- src/TextLogging/include/BipedalLocomotion/TextLogging/LoggerBuilder.h
- src/TextLogging/src/DefaultLogger.cpp
- src/TextLogging/src/Logger.cpp
This  PR will allow using the ros2 text logging mechanism within blf framework. Moreover, it also exposes the blf logging capabilities in the python bindings
cc @traversaro
> Implement the ROS2 sink for the TextLogging

- CHANGELOG.md
- bindings/python/IK/src/QPInverseKinematics.cpp
- bindings/python/TSID/src/QPTSID.cpp
- src/IK/CMakeLists.txt
- src/IK/include/BipedalLocomotion/IK/QPFixedBaseInverseKinematics.h
- src/IK/include/BipedalLocomotion/IK/QPInverseKinematics.h
- src/IK/src/QPFixedBaseInverseKinematics.cpp
- src/IK/tests/CMakeLists.txt
- src/IK/tests/QPFixedBaseInverseKinematicsTest.cpp
This PR implements:
- `QPFixedBaseInverseKinematics` and the associated python bindings
- Improve the documentation of the `QPInverseKinematics`
- Allow using the iDynTree swig bindings in `QPFixedBaseTSID` for the kindyncomputation object https://github.com/ami-iit/bipedal-locomotion-framework/commit/85dc4fe9b95908035d44a9c91e3879ddbfb403f8
This PR closes #598
> Implement QPFixedBaseInverseKinematics class

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
As per title, this should give the user the possibility to set different video codecs in for the yarpRobotLoggerDevice 
Here a list of different codecs https://softron.zendesk.com/hc/en-us/articles/207695697-List-of-FourCC-codes-for-video-codecs
> Add the possibility to customize the video codec in the YarpRobotLoggerDevice

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
This fix is required when the the YarpSensorBridge is attached to a list of polydriver and the remote control board remapper is not the first one.
> Fix attachRemappedRemoteControlBoard in YarpSensorBridge

- CHANGELOG.md
- bindings/python/Conversions/CMakeLists.txt
- bindings/python/Conversions/src/ManifConversions.cpp
- bindings/python/Conversions/tests/test_manif_conversions.py
With this PR it will be possible to write the following code in python
```py
import idyntree.swig as idyn
import bipedal_locomotion_framework as blf
rot_idyn = idyn.Rotation.Identity()
trans_idyn = idyn.Transform.Identity()
so3 = blf.conversions.to_manif_rot(rot_idyn)
se3 = blf.conversions.to_manif_pose(trans_idyn)
```
> Implement the python bindings for the iDynTree to manif conversions

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/SubModelKinDynWrapper.h
- src/Estimators/src/SubModelKinDynWrapper.cpp
- src/Estimators/tests/RobotDynamicsEstimator/CMakeLists.txt
- src/Estimators/tests/RobotDynamicsEstimator/SubModelKinDynWrapperTest.cpp
Adding the `SubModelKinDynWrapper` class. It handles the `KinDynComputation` object of a sub-model and keeps updated the dynamics and kinematics information.
This PR is blocked by #604.
> Add SubModelKinDynWrapper class

- CHANGELOG.md
- bindings/python/IK/CMakeLists.txt
- bindings/python/IK/include/BipedalLocomotion/bindings/IK/JointLimitsTask.h
- bindings/python/IK/src/JointLimitsTask.cpp
- bindings/python/IK/src/Module.cpp
- bindings/python/IK/tests/test_QP_inverse_kinematics.py
- src/IK/CMakeLists.txt
- src/IK/include/BipedalLocomotion/IK/JointLimitsTask.h
- src/IK/src/JointLimitsTask.cpp
- src/IK/tests/CMakeLists.txt
- src/IK/tests/JointLimitsTaskTest.cpp
- src/IK/tests/QPInverseKinematicsTest.cpp
This closes #530 
cc @shikui08
> Implement the JointLimitsTask for the IK

- CHANGELOG.md
- src/System/include/BipedalLocomotion/System/Clock.h
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/617 .
> Fix race condition in System::ClockBuilder

- CHANGELOG.md
- bindings/python/IK/src/CoMTask.cpp
- bindings/python/IK/src/IKLinearTask.cpp
- bindings/python/IK/src/JointLimitsTask.cpp
- bindings/python/IK/src/JointTrackingTask.cpp
- bindings/python/IK/src/QPInverseKinematics.cpp
- bindings/python/IK/src/R3Task.cpp
- bindings/python/IK/src/SE3Task.cpp
- bindings/python/IK/src/SO3Task.cpp
- bindings/python/System/include/BipedalLocomotion/bindings/System/ILinearTaskSolver.h
- bindings/python/utils.py
- src/IK/CMakeLists.txt
- src/IK/include/BipedalLocomotion/IK/AngularMomentumTask.h
- src/IK/include/BipedalLocomotion/IK/CoMTask.h
- src/IK/include/BipedalLocomotion/IK/IKLinearTask.h
- src/IK/include/BipedalLocomotion/IK/JointLimitsTask.h
- src/IK/include/BipedalLocomotion/IK/JointTrackingTask.h
- src/IK/include/BipedalLocomotion/IK/QPInverseKinematics.h
- src/IK/include/BipedalLocomotion/IK/R3Task.h
- src/IK/include/BipedalLocomotion/IK/SE3Task.h
- src/IK/include/BipedalLocomotion/IK/SO3Task.h
- src/IK/src/IKLinearTask.cpp
- src/IK/src/JointLimitsTask.cpp
- src/IK/src/QPInverseKinematics.cpp
- src/IK/tests/QPInverseKinematicsTest.cpp
- src/System/CMakeLists.txt
- src/System/include/BipedalLocomotion/System/ILinearTaskFactory.h
This PR adds the possibility to build an IK problem directly from a configuration file.
This means that the if the user provides a suitable config file (an example is added in the documentation), all the tasks are automatically built and the `QPInverseKinematics` is finalized.
The only thing the user has to do is to provide the setpoints for the tasks.
This is achieved by following
```cpp
auto [variableHandler, solver] = BipedalLocomotion::IK::QPInverseKinematics::build(paramHandler, kinDyn)
```
where `paramHandler` is a `std::weak_ptr<IParameterHandler>` and `kinDyn` is a `std::shared_ptr<iDynTree::KinDynComputations>`.
This feature is implemented by using the factory design pattern. After declaring a new task, the user must call the following macro
```cpp
BLF_REGISTER_IK_TASK(TaskType); …
```
> Add the possibility to programmatically build an IK problem from a configuration file 

- CHANGELOG.md
- bindings/python/IK/src/IntegrationBasedIK.cpp
- bindings/python/IK/src/QPInverseKinematics.cpp
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/MultiStateWeightProvider.h
- src/IK/CMakeLists.txt
- src/IK/include/BipedalLocomotion/IK/IntegrationBasedIK.h
- src/IK/include/BipedalLocomotion/IK/QPInverseKinematics.h
- src/IK/src/IntegrationBasedIK.cpp
- src/IK/src/QPInverseKinematics.cpp
- src/IK/tests/QPInverseKinematicsTest.cpp
- src/System/CMakeLists.txt
- src/System/include/BipedalLocomotion/System/ConstantWeightProvider.h
- src/System/include/BipedalLocomotion/System/Factory.h
- src/System/include/BipedalLocomotion/System/ILinearTaskFactory.h
- src/System/include/BipedalLocomotion/System/WeightProvider.h
This PR complements #614, in detail, it will allow the user to pass different kinds of WeightProviders to the IK directly from the configuration file.
Moreover, I introduced the `IntegrationBasedIKProblem` that stores all the ingredients required to solve the IK problem.
> Add WeightProvider factory and implement IntegrationBasedIKProblem

- CHANGELOG.md
- src/IK/src/QPInverseKinematics.cpp
> Return an error if an invalid KinDynComputations object is passed to `QPInverseKinematics::build()`

- CHANGELOG.md
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/SubModel.h
- src/Estimators/src/SubModel.cpp
- src/Estimators/src/SubModelKinDynWrapper.cpp
- src/Estimators/tests/RobotDynamicsEstimator/SubModelCreatorTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/SubModelKinDynWrapperTest.cpp
The case without force/torque sensors to split the model was not considered and if the list of sensors was empty we had a segmentation fault error. This PR fixes the problem and now if the user does not specify a list of sensors, the SubModelCreator creates a unique SubModel object corresponding to the full model.
> Handle the case without force/torque sensors 

- CHANGELOG.md
- bindings/python/Contacts/include/BipedalLocomotion/bindings/Contacts/ContactDetectors.h
- bindings/python/Contacts/src/ContactDetectors.cpp
- bindings/python/Contacts/src/Module.cpp
- bindings/python/Contacts/tests/test_schmitt_trigger_detector.py
- bindings/python/Math/CMakeLists.txt
- bindings/python/Math/include/BipedalLocomotion/bindings/Math/SchmittTrigger.h
- bindings/python/Math/src/Module.cpp
- bindings/python/Math/src/SchmittTrigger.cpp
- src/Contacts/include/BipedalLocomotion/ContactDetectors/ContactDetector.h
- src/Contacts/include/BipedalLocomotion/ContactDetectors/FixedFootDetector.h
- src/Contacts/include/BipedalLocomotion/ContactDetectors/SchmittTriggerDetector.h
- src/Contacts/include/BipedalLocomotion/Contacts/ContactPhaseList.h
- src/Contacts/src/ContactDetector.cpp
- src/Contacts/src/ContactPhaseList.cpp
- src/Contacts/src/FixedFootDetector.cpp
- src/Contacts/src/SchmittTriggerDetector.cpp
- src/Contacts/tests/ContactDetectors/FixedFootDetectorUnitTest.cpp
- src/Contacts/tests/ContactDetectors/SchmittTriggerDetectorUnitTest.cpp
- src/Math/CMakeLists.txt
- src/Math/include/BipedalLocomotion/Math/Constants.h
- src/Math/include/BipedalLocomotion/Math/SchmittTrigger.h
- src/Math/src/SchmittTrigger.cpp
- src/Math/tests/CMakeLists.txt
- src/Math/tests/SchmittTriggerTest.cpp
This is the first PR that will bring the [CentroidalMPC](https://github.com/ami-iit/paper_romualdi_2022_icra_centroidal-mpc-walking) merged in master. 
While implementing the [`WholeBodyQPBlock`](https://github.com/ami-iit/paper_romualdi_2022_icra_centroidal-mpc-walking/blob/bd9f6a2537d45ca9c0c6bb6441bebbe4022087f3/src/centroidal-mpc-walking/src/WholeBodyQPBlock.cpp), I noticed that the behavior of `FixedFootDetector` (the class used to get the fixed foot given planned footsteps) was not coherent with the others advanceable in the project. Indeed, before this PR, a user had to call `FixedFootDetector::getFixedFoot()` before calling `FixedFootDetector::advance()`. This behavior was counterintuitive since the `Advanceable` should be able to provide its output only if `advance()` is called. …
> Restructure ContactDetector machinery 

- .github/workflows/ci.yml
- bindings/python/CMakeLists.txt
This should fix https://github.com/ami-iit/bipedal-locomotion-framework/actions/runs/4510249345/jobs/7940979417?pr=634#step:21:1013
> Looking for c++17 for python bindings

- CHANGELOG.md
- bindings/python/Contacts/src/Contacts.cpp
- bindings/python/Planners/src/SwingFootPlanner.cpp
- src/Contacts/include/BipedalLocomotion/Contacts/Contact.h
- src/Contacts/src/Contact.cpp
- src/Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
- src/Planners/src/SwingFootPlanner.cpp
- src/Planners/tests/SwingFootPlannerTest.cpp
With this PR it will be possible to update the contact list in the `SwingFootTrajectoryPlanner`. 
If the contact list is not empty, we check if it is possible to update the list.  Given some limitations of the framework (mainly due to the SO3 trajectory generation) for the time being, we support only the two following cases:
- Given the current time instant, both the stored and the new contact lists must have an active contact at the same pose.
- If the contact is not active (swing phase) the next contact must satisfy the following two hypothesis
1. the orientation of the next contact must be the same as the orientation of the next contact in the contact list stored in the class.
2. the impact time of the next contact must be the same as the one of the next contact in the contact list …
> Add the possibility to update the contact list in the swing foot trajectory planner

- .github/workflows/ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/636 .
This PR fixes an issue when using CMake 3.26.1 (so a quite recent CMake) with pybind11 2.4.3 (quite an old version). 
Basically, the problem is that the old version of pybind11 explicitly sets `-std=c++14` as compilation option, and this overrides the `-std=c++17` option that should be used instead (see https://github.com/pybind/pybind11/blob/v2.4.3/tools/pybind11Tools.cmake#L21 and https://github.com/pybind/pybind11/blob/v2.4.3/tools/pybind11Tools.cmake#L21). By explicitingly setting the `CMAKE_CXX_STANDARD` option, we make sure that pybind11 does not set any additional option.
> Fix compilation when using CMake 3.26.1 and pybind11 2.4.3 (for example on Ubuntu 20.04 GitHub Actions image)

- CHANGELOG.md
- src/IK/include/BipedalLocomotion/IK/CoMTask.h
- src/IK/src/CoMTask.cpp
- src/TSID/include/BipedalLocomotion/TSID/CoMTask.h
- src/TSID/src/CoMTask.cpp
With this PR it will be possible to set vectorial gains in TSID and IK CoM Tasks.
After merging this PR, I will release a new version of the code so we can safely merge https://github.com/robotology/robotology-superbuild/pull/1384
---
@CarlottaSartore
> Add the possibility to set vectorial gains in CoM IK and TSID tasks

- bindings/python/Contacts/CMakeLists.txt
- bindings/python/Contacts/tests/test_fixed_foot_detector.py
There was an unexpected test failure in https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/25, and it turned out a test was not run in the CI.
> Add missing test test_fixed_foot_detector.py to Python tests

- CHANGELOG.md
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/SubModel.h
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/SubModelKinDynWrapper.h
- src/Estimators/src/SubModel.cpp
- src/Estimators/src/SubModelKinDynWrapper.cpp
- src/Estimators/tests/RobotDynamicsEstimator/SubModelCreatorTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/SubModelKinDynWrapperTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/config/config.ini
- src/Estimators/tests/RobotDynamicsEstimator/config/model.ini
- src/Estimators/tests/RobotDynamicsEstimator/config/ukf.ini
- src/Estimators/tests/RobotDynamicsEstimator/config/ukf/ukf_measurement.ini
- src/Estimators/tests/RobotDynamicsEstimator/config/ukf/ukf_state.ini
Hi @GiulioRomualdi and @S-Dafarra, as anticipated in https://github.com/ami-iit/bipedal-locomotion-framework/pull/615#issuecomment-1523654641 here is a first PR.
This PR modifies some interfaces and adds some methods to the already merged classes `SubModel` and `SubModelKinDynWrapper`.
> Implement robot dynamics estimator - PR1

- CHANGELOG.md
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/ConstantMeasurementModel.h
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/Dynamics.h
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/JointVelocityStateDynamics.h
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/SubModelKinDynWrapper.h
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/ZeroVelocityStateDynamics.h
- src/Estimators/src/ConstantMeasurementModel.cpp
- src/Estimators/src/Dynamics.cpp
- src/Estimators/src/JointVelocityStateDynamics.cpp
- src/Estimators/src/ZeroVelocityStateDynamics.cpp
- src/Estimators/tests/RobotDynamicsEstimator/CMakeLists.txt
- src/Estimators/tests/RobotDynamicsEstimator/ConstantMeasurementModelTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/JointVelocityStateDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/ZeroVelocityStateDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/config/ukf/ukf_measurement.ini
- src/Estimators/tests/RobotDynamicsEstimator/config/ukf/ukf_state.ini
This PR implements the base class `Dynamics` which can be extended to implement specific dynamics describing the process model and the measurement model. Together with this base class I already added two specific models:
- the `ZeroVelocityDynamics` defines a dynamic model having a null first derivative
- the `JointVelocityStateDynamics` describes the dynamic model of the robot joints.
> Implement robot dynamics estimator - PR2

- CHANGELOG.md
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/AccelerometerMeasurementDynamics.h
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/GyroscopeMeasurementDynamics.h
- src/Estimators/src/AccelerometerMeasurementDynamics.cpp
- src/Estimators/src/GyroscopeMeasurementDynamics.cpp
- src/Estimators/tests/RobotDynamicsEstimator/AccelerometerMeasurementDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/CMakeLists.txt
- src/Estimators/tests/RobotDynamicsEstimator/GyroscopeMeasurementDynamicsTest.cpp
The PR implements two classes `AccelerometerMeasurementDynamics` and `GyroscopeMeasurementDynamics` describing the measurement models for the accelerometer and the gyroscope sensors.
> Add accelerometer and gyroscope dynamic models

- CHANGELOG.md
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/FrictionTorqueStateDynamics.h
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/MotorCurrentMeasurementDynamics.h
- src/Estimators/src/FrictionTorqueStateDynamics.cpp
- src/Estimators/src/MotorCurrentMeasurementDynamics.cpp
- src/Estimators/tests/RobotDynamicsEstimator/CMakeLists.txt
- src/Estimators/tests/RobotDynamicsEstimator/FrictionTorqueStateDynamicsTest.cpp
This PR implements the process model for the friction torque `FrictionTorqueStateDynamics` and the measurement model for motor current `MotorCurrentMeasurementDynamics`.
> Add process model for friction torque and measurement model for motor current

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/ft_clients.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/mas-remapper.xml
This is required to have the logger working after https://github.com/robotology/robots-configuration/pull/505
I already test it on the robot with @traversaro
---
cc @isorrentino
> 🤖 [ergoCubSN000] Clean the mas remapper files of the YarpRobotLoggerDevice

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/webcams.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- src/RobotInterface/YarpImplementation/src/YarpCameraBridge.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ICameraBridge.h
This PR:
1. adds the possibility to log RGBD stream in the YarpRobotLoggerDevice https://github.com/ami-iit/bipedal-locomotion-framework/pull/672/commits/35e2a380220ec81efd1a0fefaa7ba9f9d7d02a48
2. Fixes some bugs in YarpCameraBridge https://github.com/ami-iit/bipedal-locomotion-framework/pull/672/commits/6e9074c6e72da3ba05ecc384989bafa57f0a866c
> Enable depth logging in YarpRobotLoggerDevice

- src/TSID/src/FeasibleContactWrenchTask.cpp
This fixes the CI failure spotted in https://github.com/ami-iit/bipedal-locomotion-framework/pull/678#issuecomment-1557007400
> Fix macOS compilation of FeasibleContactWrenchTask

- CHANGELOG.md
- bindings/python/ML/CMakeLists.txt
- bindings/python/ML/include/BipedalLocomotion/bindings/ML/MANNTrajectoryGenerator.h
- bindings/python/ML/src/MANNAutoregressive.cpp
- bindings/python/ML/src/MANNTrajectoryGenerator.cpp
- bindings/python/ML/src/Module.cpp
- src/ML/CMakeLists.txt
- src/ML/include/BipedalLocomotion/ML/MANNAutoregressive.h
- src/ML/include/BipedalLocomotion/ML/MANNTrajectoryGenerator.h
- src/ML/src/MANNAutoregressive.cpp
- src/ML/src/MANNTrajectoryGenerator.cpp
- src/ML/tests/CMakeLists.txt
- src/ML/tests/FolderPath.h.in
- src/ML/tests/MANNTest.cpp
- src/ML/tests/MANNTrajectoryGeneratorTest.cpp
This PR implements `MANNTrajectoryGenerator`.
The `MANNTrajectoryGenerator` class utilizes the `MANNAutoregressive` algorithm to generate a kinematically feasible trajectory for humanoid robots. The planner generates a trajectory with a duration equal to `slow_down_factor * time_horizon` seconds.
The diagram shows how the `MANNAutoregressive` is used within the `MANNTrajectoryGenerator` class.
To initialize the generator, the user must set the initial state using the `MANNTrajectoryGenerator::setInitialState` method. The generator takes `MANNTrajectoryGeneratorInput` as input, which is used as the input for `MANNAutoregressiveInput`, along with the `mergePointIndex`. The `MANNAutoregressiveInput` is assumed to remain constant within the trajectory horizon. The `mergePointIndex` indicates …
> Implement MANNTrajectoryGenerator in ML component

- CHANGELOG.md
- bindings/python/ML/CMakeLists.txt
- bindings/python/ML/include/BipedalLocomotion/bindings/ML/MANNAutoregressiveInputBuilder.h
- bindings/python/ML/src/MANNAutoregressiveInputBuilder.cpp
- bindings/python/ML/src/Module.cpp
- src/ML/CMakeLists.txt
- src/ML/include/BipedalLocomotion/ML/MANNAutoregressiveInputBuilder.h
- src/ML/src/MANNAutoregressiveInputBuilder.cpp
- src/Math/CMakeLists.txt
- src/Math/include/BipedalLocomotion/Math/QuadraticBezierCurve.h
- src/Math/src/QuadraticBezierCurve.cpp
This PR implements the `MANNAutoregressiveInputBuilder` that is required to easily generate input for MANN from a joypad. The class does not depend on the joypad since it requires only two vectors. The desired motion direction and the facing direction.
> Implement QuadraticBezierCurve and MANNAutoregressiveInputBuilder

- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- cmake/Findonnxruntime.cmake
- src/ML/src/MANN.cpp
This PR adds support for the MANN component on Windows.
It is composed by two changes:
* Fix for CMake: https://github.com/conda-forge/onnxruntime-feedstock/pull/56 added an onnxruntime-cpp package on Windows, but name of the shared library on Windows is `onnxruntime_conda.dll` and not `onnxruntime.dll`, so we need to change accordingly the `Findonnxruntime.cmake` script.
* On Windows the Ort::Session wants a wchar_t*, so we need to convert the std::string to std::wstring (see https://github.com/microsoft/onnxruntime/issues/15889).
> MANN: support Windows 

- CHANGELOG.md
- docs/config.toml
- docs/pages/main-page.dox
- docs/pages/so3-minjerk.md
- src/Planners/include/BipedalLocomotion/Planners/SO3Planner.h
- src/Planners/include/BipedalLocomotion/Planners/SO3Planner.tpp
- src/Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
- src/Planners/src/SwingFootPlanner.cpp
- src/Planners/tests/SO3PlannerTest.cpp
- src/Planners/tests/SwingFootPlannerTest.cpp
Thanks to this PR we can update the contact list in the swing foot planner when the contact is not active and the new orientation is different from the previous one.
> Add the possibility to change the orientation of the foot in the swing foot planner when the contact is not active

- bindings/python/Contacts/CMakeLists.txt
- bindings/python/ContinuousDynamicalSystem/CMakeLists.txt
- bindings/python/Conversions/CMakeLists.txt
- bindings/python/FloatingBaseEstimators/CMakeLists.txt
- bindings/python/IK/CMakeLists.txt
- bindings/python/ML/CMakeLists.txt
- bindings/python/ParametersHandler/CMakeLists.txt
- bindings/python/Planners/CMakeLists.txt
- bindings/python/ReducedModelControllers/CMakeLists.txt
- bindings/python/RobotInterface/CMakeLists.txt
- bindings/python/System/CMakeLists.txt
- bindings/python/TSID/CMakeLists.txt
- bindings/python/TextLogging/CMakeLists.txt
- bindings/python/YarpUtilities/CMakeLists.txt
https://github.com/ami-iit/bipedal-locomotion-framework/pull/697 introduced an untested and undocumented support for building the Python bindings in a standalone way against an existing compiled version of BLF, that we plan to use in conda-forge packaging. However, that patch was not complete as the CMakeLists.txt in `bindings/python` still referred to CMake options that do not exists if an external blf is used.
I am testing the patch in https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/30 .
> Fix standalone Python bindings workflow

- CHANGELOG.md
- bindings/python/bipedal_locomotion_framework.cpp.in
> Fix python bindings compilation when toml is not installed

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
> Fix YarpRobotLoggerDevice if YARP_ROBOT_NAME is not defined

- .github/workflows/conda-forge-ci.yml
The pin was added in https://github.com/ami-iit/bipedal-locomotion-framework/pull/675 as a workaround for https://github.com/ami-iit/bipedal-locomotion-framework/issues/674 (root issue for reference: https://github.com/conda-forge/pybind11-feedstock/issues/77) until https://github.com/conda-forge/compilers-feedstock/pull/57 was merged. Now that https://github.com/conda-forge/compilers-feedstock/pull/57 was merged, we can remove the workaround.
> conda-forge CI: Remove manifpy strict pin

- CHANGELOG.md
- bindings/python/System/include/BipedalLocomotion/bindings/System/IClock.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- src/System/RosImplementation/include/BipedalLocomotion/System/RosClock.h
- src/System/RosImplementation/src/RosClock.cpp
- src/System/YarpImplementation/include/BipedalLocomotion/System/YarpClock.h
- src/System/YarpImplementation/src/YarpClock.cpp
- src/System/include/BipedalLocomotion/System/AdvanceableRunner.h
- src/System/include/BipedalLocomotion/System/IClock.h
- src/System/include/BipedalLocomotion/System/SharedResource.h
- src/System/include/BipedalLocomotion/System/StdClock.h
- src/System/src/StdClock.cpp
- src/System/tests/AdvanceableRunnerTest.cpp
This PR concludes the work started in https://github.com/ami-iit/bipedal-locomotion-framework/pull/630 by using `std::chrono::nanoseconds` in `BipedalLocomotion::clock` and `BipedalLocomotion::System::AdvanceableRunner`.
> Use `std::chrono::nanoseconds` in `clock` and `AdvanceableRunner`

- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
The time is now saved again in seconds and not in nanoseconds
Regression due to https://github.com/ami-iit/bipedal-locomotion-framework/pull/702
cc @gabrielenava @davidegorbani
> Fix the time logging in YarpRobotLogger device

- CHANGELOG.md
- bindings/python/ContinuousDynamicalSystem/include/BipedalLocomotion/bindings/ContinuousDynamicalSystem/Integrator.h
- bindings/python/ContinuousDynamicalSystem/src/CentroidalDynamics.cpp
- bindings/python/ContinuousDynamicalSystem/src/LinearTimeInvariantSystem.cpp
- src/ContinuousDynamicalSystem/CMakeLists.txt
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/RK4.h
- src/ContinuousDynamicalSystem/tests/IntegratorLinearSystem.cpp
This integrator can be used only for tuple that contains only vectors that belong to $R^n$ and it is not compatible with general LieGroups.
I've already exposed the python bindings for the integrator
> Implement RK4 integrator in ContinuousDynamicalSystem component and expose the python bindings

- .github/workflows/ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- cmake/FindQhull.cmake
- src/Planners/CMakeLists.txt
- src/Planners/src/ConvexHullHelper.cpp
On ubuntu 22.04 I got the following error
```
usr/bin/ld: ../../../lib/libBipedalLocomotionFrameworkPlanners.so.0.14.200: undefined reference to `qh_new_qhull(int, int, double*, unsigned int, char*, _IO_FILE*, _IO_FILE*)'
/usr/bin/ld: ../../../lib/libBipedalLocomotionFrameworkPlanners.so.0.14.200: undefined reference to `qh_memfreeshort(int*, int*)'
/usr/bin/ld: ../../../lib/libBipedalLocomotionFrameworkPlanners.so.0.14.200: undefined reference to `qh_freeqhull(unsigned int)'
collect2: error: ld returned 1 exit status
make[3]: *** [src/Planners/tests/CMakeFiles/SwingFootPlannerUnitTests.dir/build.make:108: bin/SwingFootPlannerUnitTests] Error 1
make[2]: *** [CMakeFiles/Makefile2:3853: src/Planners/tests/CMakeFiles/SwingFootPlannerUnitTests.dir/all] Error 2
make[1]: *** …
```
> Attempt to use the c version of qhull

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1/blf-yarp-robot-logger-interfaces/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova02/blf-yarp-robot-logger-interfaces/ft-imu-mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova02/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova04/blf-yarp-robot-logger-interfaces/ft-imu-mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova04/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/blf-yarp-robot-logger-interfaces/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/UkfState.h
- src/Estimators/tests/RobotDynamicsEstimator/ConstantMeasurementModelTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/GyroscopeMeasurementDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/ZeroVelocityStateDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/config/model.ini
Fix https://github.com/robotology/icub-models-generator/issues/242 .
icub-models 2.0.0 changed the name of the FT sensors in the URDF from being named `<identifier>_ft_sensor` (like `l_arm_ft_sensor`, `l_leg_ft_sensor`, ...) to `<identifier>_ft` (like `l_arm_ft`, `l_leg_ft`, ...). 
However, the yarprobotinterface configuration files continued to refer to the sensors as `<identifier>_ft_sensor`, creating errors for software that was trying to match sensors find in URDF and sensors as exposed by the YARP's multipleanalogsensorsserver device.
This PR changes all the instances of iCub configuration files to `<identifier>_ft`, restoring compatibility with icub-models 2.0.0, robots-configuration releases >= 2.5.0 and ergocub-software >= 0.3.4, see …
> Change FT sensors names for compatibility with icub-models >= 2.0.0, robots-configuration >= 2.5.0 and ergocub-software >= 0.3.4

- .github/workflows/changelog-checker.yml
Fix failure in the changelog-checker. The issue that created problems with v1.1.0 is https://github.com/Zomzog/changelog-checker/issues/53, it was fixed in https://github.com/Zomzog/changelog-checker/pull/55 so I used the commit corresponding to the lates master commit to get things to work. 
I checked that it fails (but with the correct error) if their is no label `[disable changelog ci]`, and that with the label it passes.
> Fix changelog-checker CI check

- CHANGELOG.md
- src/System/include/BipedalLocomotion/System/AdvanceableRunner.h
As per the title, this PR adds the possibility to stop the advanceable runner if the number of deadline misses exceeds the accepted maximum
> Set a maximum number of accepted deadline miss the the AdvanceableRunner

- .gitignore
- CHANGELOG.md
- bindings/python/IK/CMakeLists.txt
- bindings/python/IK/include/BipedalLocomotion/bindings/IK/DistanceTask.h
- bindings/python/IK/include/BipedalLocomotion/bindings/IK/GravityTask.h
- bindings/python/IK/src/DistanceTask.cpp
- bindings/python/IK/src/GravityTask.cpp
- bindings/python/IK/src/Module.cpp
- bindings/python/IK/tests/test_QP_inverse_kinematics.py
- src/IK/CMakeLists.txt
- src/IK/include/BipedalLocomotion/IK/DistanceTask.h
- src/IK/include/BipedalLocomotion/IK/GravityTask.h
- src/IK/src/DistanceTask.cpp
- src/IK/src/GravityTask.cpp
- src/IK/tests/CMakeLists.txt
- src/IK/tests/DistanceTaskTest.cpp
- src/IK/tests/GravityTaskTest.cpp
- src/IK/tests/QPInverseKinematicsTest.cpp
Implements the ``DistanceTask`` and ``GravityTask`` initially implemented by @EhsanRanjbari
> Distance and gravity tasks

- CHANGELOG.md
- src/IK/include/BipedalLocomotion/IK/SE3Task.h
- src/IK/src/SE3Task.cpp
- src/TSID/include/BipedalLocomotion/TSID/SE3Task.h
- src/TSID/src/SE3Task.cpp
- src/TSID/tests/SE3TaskTest.cpp
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/725
> Add the possibility to control a subset of linear coordinates in `TSID::SE3Task`

- CHANGELOG.md
- bindings/CMakeLists.txt
- bindings/python/CMakeLists.txt
This is done by setting the FRAMEWORK_PYTHON_INSTALL_DIR CMake variable.
> CMake: Permit to explictly specify Python installation directory

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- src/Estimators/src/AccelerometerMeasurementDynamics.cpp
- src/Estimators/tests/FloatingBaseEstimators/FloatingBaseEstimatorTest.cpp
- src/Estimators/tests/FloatingBaseEstimators/InvariantEKFBaseEstimatorTest.cpp
Add `bayes-filters-lib` dependency (https://github.com/robotology/bayes-filters-lib/tree/master) to the CI to install the `RobotDynamicsEstimator` library.
PS. I do not know if I missed something as it is the first time I have modified the CI.
cc @GiulioRomualdi
> Modify ci to install and test `RobotDynamicsEstimator` library

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
With this PR, I saved the timestamps of the frames collected with the YarpRobotLoggerDevice in seconds instead of nanoseconds.
> Fix timestamp logging for the cameras

- CHANGELOG.md
- bindings/CMakeLists.txt
> Update the CMakeLists.txt to be compliant with python 3.12

- CHANGELOG.md
- bindings/python/CMakeLists.txt
- bindings/python/RobotDynamicsEstimator/CMakeLists.txt
- bindings/python/RobotDynamicsEstimator/include/BipedalLocomotion/bindings/RobotDynamicsEstimator/Module.h
- bindings/python/RobotDynamicsEstimator/include/BipedalLocomotion/bindings/RobotDynamicsEstimator/RobotDynamicsEstimator.h
- bindings/python/RobotDynamicsEstimator/src/Module.cpp
- bindings/python/RobotDynamicsEstimator/src/RobotDynamicsEstimator.cpp
- bindings/python/bipedal_locomotion_framework.cpp.in
- src/ML/tests/MANNTrajectoryGeneratorTest.cpp
> Add Python bindings for RDE library - PR5

- CHANGELOG.md
- bindings/python/RobotInterface/CMakeLists.txt
Fix "standalone" Python bindings build used in conda-forge builds.
> Add missing include(FetchContent) in bindings/python/RobotInterface/CMakeLists.txt

- CHANGELOG.md
- devices/CMakeLists.txt
- devices/RobotDynamicsEstimatorDevice/CMakeLists.txt
- devices/RobotDynamicsEstimatorDevice/README.md
- devices/RobotDynamicsEstimatorDevice/app/CMakeLists.txt
- devices/RobotDynamicsEstimatorDevice/app/robots/ergoCubGazeboV1/interface-robot-dynamics-estimator/all_joints_mc.xml
- devices/RobotDynamicsEstimatorDevice/app/robots/ergoCubGazeboV1/interface-robot-dynamics-estimator/ft_clients.xml
- devices/RobotDynamicsEstimatorDevice/app/robots/ergoCubGazeboV1/interface-robot-dynamics-estimator/mas-remapper.xml
- devices/RobotDynamicsEstimatorDevice/app/robots/ergoCubGazeboV1/launch-robot-dynamics-estimator.xml
- devices/RobotDynamicsEstimatorDevice/app/robots/ergoCubGazeboV1/robot-dynamics-estimator.xml
- devices/RobotDynamicsEstimatorDevice/include/BipedalLocomotion/RobotDynamicsEstimatorDevice.h
- devices/RobotDynamicsEstimatorDevice/src/RobotDynamicsEstimatorDevice.cpp
This is the last PR for the `RobotDynamicsEstimator`. It implements the device that will be running on the robot and uses the full `RDE` library. I tested the device in simulation by commenting out the readings of the motor currents (not available in Gazebo) and by setting them manually.
> Implement `RobotDynamicsEstimatorDevice` - PR6

- CHANGELOG.md
- bindings/python/Contacts/src/Contacts.cpp
- bindings/python/Planners/src/SwingFootPlanner.cpp
- bindings/python/Planners/tests/test_swing_foot_planner.py
- src/Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
- src/Planners/src/SwingFootPlanner.cpp
This PR restructured the swing foot planner to handler corners case that came out while testing DNN-MPC integration. The code has been tested on the robot.
> Refactory of the swing foot planner

- .github/workflows/ci.yml
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/769 . I do not think it make sense to document this change in the changelog.
> CI: Bump vcpkg-robotology to v0.11.0

- CHANGELOG.md
- bindings/python/ML/src/MANNAutoregressive.cpp
- bindings/python/ML/src/MANNTrajectoryGenerator.cpp
- examples/MANN/MANNAutoregressive.ipynb
- examples/MANN/MANNTrajectoryGenerator.ipynb
- examples/MANN/README.md
- examples/MANN/config/config_joypad.toml
- examples/MANN/config/config_mann.toml
- src/ML/include/BipedalLocomotion/ML/MANN.h
- src/ML/include/BipedalLocomotion/ML/MANNAutoregressive.h
- src/ML/include/BipedalLocomotion/ML/MANNTrajectoryGenerator.h
- src/ML/src/MANN.cpp
- src/ML/src/MANNAutoregressive.cpp
- src/ML/src/MANNTrajectoryGenerator.cpp
- src/ML/tests/MANNTest.cpp
- src/ML/tests/MANNTrajectoryGeneratorTest.cpp
This PR is the outcome of the refactoring carried out with @paolo-viceconte 
In detail, we implemented `MANN::generateDummyMANNOutput` and `MANN::generateDummyMANNInput` in the `ML` component. Additionally, we restructured `MANNAutoregressive` for improved reset handling by introducing the `MANNFootState` class and consolidating reset-related quantities in `MANNAutoregressive::AutoregressiveState`. This simplifies the generation of the initial `AutoregressiveState` required to start trajectory generation. Concurrently, we restructured `MANNTrajectoryGenerator` by eliminating the need to pass foot positions in setInitialState. We enhanced `MANNTrajectoryGenerator` with reset capabilities similar to `MANNAutoregressive` and corrected the position and time scaling to ensure accurate scaling …
> Restructure ML component

- CHANGELOG.md
- src/Estimators/CMakeLists.txt
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/ExternalContactStateDynamics.h
- src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/SubModel.h
- src/Estimators/src/ExternalContactStateDynamics.cpp
- src/Estimators/src/GyroscopeMeasurementDynamics.cpp
- src/Estimators/src/SubModel.cpp
- src/Estimators/src/UkfModel.cpp
- src/Estimators/tests/RobotDynamicsEstimator/AccelerometerMeasurementDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/CMakeLists.txt
- src/Estimators/tests/RobotDynamicsEstimator/ExternalContactStateDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/FrictionTorqueStateDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/GyroscopeMeasurementDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/JointVelocityStateDynamicsTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/KinDynWrapperTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/RobotDynamicsEstimationTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/SubModelCreatorTest.cpp
- src/Estimators/tests/RobotDynamicsEstimator/config/model.ini
- src/Estimators/tests/RobotDynamicsEstimator/config/ukf/ukf_measurement.ini
- src/Estimators/tests/RobotDynamicsEstimator/config/ukf/ukf_state.ini
This PR introduced a process model for the external contacts defined as 
$$
\dot{f} = -k f 
$$
In addition, the PR changes the logic to define a name for the dynamics. Indeed, the name of the dynamics has to match the name `ukf_name` defined in the `model` configuration file. This solves the problem described in https://github.com/ami-iit/bipedal-locomotion-framework/issues/760 which was causing a segmentation fault when using the ft frame as the external contact frame. 
cc @GiulioRomualdi @S-Dafarra
> Add process dynamics class for external contacts

- CHANGELOG.md
- src/Contacts/include/BipedalLocomotion/Contacts/Contact.h
- src/Contacts/include/BipedalLocomotion/Contacts/ContactList.h
- src/Contacts/include/BipedalLocomotion/Contacts/ContactPhase.h
- src/Contacts/include/BipedalLocomotion/Contacts/ContactPhaseList.h
- src/Contacts/src/Contact.cpp
- src/Contacts/src/ContactList.cpp
- src/Contacts/src/ContactPhase.cpp
- src/Contacts/src/ContactPhaseList.cpp
As per title, this simplify the debugging
> Implement toString() methods in PlannedContact, ContactList, ContactPhase and ContactPhaseList

- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
This fixes how the metadata are retrieved by the logger
> Fix metadata collection in YarpRobotLoggerDevice

- devices/YarpRobotLoggerDevice/README.md
Since this logging device is widely used in the lab, I think we should keep the readme up to date. This PR updates the readme and explains how to log exogenous signal data. 
Moreover, it closes https://github.com/ami-iit/bipedal-locomotion-framework/issues/527
cc @G-Cervettini @traversaro @nicktrem @davidegorbani
> Update the README in YarpRobotLoggerDevice

- CHANGELOG.md
- bindings/python/Math/include/BipedalLocomotion/bindings/Math/Spline.h
- bindings/python/Math/src/Module.cpp
- bindings/python/Math/src/Spline.cpp
- src/Math/CMakeLists.txt
- src/Math/include/BipedalLocomotion/Math/CubicSpline.h
- src/Math/include/BipedalLocomotion/Math/LinearSpline.h
- src/Math/include/BipedalLocomotion/Math/QuinticSpline.h
- src/Math/include/BipedalLocomotion/Math/Spline.h
- src/Math/tests/SplineTest.cpp
This PR implements the `LinearSpline` class in the `math` component, where `LinearSpline` is a [piecewise linear function](https://en.wikipedia.org/wiki/Piecewise_linear_function) of the form. 
```math
s(t) = a_0 + a_1 t
```
where $t \in [0, T_i]$ and $T_i$ is the duration of the i-th polynomial.
> Implement LinearSpline in Math component

- CHANGELOG.md
- src/IK/src/QPInverseKinematics.cpp
- src/IK/tests/QPInverseKinematicsTest.cpp
- src/TSID/src/QPTSID.cpp
This addresses https://github.com/ami-iit/bipedal-locomotion-framework/issues/723
> Add the support of QP problems with no constraint in QPInverseKinematics and QPTSID 

- src/Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
- src/Planners/src/SwingFootPlanner.cpp
As per the title, this PR adds the possibility of setting the orientation and position tolerances for the swing foot planner. These tolerances are used to check if the position of a contact changes when it is already active. Having a tunable tolerance will make the planner more robust when the contact location are computed by an optimization procedure, for instance `sqpmethod`
> Add the possibility to set the SwingFootPlanner position and orientation tolerances as configuration parameters

- CHANGELOG.md
- bindings/python/Contacts/src/Contacts.cpp
- src/Contacts/include/BipedalLocomotion/Contacts/ContactList.h
- src/Contacts/include/BipedalLocomotion/Contacts/ContactPhaseList.h
- src/Contacts/src/ContactList.cpp
- src/Contacts/src/ContactPhaseList.cpp
- src/Contacts/tests/Contacts/ContactListTest.cpp
- src/Planners/src/SwingFootPlanner.cpp
- src/ReducedModelControllers/src/CentroidalMPC.cpp
While testing the integration of the MPC with MANN, we realized that the neural network was generating contacts whose activation and deactivation times weren't divisible by the MPC sampling time. This caused an issue when generating the internal vector of the MPC discretization. To overcome this limitation, we decided to implement a method in the ContactList to resample the contacts so that the activation and deactivation times are divisible with respect to a given sampling time.
Specifically, the activation time is decreased to ensure divisibility, while the deactivation time is increased. This way, we increase the overall contact duration.
Last but not least, the MPC checks that the contact timings are correctly sampled.
> Add the possibility to resample the contact in a given contact list and force the MPC to required correctly sampled contacts 

- CHANGELOG.md
- src/System/include/BipedalLocomotion/System/AdvanceableRunner.h
- src/System/include/BipedalLocomotion/System/Barrier.h
- src/System/src/Barrier.cpp
- src/System/tests/AdvanceableRunnerTest.cpp
As explained in [this comment](https://github.com/ami-iit/element_torque-control-for-walking/issues/100#issuecomment-1932445223), we found out that the **barrier logic** for **threads synchronization** is not working properly.
This is due to the following two reasons:
1. No thread will go to the [else](https://github.com/ami-iit/bipedal-locomotion-framework/blob/a921a3bede58511cef6ae9d234de112370ded0a0/src/System/src/Barrier.cpp#L36C1-L39C6) branch if the `if` condition reads [((--m_count) == 1)](https://github.com/ami-iit/bipedal-locomotion-framework/blob/a921a3bede58511cef6ae9d234de112370ded0a0/src/System/src/Barrier.cpp#L25C9-L25C25). Therefore no thread will wait.
2. The [wait() ](https://github.com/ami-iit/bipedal-locomotion-framework/blob/a921a3bede58511cef6ae9d234de112370ded0a0/src/ …
> Fix the barrier logic for threads synchronization

- CHANGELOG.md
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/CentroidalDynamics.h
- src/ContinuousDynamicalSystem/src/CentroidalDynamics.cpp
This PR aims at providing a member function to set on the fly the gravity vector used in [CentroidalDynamics.h](https://github.com/ami-iit/bipedal-locomotion-framework/blob/master/src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/CentroidalDynamics.h).
For example, when the reference frame is changed from the `world` one to a `local` one, and we want to write the centroidal dynamics in this new `local frame`, it might be needed to set a new gravity vector.
> Add member function to set gravity vector in centroidal dynamics system

- .github/workflows/conda-forge-ci.yml
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/829, add workaround for https://github.com/conda-forge/pybind11-feedstock/issues/95 .
> Constraint pybind11 version to fix conda-forge Windows CI

- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- cmake/InstallBasicPackageFiles.cmake
`OVERRIDE_MODULE_PATH` used the `PACKAGE_PREFIX_DIR` variable, that however was an internal undocumented detail of configure_package_config_file and that was changed in CMake 3.29.1 by https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9390 .
See https://github.com/ami-iit/matio-cpp/issues/78#issuecomment-2044457554 for more context.
To fix the problem, we switch to add directly the `OVERRIDE_MODULE_PATH` logic in the generated cmake config template, so that there we can use the `@PACKAGE_CMAKE_INSTALL_PREFIX@` variable, and rely on the `configure_package_config_file` to appropriately substitute `@PACKAGE_CMAKE_INSTALL_PREFIX@` with the actual relocated install prefix. To do so, we also pass `CMAKE_INSTALL_PREFIX` to the `PATH_VARS` option of `configure_package_config_file`.
See also …
> InstallBasicPackageFiles: Fix OVERRIDE_MODULE_PATH with CMake >=3.29.1

- CHANGELOG.md
- src/ML/include/BipedalLocomotion/ML/MANN.h
- src/ML/src/MANN.cpp
With @LoreMoretti and @traversaro, we observed that during inference, onnxruntime spawns n threads, where n is the number of cores, as explained in https://onnxruntime.ai/docs/performance/tune-performance/threading.html. This results in a slowdown for other threads and processes. This PR allows the user to set the number of threads used for the inference
> Add the possibility to set the number of threads used by onnxruntime in MANN

- CHANGELOG.md
- src/ContinuousDynamicalSystem/CMakeLists.txt
- src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/ButterworthLowPassFilter.h
- src/ContinuousDynamicalSystem/src/ButterworthLowPassFilter.cpp
- src/ContinuousDynamicalSystem/tests/ButterworthLowPassFilter.cpp
- src/ContinuousDynamicalSystem/tests/CMakeLists.txt
This PR implements the ButterworthLowPassFilter. The filter is described by the following transfer function
```math
H(s) = \frac{1}{\sqrt{1 + \left(\frac{s}{\omega_c}\right)^{2N}}}
```
where $\omega_c$ is the cutoff frequency and $N$ is the order of the filter and $s$ is the Laplace variable.
To compute the coefficient of the filter we split the problem in three steps:
1. Compute the transfer function of the continuous system.
2. Compute the transfer function of the discrete system.
3. Compute the coefficients of the discrete system.
What follows is taken from Passive and Active Network Analysis and Synthesis, Aram Budak, Houghton Mifflin, 1974 and from https://dsp.stackexchange.com/questions/79498/butterworth-filter-poles
The poles of the Butterworth filter are evenly spaced on a circle …
> Implement ButterworthLowPassFilter

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGazeboV3/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
This PR implements what is discussed in https://github.com/ami-iit/bipedal-locomotion-framework/issues/812#issuecomment-2057032884. I tested it and it fixes #812 (@rob-mau)
> Add maximum admissible time step parameter to YarpRobotLoggerDevice

- bindings/python/ContinuousDynamicalSystem/CMakeLists.txt
- bindings/python/ContinuousDynamicalSystem/include/BipedalLocomotion/bindings/ContinuousDynamicalSystem/ButterworthLowPassFilter.h
- bindings/python/ContinuousDynamicalSystem/src/ButterworthLowPassFilter.cpp
- bindings/python/ContinuousDynamicalSystem/src/Module.cpp
- bindings/python/System/include/BipedalLocomotion/bindings/System/Advanceable.h
- bindings/python/System/src/Advanceable.cpp
- bindings/python/System/src/Module.cpp
Moreover, I had to modify how the sink, source, and advanceable bindings are created for the `Eigen::VectorXd`. This is required otherwise if we try to register a type that has been already registered we get 
```
generc_type xxxx is already registered
```
See: https://github.com/pybind/pybind11/issues/439
> Implement the python bindings for the Butterworth low pass filter

- CHANGELOG.md
- src/ReducedModelControllers/include/BipedalLocomotion/ReducedModelControllers/CentroidalMPC.h
- src/ReducedModelControllers/src/CentroidalMPC.cpp
The goal of this PR is to expose the gravity vector as an input argument of the `CentroidalMPC`.
In this way, the user can pass it as other input arguments (like `currentCOM`, `externalWrench`, ...).
User can leverage the `setState` member function, or the `setGravity` one, to pass the gravity vector.
Moreover, if the user does not specify it, by default it is set to `[0, 0, -9.81]`.
> set gravity vector as an input argument of the CentroidalMPC

- CHANGELOG.md
- bindings/python/YarpUtilities/src/VectorsCollection.cpp
I was using `VectorsCollectionClient.read_data(False)` in Python, and when the `VectorsCollectionClient` was unable to retrieve data, it caused a segmentation fault. With this modification, the method returns `None` instead, preventing the segmentation fault.
> Fix `VectorsCollectionClient.read_data(False)` to provide `collection` as output and avoid segmentation fault

- CHANGELOG.md
- bindings/python/YarpUtilities/include/BipedalLocomotion/bindings/YarpUtilities/VectorsCollection.h
- bindings/python/YarpUtilities/src/Module.cpp
- bindings/python/YarpUtilities/src/VectorsCollection.cpp
My previous PR #850 was not working as expected because I forgot to create the bindings for `VectorsCollection`. In particular, when you call `read_data` you get the following error:
```python
TypeError: Unable to convert function return value to a Python type! The signature was
(self: bipedal_locomotion_framework.bindings.yarp_utilities.VectorsCollectionClient, arg0: bool) -> BipedalLocomotion::YarpUtilities::VectorsCollection
```
This PR creates Python bindings for `VectorsCollection` and modifies the behavior of `read_data` to provide an empty collection as output when it is unable to retrieve data.
> Create python bindings of `VectorsCollection`

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/src/YarpRobotControl.cpp
Fixes #851.
Now gives a clear error message if the vector size is incorrect:
```
[ERROR] [2024-06-13 15:35:43.808] [thread: 236092] [blf] [YarpRobotControl::Impl::setReferences] The size of the joint values is different from the number of actuated DoFs. Expected size: 7. Received size: 3.
```
> Add vector size check for joint values in setReferences in YarpRobotControl.cpp

- CHANGELOG.md
- examples/BindingsMotorControl/yarp_direct_motor_control.ipynb
- examples/Python/yarp_direct_motor_control.ipynb
In this PR I add a very basic example that shows a basic way of directly controlling the robot joints using the python bindings of BLF.
The example should be self-contained (as much as possible, we are still using gazebo so a full online experience is not the goal). 
Feel free to suggest modifications and clarifications!
> Add simple notebook example for joint control

- .github/workflows/conda-forge-ci.yml
- .github/workflows/gh-pages.yml
- examples/InverseKinematics/README.md
- examples/MANN/README.md
See https://github.com/robotology/robotology-superbuild/pull/1653 for the rationale. In general nowadays `conda` should be more and less as fast as `mamba`, and is more actively maintained.
> Switch from mamba to conda

- CHANGELOG.md
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpRobotControl.h
- src/RobotInterface/YarpImplementation/src/YarpRobotControl.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/IRobotControl.h
The goal of this PR is to add a member function to set the motor control mode in an asynchronous process, so that the invoking thread does not get blocked.
This feature might be handy when the switch of control mode is done within `Advanceable Runners` which have real time constraints and deadline misses checks.
> add setControlModeAsync member function

- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN002/yarp-robot-logger.xml
By default it would be convenient that the `jabra` camera is streamed, which means setting `stream_cameras` parameter to `true` by default for `ergocubSN002` (as it is done for `ergocubSN001`).
> Update yarp-robot-logger.xml for ergocubSN002

- cmake/AddBipedalLocomotionYARPThrift.cmake
Avoid annoying warning:
~~~
D:/miniforge3/envs/blfdev/Library/include\yarp/os/api.h(53): warning : "The YARP::YARP_OS target is deprecated. Use YARP::YARP_os instead" [D:\src\bipedal-locomotion-framework\build\devices\RobotDynamicsEstim
atorDevice\RobotDynamicsEstimatorDevice.vcxproj]
yarp_plugin_RobotDynamicsEstimatorDevice.cpp
D:/miniforge3/envs/blfdev/Library/include\yarp/os/api.h(53): warning : "The YARP::YARP_OS target is deprecated. Use YARP::YARP_os instead" [D:\src\bipedal-locomotion-framework\build\devices\RobotDynamicsEstim
atorDevice\RobotDynamicsEstimatorDevice.vcxproj]
~~~
> Fix link to deprecated CMake target YARP::YARP_OS

- .github/workflows/ci.yml
manif 0.0.5 was tagged today: https://github.com/artivis/manif/releases/tag/0.0.5 .
If the blf test pass fine with the new manif, we can release it in conda-forge and the superbuild.
> Bump manif in CI to 0.0.5

- CHANGELOG.md
- bindings/python/RobotInterface/src/SensorBridge.cpp
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
It targets https://github.com/ami-iit/bipedal-locomotion-framework/issues/875
> Make joint encoder acceleration reading optional

- .github/workflows/ci.yml
- .github/workflows/conda-forge-ci.yml
- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- utilities/balancing-torque-control/README.md
- utilities/balancing-torque-control/config/robots/ergoCubGazeboV1/blf_balancing_torque_control/robot_control.ini
- utilities/balancing-torque-control/script/blf-balancing-torque-control.py
This PR adds the possibility to specify the position of a non-controlled joint in the balancing torque control app. This is possible thanks to https://github.com/robotology/idyntree/pull/1180 and https://github.com/robotology/idyntree/pull/1174.
Given that, blf now requires iDynTree v12.2.1
cc @traversaro and @fils99
> Add the possibility to set the fixed joint configuration in balancing-torque-control app

- .github/workflows/conda-forge-ci.yml
- cmake/AddBipedalLocomotionUnitTest.cmake
Fix the build error:
~~~
[82/462] Building CXX object _deps/catch2-build/src/CMakeFiles/Catch2.dir/catch2/internal/catch_clara.cpp.o
FAILED: _deps/catch2-build/src/CMakeFiles/Catch2.dir/catch2/internal/catch_clara.cpp.o 
/usr/share/miniconda3/envs/test/bin/x86_64-conda-linux-gnu-c++ -Dcasadi_VERSION=3.6.6 -I/home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/build/_deps/catch2-src/src/catch2/.. -I/home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/build/generated-includes -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/share/miniconda3/envs/test/include -O3 -DNDEBUG -std=c++17 -fPIC …
> Use conda-forge's catch2 in CI to avoid build failures, set OMP_NUM_THREADS=1 and updated catch2's used by FetchContent to 3.7.1

- CHANGELOG.md
- devices/JointTorqueControlDevice/CMakeLists.txt
- devices/JointTorqueControlDevice/include/BipedalLocomotion/JointTorqueControlDevice.h
- devices/JointTorqueControlDevice/src/JointTorqueControlDevice.cpp
- devices/JointTorqueControlDevice/thrifts/JointTorqueControlCommands.thrift
This PR implements:
- a low-pass filter for filtering the estimated friction torque
- a saturation for the estimated friction torque
> Implement low-pass filter for estimated friction torque

- CHANGELOG.md
- utilities/joints-grid-position-tracking/blf-joints-grid-position-tracking.py
This PR fixes the bug found in https://github.com/ami-iit/element_pi-ft-modeling/issues/96#issuecomment-2383535504. Basically, the output type of the method `prepare_data()` should be `void`, while in https://github.com/ami-iit/bipedal-locomotion-framework/commit/d63fa9fbf67e10527a05431faa4951b4d8294580#diff-41b66f0e3904e0ce5ecc91e8dff26a004e80b7b6f1c27b81874d5b6554ce3154 the output is considered as `bool`. With this PR, the method is called in the proper way.
cc @GiulioRomualdi
> Fix bug related to prepare_data() method calling

- CHANGELOG.md
- utilities/motor-current-tracking/README.md
- utilities/motor-current-tracking/blf-motor-current-tracking.py
This PR adds software position limits, which can be specified in the config file, to the `blf-motor-current-tracking.py` application.
The software position limits can only restrict the range of motion of the joint with respect to the hardware limits.
> Add software position limits to motor current tracking application

- CHANGELOG.md
- bindings/CMakeLists.txt
Since Python 3.8, Python ignores the `PATH` env variable when trying to load the DLL of compiled Python extensions. 
We kind ignored the problem until now as if you install in `%CONDA_PREFIX%\Library\bin` in conda environment everything works out of the box, but the problem is present when bipedal-locomotion-framework is installed in an arbitrary install prefix and the Python bindings are found via `PYTHONPATH` env variable, see https://github.com/robotology/robotology-superbuild/issues/1268 .
This PR fixes the problem by adding some automatically generated code in the `__init__.py` file that automatically calls `os.add_dll_directory` as necessary.
As the Python code is generated by CMake it may be a bit cryptic, the actual rendered code is:
~~~py
import os
library_dll_path = …
> Fix loading of Python bindings on Windows when installed in arbitrary directory

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/imu_clients.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/blf-yarp-robot-logger-interfaces/mas-remapper.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
As per the title, this PR updates the config files of the `YarpLoggerDevice` of `ergoCubSN000`.
> [ergoCubSN000] update config files of the logger device

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- devices/examples/ROSPublisherTestDevice/CMakeLists.txt
- src/YarpUtilities/CMakeLists.txt
- src/YarpUtilities/include/BipedalLocomotion/YarpUtilities/RosPublisher.h
Since YARP 3.10, the `rosmsg` functionality is provided in the separate repository https://github.com/robotology/yarp-ros . The robotology-superbuild integrates this repository, but this package is not available in conda-forge, so this PR adds an option `FRAMEWORK_COMPILE_Ros1Publisher` to disable the compilation of the `BipedalLocomotion::YarpUtilities::RosPublisher` class that depends on `rosmsg`, and also deprecates the class so that it can be removed in the future.
> Add option FRAMEWORK_COMPILE_Ros1Publisher and deprecate  BipedalLocomotion::YarpUtilities::RosPublisher class

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/CMakeLists.txt
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- devices/YarpRobotLoggerDevice/thrifts/YarpRobotLoggerDeviceCommands.thrift
This PR aims to add a rpc command to the `YarpLoggerDevice`.
This command should be used to trigger YarpLoggerDevice to save data to local file (which currently is only possible by closing the device itself with ctrl+c).
I have added a command which saves according to the method `robometry::SaveCallbackSaveMethod::periodic`.
> Add rpc commands to YarpLoggerDevice

- CHANGELOG.md
- src/Contacts/include/BipedalLocomotion/ContactDetectors/FixedFootDetector.h
- src/Contacts/src/FixedFootDetector.cpp
Add a member function to return current time of` fixed foot detector`.
> Add member function to return current time of fixed foot detector

- CHANGELOG.md
- src/Planners/include/BipedalLocomotion/Planners/UnicycleTrajectoryGenerator.h
- src/Planners/src/UnicycleTrajectoryGenerator.cpp
This PR adds a member function to set the feet measured transform in the Unicycle Trajectory Generator
The feet measured transforms are used by the unicycle planner when regenerating the trajectory.
> Enable the setting of the measured feet transform for the Unicycle Trajectory Generator

- CHANGELOG.md
- src/TSID/include/BipedalLocomotion/TSID/VariableRegularizationTask.h
Thanks to  #828, one can build a TSID object programmatically.
This PR adds the `VariableRegularizationTask` to the list of tasks that can be built programmatically.
> Enable Programmatic Creation of  VariableRegularizationTask  

- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
The prints introduced in https://github.com/ami-iit/bipedal-locomotion-framework/pull/910 were not working properly
> Fixed some prints of the logger device

- bindings/python/ML/src/VelMANNAutoregressive.cpp
- bindings/python/ML/src/VelMANNTrajectoryGenerator.cpp
- devices/FloatingBaseEstimatorDevice/include/BipedalLocomotion/FloatingBaseEstimatorDevice.h
- devices/RobotDynamicsEstimatorDevice/include/BipedalLocomotion/RobotDynamicsEstimatorDevice.h
- src/Estimators/CMakeLists.txt
- src/Estimators/tests/FloatingBaseEstimators/CMakeLists.txt
- src/ML/src/VelMANNAutoregressive.cpp
- src/ML/src/VelMANNTrajectoryGenerator.cpp
- src/ML/tests/VelMANNTrajectoryGeneratorTest.cpp
Fix CMake warnings:
~~~
2025-02-19T07:19:21.4248687Z CMake Warning (dev) at /usr/share/miniconda3/envs/test/lib/cmake/BipedalLocomotionFramework/BipedalLocomotionFrameworkTargets.cmake:222 (set_target_properties):
2025-02-19T07:19:21.4250227Z   The library that is being linked to, iDynTree::idyntree-modelio-urdf, is
2025-02-19T07:19:21.4251015Z   marked as being deprecated by the owner.  The message provided by the
2025-02-19T07:19:21.4251627Z   developer is:
2025-02-19T07:19:21.4251824Z 
2025-02-19T07:19:21.4252113Z   Do not use deprecated target iDynTree::idyntree-modelio-urdf, use
2025-02-19T07:19:21.4252725Z   iDynTree::idyntree-modelio instead.
2025-02-19T07:19:21.4253030Z 
~~~
and compilation warnings:
~~~
2025-02-19T07:14:16.1240459Z …
> Fix iDynTree warnings

- CHANGELOG.md
- cmake/BipedalLocomotionFrameworkDependencies.cmake
Adding this line allows us to install correctly the application [motor-current-tracking
](https://github.com/ami-iit/bipedal-locomotion-framework/tree/master/utilities/motor-current-tracking)
cc @GiulioRomualdi
> Add option FRAMEWORK_COMPILE_MotorCurrentTrackingApplication in cmake file

- .github/workflows/conda-forge-ci.yml
`cmake-package-check` on Windows uses `Ninja`, that needs to be run under `cmd.exe` as the activation scripts of Visual Studio do not run on bash. I have no idea how it worked before. I am not a big fan of all the duplication between Windows and Linux/macOS, but that is already how the CI job is implemented.
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/940 .
> Do not run cmake-package-check on Windows under bash

- CHANGELOG.md
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN002/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGazeboV3/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
- src/RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h
- src/RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp
- src/RobotInterface/include/BipedalLocomotion/RobotInterface/ISensorBridge.h
This PR mitigates https://github.com/ami-iit/bipedal-locomotion-framework/issues/819 in the case of motor temperature. Thanks to https://github.com/robotology/yarp/pull/3188, the motor temperature will now be streamed in `stateExt`, eliminating the need for RPC calls between `controlboard_nws` and `RemoteControlBoard`.
> Add motor temperature sensor support to SensorBridge and YarpSensorBridge and logger

- CHANGELOG.md
- devices/JointTorqueControlDevice/include/BipedalLocomotion/JointTorqueControlDevice.h
- devices/JointTorqueControlDevice/src/JointTorqueControlDevice.cpp
This PR introduces some minor changes.
- Removed unused functions to clean up the code.
- Added saturation of friction torque when joint velocity exceeds a threshold.
- Removed the controlLoop time check since it is already handled by the YARP thread.
> Improve JointTorqueControl device

- CHANGELOG.md
- bindings/python/RobotInterface/CMakeLists.txt
- devices/YarpRobotLoggerDevice/CMakeLists.txt
I started updating `tiny-process-lib` and `cvnp` to fix the CMake 4.0.0 configuration failures, but while I doing so I reviewed cvnp history, and I noticed that there was some numpy 2.0 fixes (see https://github.com/pthom/cvnp/issues/17 and https://github.com/pthom/cvnp/commit/d2b808a0b6faeb025647973cb966e728e816d6d2) that were not included in blf. 
As the ICameraBridge Python bindings do not have test coverage, it is possible that there were already broken with numpy 2 and we did not realized as numpy 1 was still used in the environment where the ICameraBridge Python bindings is used, so updating cvnp to the latest version is probably beneficial also for numpy 2 support.
I had to use a checkout and not a tag for `tiny-process-lib` as there was no tag with the required fixes for CMake …
> Update version of tiny-process-lib and cvnp to fix usage with CMake 4 and numpy 2

- CHANGELOG.md
- CMakeLists.txt
- cmake/BipedalLocomotionFrameworkDependencies.cmake
- src/Conversions/CMakeLists.txt
- src/Planners/CMakeLists.txt
- src/ReducedModelControllers/CMakeLists.txt
casadi 3.7.0 was recently released, with a breaking change from the CMake point of view, quoting from https://github.com/casadi/casadi/releases/tag/3.7.0 : 
> breaking The casadi cmake target now has a namespace. The preferred way of configuring your cmake is:
> ```cmake
> find_package(casadi CONFIG REQUIRED)
> 
> add_executable(casadi_demo casadi_demo.cpp)
> target_link_libraries(casadi_demo casadi::casadi)
> ```
This PR changes the CMake code to always link the `casadi::casadi` imported target. Support for casadi < 3.7.0 is mantained by appropriately defining an alias target named `casadi::casadi` for the `casadi` imported target.
As defining ALIAS for non-global imported targets requires at least CMake 3.18.0 (see  https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4837), and …
> Support compilation with casadi >= 3.7.0

- .github/workflows/ci.yml
The CI job was broken by the recent update to CMake 4.0.0 in GitHub Actions images (see https://github.com/ami-iit/bipedal-locomotion-framework/actions/runs/14210180719), and we fixed it by setting the `CMAKE_POLICY_VERSION_MINIMUM` to `3.5`.
Furthermore, while debugging https://github.com/ami-iit/bipedal-locomotion-framework/pull/953 I noticed that the "Check build if some dependencies are not enabled" check takes forever, as every time a dependency is enabled or disabled the whole Python bindings are recompiled. To avoid that, we disable the Python bindings before the check and re-enable it later.
> Fix Ubuntu 20.04 CI job

- CHANGELOG.md
- src/RobotInterface/CMakeLists.txt
- utilities/realsense-test/CMakeLists.txt
Instead, we link the `realsense-test` (that uses the PCL visualizer) to the whole `${PCL_LIBRARIES}`.
See https://github.com/robotology/robotology-superbuild/pull/1842#issuecomment-2790076032 for the context of this PR.
> Only link pcl_common to PerceptionInterface instead of the full PCL_LIBRARIES

- CHANGELOG.md
- devices/JointTorqueControlDevice/include/BipedalLocomotion/JointTorqueControlDevice.h
- devices/JointTorqueControlDevice/include/BipedalLocomotion/PINNFrictionEstimator.h
- devices/JointTorqueControlDevice/include/BipedalLocomotion/PassThroughControlBoard.h
- devices/JointTorqueControlDevice/src/JointTorqueControlDevice.cpp
- devices/JointTorqueControlDevice/src/PINNFrictionEstimator.cpp
- devices/JointTorqueControlDevice/src/PassThroughControlBoard.cpp
Since we started using motor temperature as additional input for friction estimation via PINN (see for example https://github.com/ami-iit/element_sensorless-torque-control/issues/219 and https://github.com/ami-iit/element_sensorless-torque-control/issues/204), we need to modify the `JointTorqueControlDevice` accordingly. 
cc @isorrentino @GiulioRomualdi
> Modify JointTorqueControlDevice to use motor temperature as additional input for PINN (friction estimation)

- src/Estimators/tests/RobotDynamicsEstimator/CMakeLists.txt
Fix https://github.com/ami-iit/bipedal-locomotion-framework/issues/967 .
We could even avoid to download the model if `BUILD_TESTING` is `OFF`, but that is the minimal change that fixes https://github.com/ami-iit/bipedal-locomotion-framework/issues/967 .
> Fix wrong URL and hash for ergoCubSN001 model in RobotDynamicsEstimator tests

- cmake/BipedalLocomotionFrameworkDependencies.cmake
Similar to https://github.com/ami-iit/bipedal-locomotion-framework/pull/973, `FRAMEWORK_COMPILE_ManifConversions` was used before being defined in the definition of `FRAMEWORK_COMPILE_RobotDynamicsEstimator`.
> Define FRAMEWORK_COMPILE_ManifConversions before FRAMEWORK_COMPILE_RobotDynamicsEstimator

- .github/workflows/conda-forge-ci.yml
A few days ago, the Windows CI started to fail as we were using VS2019, while the OpenCV package (that we were not pinning) was updated to be built and required VS2022 (see https://github.com/conda-forge/opencv-feedstock/issues/471). 
While we could fix the problem either upstream by trying to compile again opencv with VS2019 or pin opencv to an older version, as anyhow more and more packages will migrate to VS2022 (see https://github.com/conda-forge/conda-forge.github.io/issues/2138) and given that packages built with VS2022 can be dependencies built with VS2019, while packages built with VS2019 can't use dependencies built wtih VS2022, I think the easiest fix is just to update the Windows CI to use vs2022 instead of vs2019.
> conda-ci: On Windows migrate to use VS2022

- bindings/python/RobotInterface/src/SensorBridge.cpp
Introduce methods for retrieving joint acceleration data in the YarpSensorBridge Python bindings
> Add joint acceleration retrieval methods to YarpSensorBridge python bindings

- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
Switch YarpRobotLoggerDevice to utilize an absolute clock for its periodic threads.
> Update YarpRobotLoggerDevice to use absolute clock for periodic threads

- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN002/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGazeboV3/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- devices/YarpRobotLoggerDevice/tests/yarp-robot-logger.xml
I have touched the logger code to allow the following:
- avoid logging the code status
- avoid logging the cameras with a single parameter
- avoid logging the robot.
The last point has been the trickiest, since most of the preparation work was done in the ``attachAll`` method. When not using the robot nor the cameras, it would be possible not to have any device attached. Hence, I had to make sure that the logger was properly started even when the ``attachAll`` method was not called.
I also took the occasion to introduce a few auxiliary methods to make the opening and preparation phases cleaner
> Added possibility to avoid logging code status, robot and cameras

- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubGazeboV1_1/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN000/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN001/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/ergoCubSN002/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGazeboV3/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/app/robots/iCubGenova09/yarp-robot-logger.xml
- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
For our data acquisitions, we had the need of storing short strings coming from a yarp port.
I assume that this data would not be streamed for the real time logging, also considering that it relies on ``VectorsCollection`` (that does not handle strings)
> Allow logging text exogenous signals

- bindings/python/TSID/tests/test_TSID.py
Without this, the test fail on numpy 2 with error:
~~~
E           AttributeError: `np.infty` was removed in the NumPy 2.0 release. Use `np.inf` instead.
~~~
`np.inf` is available also on numpy 1.21 (see https://numpy.org/doc/1.21/reference/constants.html#numpy.inf), that is the version of numpy available via apt on Ubuntu 22.04 (see https://repology.org/project/python%3Anumpy/versions), so this does not remove any compatibility for any older numpy version that it still make sense to support.
> Use np.inf instead of np.infty in test_TSID.py for NumPy 2.0 compatibility

- devices/YarpRobotLoggerDevice/include/BipedalLocomotion/YarpRobotLoggerDevice.h
- devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp
- devices/YarpRobotLoggerDevice/thrifts/YarpRobotLoggerDeviceCommands.thrift
This PR does the following:
- Adds a reset on the image index number after saving. This allows the frame index to restart from zero after ``saveData`` is called.
- Adds the possibility to add a tag in the name before saving the data. This allows to tag the logs while storing it.
- Reduces the chance of race conditions between the video, the run and the RPC thread.
- Applies the clang format to the device sources.
> Improved logger saving mechanism when using the RPC

- cmake/BipedalLocomotionFrameworkDependencies.cmake
Without this fix, configuration against Eigen 5 fails with:
~~~
CMake Error at cmake/OsqpEigenDependencies.cmake:14 (find_package):
Could not find a configuration file for package "Eigen3" that is compatible
with requested version "3.2.92".
The following configuration files were considered but not accepted:
/home/runner/work/robotology-superbuild/robotology-superbuild/.pixi/envs/default/share/eigen3/cmake/Eigen3Config.cmake, version: 5.0.0
Call Stack (most recent call first):
~~~
see https://gitlab.com/libeigen/eigen/-/issues/2972 for more details. As Eigen 3.3 was released in 2016, I think we are fine in just asking for Eigen without checking the version of it.
xref: https://github.com/conda-forge/eigen-feedstock/pull/47
xref: https://github.com/robotology/robotology-superbuild/issues/190 …
> Remove version constraint for Eigen3 package for Eigen3 5.0.0 compat
